import {useEffect,useRef,useState,type FormEvent,type PointerEvent} from 'react';
import type {GameRenderProps,GameView} from '../../../shared/types';
import {TypingTransport} from './typing-transport';
import './party.css';

type Stroke={strokeId:string;color:string;width:number;tool:'pen'|'eraser';points:number[][]};
const ink=['#000000','#ef4c70','#ff922b','#f1c232','#29a86b','#3485ef','#9259dc','#ffffff'];
function paint(ctx:CanvasRenderingContext2D,stroke:Stroke){if(!stroke.points.length)return;ctx.strokeStyle=stroke.tool==='eraser'?'#ffffff':stroke.color;ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=stroke.width;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();const [first,...rest]=stroke.points;ctx.moveTo(first[0]*1000,first[1]*700);for(const [x,y]of rest)ctx.lineTo(x*1000,y*700);if(!rest.length){ctx.arc(first[0]*1000,first[1]*700,stroke.width/2,0,Math.PI*2);ctx.fill();}else ctx.stroke();}
export function DoodleCanvas({strokes=[],editable=false,send,small=false,onBusy}:{strokes?:Stroke[];editable?:boolean;send?:(a:any)=>void;small?:boolean;onBusy?:(busy:boolean)=>void}){
  const canvas=useRef<HTMLCanvasElement>(null),active=useRef<Stroke|null>(null),queue=useRef<any[]>([]),gesture=useRef(0),current=useRef({send,onBusy,editable});current.current={send,onBusy,editable};const [color,setColor]=useState(ink[0]),[width,setWidth]=useState(8),[confirmClear,setConfirmClear]=useState(false);
  const enqueue=(packet:any)=>{queue.current.push(packet);onBusy?.(true);};
  const flush=(finish=false)=>{const stroke=active.current;if(!stroke)return;if(stroke.points.length>1||finish)enqueue({type:'stroke',...stroke});active.current=finish?null:{...stroke,points:[stroke.points.at(-1)!]};};
  useEffect(()=>{const interval=setInterval(()=>{if(!current.current.editable){queue.current=[];active.current=null;current.current.onBusy?.(false);return;}const stroke=active.current;if(stroke&&stroke.points.length>1){queue.current.push({type:'stroke',...stroke});active.current={...stroke,points:[stroke.points.at(-1)!]};}const packet=queue.current.shift();if(packet)current.current.send?.(packet);current.current.onBusy?.(queue.current.length>0||!!active.current);},36);return()=>{clearInterval(interval);current.current.onBusy?.(false);};},[]);
  useEffect(()=>{const ctx=canvas.current?.getContext('2d');if(!ctx)return;ctx.fillStyle='#ffffff';ctx.fillRect(0,0,1000,700);for(const s of strokes)paint(ctx,s);for(const packet of queue.current)if(packet.type==='stroke')paint(ctx,packet);if(active.current)paint(ctx,active.current);},[strokes]);
  const point=(e:PointerEvent<HTMLCanvasElement>)=>{const rect=e.currentTarget.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width)),Math.max(0,Math.min(1,(e.clientY-rect.top)/rect.height))];};
  return <div className={`doodle-board ${small?'compact':''}`}>
    <canvas ref={canvas} width={1000} height={700} aria-label={editable?'Drawing canvas: drag to draw':'Player drawing'} className={editable?'editable':''}
      onPointerDown={e=>{if(!editable)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);active.current={strokeId:`s${Date.now().toString(36)}_${gesture.current++}`,tool:color==='#ffffff'?'eraser':'pen',color,width,points:[point(e)]};onBusy?.(true);const ctx=e.currentTarget.getContext('2d');if(ctx)paint(ctx,active.current);}}
      onPointerMove={e=>{if(!editable||!active.current)return;const next=point(e),previous=active.current.points.at(-1)!;if(Math.hypot(next[0]-previous[0],next[1]-previous[1])<0.0015)return;active.current.points.push(next);const ctx=e.currentTarget.getContext('2d');if(ctx)paint(ctx,{...active.current,points:[previous,next]});if(active.current.points.length>=80)flush();}}
      onPointerUp={()=>flush(true)} onPointerCancel={()=>flush(true)} />
    {editable&&<div className="doodle-tools"><div className="ink-colors" aria-label="Pen color">{ink.map(c=><button key={c} type="button" aria-label={c==='#ffffff'?'Eraser':`Ink ${c}`} aria-pressed={color===c} className={color===c?'selected':''} style={{background:c}} onClick={()=>setColor(c)}>{c==='#ffffff'?'⌫':''}</button>)}</div><label>Width <select aria-label="Pen width" value={width} onChange={e=>setWidth(Number(e.target.value))}>{[3,8,16,30].map(w=><option key={w}>{w}</option>)}</select></label><button type="button" onClick={()=>enqueue({type:'undo'})}>Undo stroke</button>{confirmClear?<><button type="button" onClick={()=>{enqueue({type:'clear',confirm:true});setConfirmClear(false);}}>Confirm clear</button><button type="button" onClick={()=>setConfirmClear(false)}>Cancel</button></>:<button type="button" onClick={()=>setConfirmClear(true)}>Clear</button>}</div>}
  </div>;
}

function AnswerForm({send,disabled=false,numeric=false,placeholder='Type your answer',label='Lock in answer',min,max,initial=''}:{send:(value:any)=>void;disabled?:boolean;numeric?:boolean;placeholder?:string;label?:string;min?:number;max?:number;initial?:string}){
  const [value,setValue]=useState(initial);const submit=(e:FormEvent)=>{e.preventDefault();if(!value.trim()||disabled)return;send(numeric?Number(value):value);if(!numeric)setValue('');};
  return <form className="party-answer" onSubmit={submit}><input autoComplete="off" spellCheck={false} aria-label={placeholder} type={numeric?'number':'text'} inputMode={numeric?'decimal':'text'} step="any" min={min} max={max} maxLength={120} value={value} disabled={disabled} placeholder={placeholder} onChange={e=>setValue(e.target.value)}/><button type="submit" disabled={disabled||!value.trim()}>{label}</button></form>;
}
function TypeRace({view,send,disabled,name}:{view:GameView;send:(a:any)=>void;disabled:boolean;name:(id:string)=>string}){
  const [text,setText]=useState(view.yourText??''),transport=useRef(new TypingTransport());const state=useRef({text,server:view.yourText??'',ack:view.typingAck,disabled});state.current={text,server:view.yourText??'',ack:view.typingAck,disabled};
  useEffect(()=>setText((previous:string)=>previous.startsWith(view.yourText)?previous:view.yourText),[view.yourText]);
  useEffect(()=>{const interval=setInterval(()=>{const packet=transport.current.next(state.current,Date.now());if(packet)send(packet);},85);return()=>clearInterval(interval);},[send]);
  return <><p className="typing-phrase">{view.phrase.split('').map((c:string,i:number)=><span key={i} className={i<view.yourText.length?'correct-letter':i<text.length&&text[i]!==c?'wrong-letter':i===view.yourText.length?'current-letter':''}>{c}</span>)}</p><textarea className="typing-input" aria-label="Type the displayed sentence" autoComplete="off" autoCorrect="off" autoCapitalize="off" spellCheck={false} maxLength={view.phrase.length} value={text} disabled={disabled} onPaste={e=>e.preventDefault()} onDrop={e=>e.preventDefault()} onChange={e=>{const typo=text.split('').findIndex((c:string,i:number)=>c!==view.phrase[i]);if(typo>=0&&e.target.value.length>text.length)return;if(e.target.value.length<=text.length+1&&e.target.value.startsWith(view.yourText))setText(e.target.value);}} placeholder="Start typing here…"/>
    <p className="party-muted">Green characters are server-confirmed. Backspace to remove a typo before continuing. Paste is disabled.</p>{view.paceFlag&&<p className="party-muted">Your sustained pace is above 300 WPM. Your validated typing still counts.</p>}<div className="typing-racers">{view.racers?.map((r:any)=><div key={r.id}><div className="party-row"><b>{name(r.id)}</b><span>{r.finished?'Finished':`${r.wpm} WPM · ${r.accuracy}% accuracy`}</span></div><progress value={r.progress} max={1}/></div>)}</div></>;
}
function TelephoneShow({chains,name}:{chains:any[][];name:(id:string)=>string}){
  const [position,setPosition]=useState(0),[auto,setAuto]=useState(false);const entries=chains.flatMap((chain,index)=>chain.map((item,step)=>({item,chain:index,step}))),current=entries[position%entries.length];
  useEffect(()=>{if(!auto)return;const timer=setInterval(()=>setPosition(p=>(p+1)%entries.length),5000);return()=>clearInterval(timer);},[auto,entries.length]);
  return <div className="telephone-reveal"><h3>The transformations</h3><p className="party-muted">A shared story, no competitive winner. Use the controls or play a five-second slideshow.</p><div className="party-options">{chains.map((_,i)=><button key={i} className={current.chain===i?'selected':''} onClick={()=>setPosition(chains.slice(0,i).reduce((n,c)=>n+c.length,0))}>Chain {i+1}</button>)}</div><div className="telephone-timeline"><article><span className="party-eyebrow">Chain {current.chain+1} · Step {current.step+1} · {name(current.item.author)}</span>{current.item.skipped&&<p className="party-muted">This player did not submit before the deadline.</p>}{current.item.kind==='drawing'?<DoodleCanvas strokes={current.item.strokes}/>:<h3>{current.item.text}</h3>}</article></div><div className="slideshow-controls"><button onClick={()=>setPosition(p=>(p-1+entries.length)%entries.length)}>← Back</button><button aria-pressed={auto} onClick={()=>setAuto(v=>!v)}>{auto?'Pause slideshow':'Auto · 5 seconds'}</button><button onClick={()=>setPosition(p=>(p+1)%entries.length)}>Next →</button></div></div>;
}
function Reveal({view,name}:{view:GameView;name:(id:string)=>string}){
  const r=view.reveal??{};
  if(r.chains)return <TelephoneShow chains={r.chains} name={name}/>;
  return <div className="party-reveal"><span className="party-eyebrow">Round revealed</span>
    {r.answer!==undefined&&<><h3 className="reveal-answer">{String(r.answer)}</h3>{r.unit&&<p>{r.unit}</p>}</>}
    {r.exploded&&<h3>💥 {name(r.exploded)} held the bomb!</h3>}
    {r.impostor&&<p>The impostor was <strong>{name(r.impostor)}</strong>. {r.caught?'The room caught them!':'They escaped the vote.'}</p>}
    {r.finalGuess&&<p>Their final guess: <strong>{r.finalGuess}</strong></p>}
    {r.oddPlayer&&<p><strong>{name(r.oddPlayer)}</strong> was {view.id==='the-liar'?'the liar':'the odd artist'}. {r.caught?'Identified!':'They fooled the room.'}</p>}
    {r.oddPrompt&&<p>The different assignment was <strong>{r.oddPrompt}</strong>.</p>}
    {r.solver&&<p>Found by <strong>{name(r.solver)}</strong>{r.guesses?` in ${r.guesses} room guesses`:''}.</p>}
    {r.current!==undefined&&<div className="card-reveal"><span>{r.current}</span><b>→</b><span>{r.next}</span><p>{r.correct==='equal'?'Equal — everyone is safe.':`The next card was ${r.correct}.`}</p></div>}
    {r.item&&<><h3>{r.item}</h3><p>{r.winner?`${name(r.winner)} paid ${r.bid} coins and gained ${r.value} points.`:'Nobody submitted a bid.'}</p></>}
    {r.clue&&<p>Clue: <strong>{r.clue}</strong></p>}
    {r.clues&&<div className="party-result-list">{r.clues.map((c:any,i:number)=><div key={i}><b>Clue {c.number} · Team {c.team+1}</b><span>{c.clue}{c.guess?` → ${c.guess}`:''}</span></div>)}</div>}
    {r.solvers&&<p>{r.solvers.length?`Solved by ${r.solvers.map(name).join(', ')}.`:'Nobody found it. Final private distance and fewer guesses determined round points.'}</p>}
    {r.bids&&<div className="party-result-list">{Object.entries(r.bids).map(([p,bid])=><div key={p}><b>{name(p)}</b><span>Bid ${String(bid)} · Cash ${r.budgets[p]} · Assets ${r.assets[p]}</span></div>)}</div>}
    {r.lastWord&&<p>Final word: <strong>{r.lastWord}</strong></p>}
    {r.winner&&view.id==='word-chain'&&<p>Last player: <strong>{name(r.winner)}</strong></p>}
    {r.sequence&&<p className="sequence-reveal">{r.sequence.map((v:number)=>v+1).join(' → ')}</p>}
    {r.phrase&&<p>{r.phrase}</p>}
    {r.finishers&&Object.keys(r.finishers).length>0&&<div className="party-result-list">{Object.entries(r.finishers).sort(([,a],[,b])=>Number(a)-Number(b)).map(([p,rank])=><div key={p}><b>#{String(rank)} {name(p)}</b></div>)}</div>}
    {r.gallery&&<div className="party-gallery">{r.gallery.map((e:any)=><article key={e.index}>{e.strokes?<DoodleCanvas strokes={e.strokes} small/>:<p>{e.text}</p>}<b>{name(e.author)}</b>{e.author===r.oddPlayer&&<span className="party-badge">{view.id==='the-liar'?'Liar':'Odd assignment'}</span>}</article>)}</div>}
    {Array.isArray(r.options)&&r.options[0]?.text&&<div className="party-result-list">{r.options.map((o:any,i:number)=><div key={i}><strong>{o.text}{o.text===r.answer?' ✓ Truth':''}</strong><span>{o.owners.length?`Written by ${o.owners.map(name).join(', ')}`:'The real answer'}</span><small>{o.voters.length?`Chosen by ${o.voters.map(name).join(', ')}`:'No votes'}</small></div>)}</div>}
    {r.answers&&<div className="party-result-list">{Object.entries(r.answers).map(([p,a])=><div key={p}><strong>{name(p)}</strong><span>{r.options?.[Number(a)]??(typeof a==='boolean'?(a?'Correct':'Missed'):String(a))}{r.validity&&` · ${r.validity[p]?'Accepted':'Outside the category list'}`}</span></div>)}</div>}
    {r.counts&&<div className="answer-distribution">{Object.entries(r.counts).map(([a,n])=>{const total=Object.values(r.counts).reduce((sum:number,v:any)=>sum+Number(v),0) as number;const percent=Math.round(Number(n)/Math.max(1,total)*100);return <div key={a}><div className="party-row"><b>{r.options?.[Number(a)]??name(a)}</b><span>{String(n)} · {percent}%</span></div><div className="distribution-track"><span style={{width:`${percent}%`}}/></div></div>;})}</div>}
    {r.distribution&&<div className="party-result-list">{r.distribution.map((d:any,i:number)=><div key={i}><b>{d.text}{d.correct?' ✓':''}</b><span>{d.count} answer{d.count===1?'':'s'}</span></div>)}</div>}
    {r.estimates&&<div className="party-result-list">{r.estimates.map((e:any)=><div key={e.id}><b>{name(e.id)}</b><span>{e.value} · error {e.error}</span></div>)}</div>}
    {r.examples&&<p>Accepted examples: {r.examples.join(', ')}</p>}
    {r.votes&&<div className="party-result-list">{Object.entries(r.votes).map(([p,a])=><div key={p}><strong>{name(p)}</strong><span>Voted for {typeof a==='string'?name(a):`entry ${Number(a)+1}`}</span></div>)}</div>}
    <p className="party-muted">Scores are calculated by the server. The next screen starts automatically.</p>
  </div>;
}

export default function PartyGame({view,send,playerId,players,now,spectator}:GameRenderProps){
  const name=(id:string)=>players.find(p=>p.id===id)?.name??'Player';const disabled=spectator||!view.canPlay||(view.youSubmitted&&!view.canChange)||(view.pending&&now>=view.pending.confirmAt);const key=`${view.id}-${view.round}-${view.phase}`;
  const submit=(value:any)=>send({type:'submit',value});const [canvasBusy,setCanvasBusy]=useState(false);
  const myTurn=view.current===playerId;
  const waiting=<p className="party-wait" role="status">{spectator?'You are spectating.':view.waitingNextRound?'You rejoined during playback. You will play the next round.':!view.canPlay?'Your run is over. Watch the remaining players.':view.youSubmitted?'Answer locked. Waiting for the room…':'Watch the current player.'}</p>;
  let content;
  if(view.phase==='reveal'||view.phase==='finished')content=<Reveal key={key} view={view} name={name}/>;
  else if(view.id==='draw-guess')content=<><div className="party-prompt"><span className="party-eyebrow">{name(view.drawer)} is drawing · {view.category}</span><h3 className="word-hint">{view.secret??view.hint}</h3></div><DoodleCanvas key={key+'-canvas'} strokes={view.strokes} editable={!spectator&&view.drawer===playerId} send={send}/>{view.drawer!==playerId&&!disabled?<AnswerForm key={key} send={submit} label="Guess" placeholder="What is the drawing?"/>:view.drawer===playerId?<p className="party-muted">Draw your secret word without writing letters.</p>:waiting}<div className="guess-feed" aria-live="polite">{view.chat?.map((c:any,i:number)=><p key={i}><b>{name(c.id)}</b> {c.text}</p>)}</div></>;
  else if(view.id==='impostor-word')content=<><div className="private-card"><span className="party-eyebrow">{view.role==='impostor'?'Your secret role: impostor':view.role?'Your private word':'Discussion round'}</span><h3>{view.secret??`Category: ${view.category}`}</h3>{view.role==='impostor'&&<p>Blend in. Listen for clues to the word.</p>}</div>{view.phase==='read'?<p>Read your private card. Discussion begins when the timer ends.</p>:view.phase==='discuss'?<><p>Share a short clue, then discuss who might be bluffing.</p>{!disabled&&!view.clues?.some((c:any)=>c.id===playerId)&&<AnswerForm key={key} send={submit} label="Share clue" placeholder="A clue without the word"/>}<div className="party-result-list">{view.clues?.map((c:any)=><div key={c.id}><b>{name(c.id)}</b><span>{c.text}</span></div>)}</div></>:view.phase==='vote'?<><h3>Who is the impostor?</h3><p className="party-muted">Your vote is private. Change it until the timer ends.</p><div className="party-options">{players.filter(p=>view.alive?.includes(p.id)&&p.id!==playerId).map(p=><button key={p.id} disabled={disabled} className={view.yourChoice===p.id?'selected':''} onClick={()=>submit(p.id)}>{p.name}{view.yourChoice===p.id?' ✓':''}</button>)}</div>{disabled&&waiting}</>:<><h3>{name(view.guesser)} was caught and gets one final word guess.</h3>{view.guesser===playerId&&!spectator?<AnswerForm key={key} send={submit} label="Final guess"/>:waiting}</>}</>;
  else if(view.id==='type-race')content=<TypeRace key={view.round} view={view} send={send} disabled={disabled} name={name}/>;
  else if(view.id==='bomb-pass')content=<><div className="bomb-display">💣</div><h3>{name(view.holder)} has the bomb</h3><p className="party-muted">{view.last} The explosion time is hidden.</p>{view.holder===playerId&&!disabled?(view.unlocked?<><h3>Correct! Pass it now.</h3><div className="party-options">{players.filter(p=>view.alive.includes(p.id)&&p.id!==playerId&&p.connected).map(p=><button key={p.id} onClick={()=>send({type:'pass',target:p.id})}>Pass to {p.name} →</button>)}</div></>:view.challengeStatus==='retry'?<p className="party-wait">New challenge in one second…</p>:<div className="private-card"><span className="party-eyebrow">Your private challenge</span><h3>{view.challenge?.question}</h3>{view.challenge?.options?<div className="party-options">{view.challenge.options.map((option:string,i:number)=><button key={i} onClick={()=>submit(i)}>{option}</button>)}</div>:<AnswerForm key={`${key}-${view.phaseStart}`} send={submit} label="Solve to unlock pass" placeholder="Your answer"/>}</div>):<p>Solve your challenge when the bomb reaches you. Its fuse continues across passes.</p>}</>;
  else if(view.id==='guess-drawing')content=view.phase==='draw'?<><div className="private-card"><span className="party-eyebrow">Your private assignment</span><h3>{view.secret??'Artists are drawing'}</h3><p>Draw it without letters. Keep your prompt private.</p></div><DoodleCanvas key={key+'-canvas'} strokes={view.strokes} editable={!disabled} send={send} onBusy={setCanvasBusy}/><button className="party-primary" disabled={disabled||canvasBusy} onClick={()=>send({type:'submit'})}>Drawing complete</button>{disabled&&waiting}</>:<><h3>{view.phase==='inspect'?'Inspect the anonymous gallery':'Which artist had a different assignment?'}</h3>{view.phase==='inspect'&&<p>Voting opens when the inspection timer ends.</p>}<div className="party-gallery">{view.gallery?.map((g:any)=><article key={g.index}><span className="party-eyebrow">Drawing {String.fromCharCode(65+g.index)}</span><DoodleCanvas small strokes={g.strokes}/><button disabled={disabled||g.yours||view.phase!=='vote'} onClick={()=>submit(g.index)}>{g.yours?'Your drawing':`Vote ${String.fromCharCode(65+g.index)}`}</button></article>)}</div>{disabled&&waiting}</>;
  else if(view.id==='word-chain')content=<><span className="party-eyebrow">{name(view.current)}’s turn</span><h3 className="word-hint">{view.previous}</h3><p>Start your word with <strong>{view.previous?.slice(-1).toUpperCase()}</strong></p><p className="party-muted">{view.last}</p>{myTurn&&!disabled?<AnswerForm key={`${key}-${view.previous}`} send={submit} label="Play word" placeholder={`Word beginning with ${view.previous?.slice(-1)}`}/>:waiting}<p className="party-muted">Used: {view.used?.join(', ')}</p></>;
  else if(view.id==='memory-mayhem'||view.id==='sequence')content=<><h3>{view.phase==='show'?'Watch and remember':'Repeat the pattern'}</h3><p>{view.phase==='show'?`${view.length} steps · Wait until playback ends.`:`${view.progress??0} / ${view.length} entered · Two mistakes end your run.`}</p><div className={`memory-pads pads-${view.size}`}>{Array.from({length:view.size},(_,i)=><button key={i} aria-label={`Pad ${i+1}`} style={{'--pad-color':ink[(i+1)%7]} as any} className={view.phase==='show'&&view.currentPad===i&&now<view.lightUntil?'lit':''} disabled={disabled||view.phase==='show'} onClick={()=>submit(i)}>{i+1}</button>)}</div>{disabled&&waiting}</>;
  else if(view.id==='the-liar')content=<><h3>{view.question}</h3>{view.phase==='write'?<><div className="private-card"><strong>{view.role==='liar'?'You are the liar. Invent an answer that is not true for you.':view.role?'Answer truthfully. One player will bluff.':'Players are writing privately.'}</strong></div>{!disabled?<AnswerForm key={key} send={submit} placeholder="Your short response"/>:waiting}</>:<><p>{view.phase==='inspect'?'Discuss the anonymous answers before voting opens.':'Who is bluffing? Vote for one anonymous answer.'}</p><div className="party-gallery">{view.gallery?.map((g:any)=><article key={g.index}><p>“{g.text}”</p><button disabled={disabled||g.yours||view.phase!=='vote'} onClick={()=>submit(g.index)}>{g.yours?'Your answer':`Vote answer ${g.index+1}`}</button></article>)}</div>{disabled&&waiting}</>}</>;
  else if(view.id==='higher-lower')content=<><span className="party-eyebrow">Shuffled deck · values 1–13</span><div className="number-card">{view.current}</div><h3>Will the next card be higher or lower?</h3><div className="party-options"><button disabled={disabled} onClick={()=>submit('higher')}>↑ Higher</button><button disabled={disabled} onClick={()=>submit('lower')}>↓ Lower</button></div><p className="party-muted">Equal cards are safe. Two strikes eliminate you.</p>{disabled&&waiting}</>;
  else if(view.id==='auction-wars')content=<><div className="auction-item">✦</div><span className="party-eyebrow">Lot {view.round} of {view.maxRounds} · {view.category}</span><h3>{view.item}</h3><p>{view.description}</p><div className="private-card">Your available budget: <strong>${view.budgets?.[playerId]??'—'}</strong>{view.yourBid!==undefined&&<p>Current sealed bid: <strong>${view.yourBid}</strong></p>}</div>{!disabled?<AnswerForm key={key} numeric min={0} max={view.budgets?.[playerId]} send={submit} label={view.yourBid!==undefined?'Revise sealed bid':'Seal bid'} placeholder="Bid whole dollars"/>:waiting}<p className="party-muted">Change your bid before time ends. Tied highest bids favor the earliest final bid. Final score = assets + 25% of remaining cash.</p></>;
  else if(view.id==='doodle-telephone')content=<><h3>{view.phase==='phrase'?'Start a drawing story':view.phase==='draw'?'Draw this phrase':'Describe this drawing'}</h3>{view.assignment?.kind==='text'&&<div className="private-card"><h3>{view.assignment.text}</h3></div>}{view.assignment?.kind==='drawing'&&<DoodleCanvas strokes={view.assignment.strokes}/>}<p className="party-muted">Only you see this assignment. It passes to the next player when everyone finishes. This story awards participation.</p>{view.phase==='draw'?<><DoodleCanvas key={key+'-canvas'} strokes={view.strokes} editable={!disabled} send={send} onBusy={setCanvasBusy}/><button className="party-primary" disabled={disabled||canvasBusy} onClick={()=>send({type:'submit'})}>Pass my drawing</button></>:!disabled?<AnswerForm key={key} send={submit} label="Pass phrase" placeholder={view.phase==='phrase'?'A silly, drawable phrase':'What do you see?'}/>:null}{disabled&&waiting}</>;
  else if(view.id==='hangman-battle')content=<><h3 className="word-hint">{view.mask}</h3><p>{6-view.mistakes} chances left</p><div className="hangman-progress" aria-label={`${view.mistakes} wrong guesses`}>{Array.from({length:6},(_,i)=><span key={i} className={i<view.mistakes?'lost':''}>◆</span>)}</div><div className="letter-keyboard">{'abcdefghijklmnopqrstuvwxyz'.split('').map(c=><button key={c} disabled={disabled||view.letters?.includes(c)} onClick={()=>submit(c)}>{c.toUpperCase()}</button>)}</div>{!disabled?<AnswerForm key={key} send={submit} label="Solve word" placeholder="Or guess the whole word"/>:waiting}</>;
  else if(view.id==='password')content=<><div className="party-teams">{view.teams?.map((team:string[],i:number)=><div key={i} className={i===view.team?'active':''}><b>Team {i+1}</b><span>{team.map(name).join(' · ')}</span></div>)}</div><span className="party-eyebrow">Clue {view.clueNumber} of 4 · worth {5-view.clueNumber} points</span><h3>{name(view.giver)} gives a clue</h3>{view.secret&&<div className="private-card"><span className="party-eyebrow">Your private password · clue-giver only</span><h3>{view.secret}</h3></div>}{view.clue&&<div className="password-clue"><span className="party-eyebrow">The clue</span><h3>{view.clue}</h3></div>}{view.phase==='clue'&&view.giver===playerId&&!spectator?<AnswerForm key={`${key}-${view.clueNumber}`} send={submit} label="Give clue" placeholder="One token; letters and hyphens"/>:view.phase==='guess'&&view.members?.includes(playerId)&&!view.givers?.includes(playerId)&&!disabled?<><p>Your team gets one collective guess. Discuss it first.</p><AnswerForm key={`${key}-${view.clueNumber}`} send={submit} label="Team’s only guess" placeholder="One word"/></>:waiting}<div className="party-result-list">{view.clues?.map((c:any,i:number)=><div key={i}><b>Team {c.team+1}: {c.clue}</b><span>{c.guess?`Guessed ${c.guess}`:'Awaiting a guess'}</span></div>)}</div></>;
  else if(view.id==='secret-number')content=<><span className="party-eyebrow">Your private deduction race · {view.attempts??0} / 20 guesses</span><h3 className="number-range">{view.low} <span>…</span> {view.high}</h3><p>Your hints and guesses are visible only to you. Everyone races at the same time.</p>{!disabled?<AnswerForm key={`${key}-${view.history?.length}`} numeric min={1} max={1000} send={submit} label="Guess number" placeholder={`Your narrowed range: ${view.low}–${view.high}`}/>:waiting}<div className="party-result-list">{view.history?.slice(-10).reverse().map((g:any,i:number)=><div key={i}><b>You guessed {g.value}</b><span>{g.hint==='correct'?'✓ Exact!':g.hint==='higher'?'↑ Go higher':'↓ Go lower'}</span></div>)}</div></>;
  else content=<><div className="party-prompt">{view.emoji&&<div className="emoji-clue">{view.emoji}</div>}{view.scramble&&<h3 className="word-hint scramble">{view.scramble}</h3>}{view.letter&&<span className="category-letter">{view.letter}</span>}<h3>{view.question??(view.emoji?'What do these emoji mean?':view.scramble?'Unscramble the word':'Enter your answer')}</h3>{view.id==='fake-answer'&&<p>{view.phase==='write'?'Invent a convincing false answer.':'Find the real answer. You cannot vote for your own fake.'}</p>}{view.id==='majority-rules'&&<p>Choose the option you think most players will select. Tied top groups earn 300.</p>}{view.id==='minority-rules'&&<p>The smallest nonempty group earns 500. Equal occupied groups all earn 250.</p>}{view.id==='would-you-rather'&&<p>Match the strict majority for 500. An even split gives everyone 250.</p>}</div>{view.options?.length>0?<div className="party-options">{view.options.map((option:string,i:number)=><button key={i} className={view.yourChoice===i||view.pending?.value===i?'selected':''} disabled={disabled||view.disabledOptions?.includes(i)} onClick={()=>submit(i)}><span className="option-letter">{String.fromCharCode(65+i)}</span>{option}{view.disabledOptions?.includes(i)&&<small>Your fake</small>}</button>)}</div>:!disabled?<AnswerForm key={key} numeric={view.id==='speed-math'||view.id==='closest-wins'} min={view.min} max={view.max} send={submit} label={['emoji-guess','word-scramble'].includes(view.id)?'Guess':'Lock in answer'} placeholder={view.id==='closest-wins'?`Your numeric estimate${view.unit?` (${view.unit})`:''}`:view.id==='fake-answer'?'Your believable fake':view.id==='speed-math'?'Your calculated answer':'Your answer'}/>:null}{view.pending&&<p className="party-feedback" role="status">{now<view.pending.confirmAt?'Confirming selection… you may change it now.':'Selection confirmed.'}</p>}{view.canChange&&view.youSubmitted&&<p className="party-muted">Your selection is saved privately. You can change it until the timer ends.</p>}{view.feedback&&!view.youSubmitted&&<p className="party-feedback" role="status">{view.feedback}</p>}{disabled&&waiting}</>;
  return <section className="party-game"><details className="party-rules"><summary>How to play</summary><p>{view.instructions}</p></details><div className="party-content">{content}</div>{view.phase!=='reveal'&&view.phase!=='finished'&&<div className="party-status"><span>{view.submitted?.length??0} / {view.alive?.length??players.length} locked in</span>{view.strikes?.[playerId]>0&&<span>Your strikes: {view.strikes[playerId]}</span>}<span>Round {view.round} / {view.maxRounds}</span></div>}</section>;
}
