import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {arcadeDefinitions,ArenaGame,ButtonBashGame,DifferenceGame,GolfGame,golfCourses,GridGame,RaceGame,ReactionGame,SnakeGame,snakeCollisions,TerritoryGame,type Snake} from '../server/games/arcade.js';
const players=[{id:'a',name:'Ada',color:'#aa88ff'},{id:'b',name:'Bea',color:'#66ddcc'}];
const context=(config:Record<string,number>={})=>({config,matchIndex:0});
const snake=(body:{x:number;y:number}[],direction=1):Snake=>({body,direction,queued:direction,alive:true});

test('all eighteen revised arcade definitions initialize, validate membership, serialize safely and finish while AFK',()=>{
  assert.equal(arcadeDefinitions.length,18);
  for(const d of arcadeDefinitions){const ps=Array.from({length:d.metadata.min},(_,i)=>({id:`p${i}`,name:`Player ${i}`,color:'#aabbcc'})),game=d.init(ps,1000);assert.ok(d.metadata.instructions.length>60,d.metadata.id);assert.equal(game.id,d.metadata.id);game.join('spectator',1100);game.leave(ps[0].id,1200);game.reconnect(ps[0].id,1300);assert.doesNotThrow(()=>JSON.stringify(game.publicState()));assert.doesNotThrow(()=>JSON.stringify(game.privateState('spectator')));assert.throws(()=>game.input('spectator',{type:'claim'},1400));assert.throws(()=>game.input(ps[0].id,{type:'invented-score',score:99999},1400));
    for(let t=1100;t<=600000&&!game.done;t+=100)game.tick(t,100);assert.equal(game.done,true,`${d.metadata.id} must not deadlock`);assert.ok(Object.values(game.scores).every(Number.isFinite),d.metadata.id);game.cleanup();assert.doesNotThrow(()=>JSON.stringify(game.serialize(null)));}
});

test('territory waits for simultaneous resolution; support decides conflicts and ties preserve ownership',()=>{
  const game=new TerritoryGame(players,0);assert.equal(game.w,24);assert.equal(game.h,18);game.cells.fill(null);game.cells[25]='a';game.cells[2]='a';game.cells[27]='b';game.input('a',{type:'claim',x:2,y:1},100);game.input('b',{type:'claim',x:2,y:1},200);assert.equal(game.cells[26],null);assert.equal(game.serialize('a').selected,26);assert.equal(game.publicState().selected,null);assert.equal(game.serialize('b').selected,26);game.tick(3000,100);assert.equal(game.cells[26],'a');assert.equal(game.round,2);
  const tie=new TerritoryGame(players,0);tie.cells.fill(null);tie.cells[25]='a';tie.cells[27]='b';tie.input('a',{type:'claim',x:2,y:1},1);tie.input('b',{type:'claim',x:2,y:1},2);tie.tick(3000,100);assert.equal(tie.cells[26],null);
});
test('enemy territory requires strictly greater support and enclosures convert only neutral regions',()=>{
  const game=new TerritoryGame(players,0);game.cells.fill(null);game.cells[25]='a';game.cells[26]='b';game.cells[27]='b';game.input('a',{type:'claim',x:2,y:1},1);game.tick(3000,100);assert.equal(game.cells[26],'b');game.cells[2]='a';game.input('a',{type:'claim',x:2,y:1},3100);game.tick(6000,100);assert.equal(game.cells[26],'a');
  for(const occupant of [null,'b']){const enclosed=new TerritoryGame(players,0);enclosed.cells.fill(null);for(const[x,y]of [[5,5],[6,5],[7,5],[5,6],[7,6],[5,7],[6,7]])enclosed.cells[y*24+x]='a';enclosed.cells[6*24+6]=occupant;enclosed.input('a',{type:'claim',x:7,y:7},500);enclosed.tick(3000,100);assert.equal(enclosed.cells[6*24+6],occupant==='b'?'b':'a');}
});
test('territory settings are meaningful and pending choices remain private',()=>{const g=new TerritoryGame(players,1000,context({rounds:2,turnSeconds:1}));g.input('a',{type:'claim',x:1,y:0},1100);assert.equal(g.deadline,2000);assert.equal(g.serialize('b').selected,null);g.tick(2000,100);g.tick(3000,100);assert.equal(g.done,true);});

test('snake wall, body, simultaneous head-on and head-swap collisions are authoritative',()=>{
  const snakes={a:snake([{x:2,y:2},{x:1,y:2},{x:0,y:2}]),b:snake([{x:4,y:2},{x:5,y:2},{x:6,y:2}],3)};
  assert.deepEqual([...snakeCollisions(snakes,{a:{x:3,y:2},b:{x:3,y:2}},new Set(),10,10)].sort(),['a','b']);assert.equal(snakeCollisions(snakes,{a:{x:-1,y:2}},new Set(),10,10).has('a'),true);assert.equal(snakeCollisions(snakes,{a:{x:5,y:2}},new Set(),10,10).has('a'),true);assert.deepEqual([...snakeCollisions(snakes,{a:{x:4,y:2},b:{x:2,y:2}},new Set(),10,10)].sort(),['a','b']);
});
test('snake can enter a vacating tail but not a growing tail',()=>{const snakes={a:snake([{x:2,y:2},{x:2,y:3},{x:3,y:3},{x:3,y:2}])},heads={a:{x:3,y:2}};assert.equal(snakeCollisions(snakes,heads,new Set(),10,10).size,0);assert.equal(snakeCollisions(snakes,heads,new Set(['a']),10,10).has('a'),true);});
test('snake uses the 50×36 grid, length four and fixed 10Hz; food and survivor rankings are authoritative',()=>{
  const game=new SnakeGame(players,0),a=game.snakes.a;assert.equal(game.w,50);assert.equal(game.h,36);assert.equal(a.body.length,4);assert.throws(()=>game.input('a',{type:'direction',direction:3},10));const x=a.body[0].x;game.food=[{x:x+1,y:a.body[0].y}];game.tick(99,99);assert.equal(a.body[0].x,x);game.tick(100,1);assert.equal(a.body.length,5);assert.equal(game.scores.a,10);game.tick(300,100);assert.equal(a.body[0].x,x+3);
  game.scores.b=200;game.snakes.b.body=[{x:0,y:1},{x:1,y:1},{x:2,y:1},{x:3,y:1}];game.snakes.b.direction=3;game.snakes.b.queued=3;game.tick(400,100);assert.equal(game.done,true);assert.ok(game.placementScores.a>game.placementScores.b);assert.equal(game.scores.b,200);
});

test('25×19 perfect maze has a connected legal exit path and gives separate finishing placements',()=>{
  const g=new GridGame('maze-race',players,0);assert.equal(g.w,25);assert.equal(g.h,19);assert.ok(Number.isFinite(g.pathDistances[g.w+1]));g.input('a',{type:'direction',direction:0},200);assert.equal(g.pawns.a.y,1);const exit=g.exit.y*g.w+g.exit.x;const before=[{dx:-1,dy:0,d:1},{dx:0,dy:-1,d:2}].find(o=>g.cells[exit+o.dy*g.w+o.dx]!==-1)!;Object.assign(g.pawns.a,{x:g.exit.x+before.dx,y:g.exit.y+before.dy,lastMove:0});g.input('a',{type:'direction',direction:before.d},500);assert.equal(g.pawns.a.finished,true);assert.equal(g.done,false);g.tick(g.deadline,100);assert.equal(g.done,true);assert.ok(g.placementScores.a>g.placementScores.b);
});
test('last tile crumbles after 700ms and color dash rescues one mistake before eliminating',()=>{
  const last=new GridGame('last-tile',players,0),tile=last.pawns.a.y*last.w+last.pawns.a.x;assert.equal(last.w,25);assert.equal(last.h,18);last.input('a',{type:'direction',direction:1},200);last.tick(899,100);assert.equal(last.cells[tile],0);last.tick(900,1);assert.equal(last.cells[tile],-1);
  const color=new GridGame('color-dash',players,0);for(let round=0;round<2;round++){color.target=2;color.cells[color.pawns.a.y*color.w+color.pawns.a.x]=2;color.cells[color.pawns.b.y*color.w+color.pawns.b.x]=3;color.tick(color.nextEvent,100);if(!round){assert.equal(color.pawns.b.alive,true);assert.equal(color.strikes.b,1);color.tick(color.nextEvent,100);}}assert.equal(color.pawns.b.alive,false);assert.equal(color.done,true);
});
test('platform panic enforces 200ms moves and warns five or more tiles for one second',()=>{const g=new GridGame('platform-panic',players,0);assert.equal(g.w,9);assert.equal(g.h,9);g.input('a',{type:'direction',direction:1},100);const x=g.pawns.a.x;g.input('a',{type:'direction',direction:1},200);assert.equal(g.pawns.a.x,x);g.tick(2500,100);const warned=Object.keys(g.warnings);assert.ok(warned.length>=5&&warned.length<=12);assert.ok(warned.every(k=>g.warnings[+k]===3500));g.tick(3499,100);assert.ok(warned.every(k=>g.cells[+k]!==-1));g.tick(3500,1);assert.ok(warned.every(k=>g.cells[+k]===-1));});

test('arena normalizes diagonal movement, validates inputs, and stops stale intentions',()=>{const g=new ArenaGame('coin-rush',players,0),p=g.pawns.a,x=p.x,y=p.y;g.input('a',{type:'move',x:1,y:1},100);g.tick(200,100);assert.ok(Math.abs(Math.hypot(p.x-x,p.y-y)-26)<.001);const px=p.x;g.tick(1000,100);assert.equal(p.x,px);assert.throws(()=>g.input('a',{type:'move',x:NaN,y:0},1100));assert.throws(()=>g.input('a',{type:'score',score:9999},1100));assert.equal(g.coins.length,15);});
test('pixel battle has 100HP, 25 damage, server kills, and invulnerable respawns',()=>{
  const g=new ArenaGame('pixel-battle',players,0);assert.equal(g.w,1600);assert.equal(g.h,900);assert.equal(g.pawns.a.health,100);Object.assign(g.pawns.a,{x:70,y:70,immune:0});Object.assign(g.pawns.b,{x:180,y:70,immune:0,health:25});g.input('a',{type:'fire',x:180,y:70},500);g.input('a',{type:'fire',x:180,y:70},501);assert.equal(g.bullets.length,1);for(let t=550;t<=900;t+=50)g.tick(t,50);assert.equal(g.pawns.b.alive,false);assert.equal(g.scores.a,1);assert.equal(g.pawns.b.deaths,1);assert.equal(g.pawns.a.damage,25);g.tick(3000,100);assert.equal(g.pawns.b.alive,true);assert.equal(g.pawns.b.health,100);assert.equal(g.pawns.b.immune,4500);
});
test('all pixel spawn counts and respawns avoid cover and other pawns',()=>{for(let count=2;count<=12;count++){const ps=Array.from({length:count},(_,i)=>({id:`p${i}`,name:`P${i}`,color:'#abc'})),g=new ArenaGame('pixel-battle',ps,0);const clear=()=>{const pawns=Object.values(g.pawns);for(const p of pawns){assert.ok(p.x>=18&&p.x<=g.w-18&&p.y>=18&&p.y<=g.h-18);assert.ok(!g.obstacles.some(w=>p.x+18>w.x&&p.x-18<w.x+w.w&&p.y+18>w.y&&p.y-18<w.y+w.h));}for(let i=0;i<pawns.length;i++)for(let j=i+1;j<pawns.length;j++)assert.ok(Math.hypot(pawns[i].x-pawns[j].x,pawns[i].y-pawns[j].y)>36);};clear();for(const p of Object.values(g.pawns))Object.assign(p,{alive:false,respawnAt:2000});g.tick(2000,0);clear();}});
test('crown tagging drops instead of transferring, locks previous holder, then accumulates milliseconds',()=>{
  const g=new ArenaGame('capture-crown',players,0);Object.assign(g.pawns.a,g.center);Object.assign(g.pawns.b,{x:100,y:100});g.tick(100,100);assert.equal(g.holder,'a');Object.assign(g.pawns.b,g.center);g.tick(600,100);assert.equal(g.holder,null);assert.equal(g.pawns.a.pickupLock,1600);assert.ok(g.scores.a>0);g.tick(650,50);assert.equal(g.holder,'b');g.pawns.b.hold=29999;g.tick(700,50);assert.equal(g.done,true);assert.ok(g.scores.b>=30000);
});
test('sumo shrink begins after 30s, dash cooldown is two seconds, and crossing radius plus pawn eliminates',()=>{
  const g=new ArenaGame('sumo-circles',players,0);g.input('a',{type:'dash',x:1,y:0},100);const impulse=g.pawns.a.ix;g.input('a',{type:'dash',x:1,y:0},101);assert.equal(g.pawns.a.ix,impulse);g.tick(29000,0);assert.equal(g.radius,400);g.tick(40000,0);assert.ok(g.radius<400);Object.assign(g.pawns.b,{x:g.center.x+g.radius+29,y:g.center.y});g.tick(40050,0);assert.equal(g.pawns.b.alive,false);assert.equal(g.done,true);
});
test('dodge telegraphs large hazards and coin stealing honors victim protection',()=>{
  const dodge=new ArenaGame('dodge',players,0);for(let i=0;i<100&&!dodge.bullets.some(b=>b.shape==='rect');i++)dodge.spawnHazard(1000);const big=dodge.bullets.find(b=>b.shape==='rect')!;assert.ok(big);assert.equal(big.activateAt,1600);const x=big.x,y=big.y;dodge.tick(1200,100);assert.equal(big.x,x);assert.equal(big.y,y);
  const coin=new ArenaGame('coin-rush',players,0);coin.scores.b=2;Object.assign(coin.pawns.a,{x:600,y:350,dashUntil:500});Object.assign(coin.pawns.b,{x:600,y:350});coin.tick(100,0);assert.equal(coin.scores.a,1);assert.equal(coin.scores.b,1);coin.tick(150,0);assert.equal(coin.scores.a,1);assert.equal(coin.scores.b,1);
});

test('six JSON golf holes have pars and geometry; scoring uses raw ascending strokes and cap penalties',()=>{
  assert.equal(golfCourses.length,6);assert.equal(new Set(golfCourses.map(c=>JSON.stringify(c))).size,6);assert.ok(golfCourses.every(c=>c.par>0));assert.ok(golfCourses.some(c=>c.circles.length));assert.ok(golfCourses.some(c=>c.hazards.length));const g=new GolfGame(players,0);assert.equal(g.scoreDirection,'asc');g.input('a',{type:'shot',x:1,y:0,power:100},0);assert.throws(()=>g.input('a',{type:'shot',x:1,y:0,power:100},1));Object.assign(g.pawns.a,{...golfCourses[0].hole,vx:0,vy:0});g.tick(100,100);assert.equal(g.pawns.a.holed,true);g.tick(90000,100);assert.equal(g.holeIndex,1);assert.equal(g.totals.a,1);assert.equal(g.totals.b,12);assert.equal(g.scores.a,1);assert.throws(()=>g.input('a',{type:'shot',x:1,y:0,power:101},90001));
});
test('golf fixed steps are independent of frame size and out of bounds resets with a penalty',()=>{
  const a=new GolfGame(players,0),b=new GolfGame(players,0);a.input('a',{type:'shot',x:1,y:0,power:70},0);b.input('a',{type:'shot',x:1,y:0,power:70},0);a.tick(100,100);for(let i=1;i<=6;i++)b.tick(i*100/6,100/6);assert.ok(Math.abs(a.pawns.a.x-b.pawns.a.x)<1e-8);const origin={...a.pawns.a.shotOrigin};Object.assign(a.pawns.a,{x:-10,vx:0,vy:0});a.tick(200,100);assert.equal(a.pawns.a.x,origin.x);assert.equal(a.pawns.a.strokes,2);Object.assign(a.pawns.a,{strokes:10,vx:0,vy:0});a.tick(300,100);assert.equal(a.pawns.a.strokes,12);assert.equal(a.pawns.a.capped,true);
});

test('red light hides future phases, eliminates persistent RUN after 100ms, and keeps finisher placements',()=>{
  const g=new RaceGame('red-light',players,0);assert.equal(g.length,100);assert.equal('switchAt' in g.publicState(),false);g.light='red';g.lightChanged=1000;g.switchAt=5000;g.input('a',{type:'run',run:true},1000);g.tick(1100,50);assert.equal(g.pawns.a.alive,true);g.tick(1101,1);assert.equal(g.pawns.a.alive,false);g.light='green';g.pawns.b.x=99.9;g.input('b',{type:'run',run:true},1200);g.tick(1250,50);assert.equal(g.pawns.b.finished,true);assert.equal(g.done,true);assert.ok(g.placementScores.b>g.placementScores.a);
});
test('one-button racing uses a shared seeded course, hold height, grounded jumps and checkpoint resets',()=>{
  const a=new RaceGame('one-button-racing',players,0),b=new RaceGame('one-button-racing',players,0);assert.ok(a.obstacles.length>0&&a.pits.length>0);a.input('a',{type:'jump',held:true},0);b.input('a',{type:'jump',held:true},0);b.input('a',{type:'jump',held:false},1);for(let t=50;t<=300;t+=50){a.tick(t,50);b.tick(t,50);}assert.ok(a.pawns.a.z>b.pawns.a.z);const vz=a.pawns.a.vz;a.input('a',{type:'jump',held:true},310);assert.equal(a.pawns.a.vz,vz);Object.assign(a.pawns.b,{x:a.obstacles[0]-10,z:0,vz:0,checkpoint:0});a.tick(400,50);assert.equal(a.pawns.b.x,0);
});

test('quick draw keeps GO secret, rejects early attempts, awards ranks and caps server-measured latency correction',()=>{
  const g=new ReactionGame('quick-draw',players,0,{...context(),latencyMs:{a:500,b:0}});assert.equal(g.phase,'ready');g.tick(2000,100);assert.equal(g.phase,'waiting');assert.equal(g.publicState().deadline,0);assert.equal('triggerAt' in g.publicState(),false);g.input('a',{type:'react',eventAt:g.triggerAt+50},g.triggerAt+250);assert.equal(g.answers.a.ms,200);g.input('b',{type:'react'},g.triggerAt+400);assert.equal(g.phase,'reveal');assert.equal(g.scores.a,5);assert.equal(g.scores.b,3);assert.equal(g.tieBreaks.a[0],-200);
  const early=new ReactionGame('quick-draw',players,0);early.input('a',{type:'react'},100);early.input('a',{type:'react'},200);assert.equal(early.scores.a,0);assert.equal(early.answers.a.penaltyMs,1000);assert.equal(early.serialize('b').yourResult,null);assert.equal(early.serialize('b').answers,undefined);
});
test('reaction tournament covers all six mini-games, no-click scoring and server-validated alternating inputs',()=>{
  const g=new ReactionGame('reaction-tournament',players,0);assert.equal(new Set(g.modes.slice(0,6)).size,6);assert.equal('modes' in g.publicState(),false);g.mode='decoy';g.tick(g.triggerAt,0);g.input('a',{type:'react'},g.triggerAt+100);g.tick(g.deadline,0);assert.equal(g.scores.a,0);assert.equal(g.scores.b,1000);
  const alt=new ReactionGame('reaction-tournament',players,0);alt.mode='alternate';alt.tick(alt.triggerAt,0);alt.input('a',{type:'react',choice:4},alt.triggerAt+100);alt.input('a',{type:'react',choice:4},alt.triggerAt+200);alt.input('a',{type:'react',choice:5},alt.triggerAt+300);alt.tick(alt.deadline,0);assert.equal(alt.progress.a.count,2);assert.equal(alt.progress.a.errors,1);assert.equal(alt.scores.a,0);
});
test('button bash reveals only each current command and keeps future command metadata private',()=>{
  const g=new ButtonBashGame(players,0);assert.equal(g.commandSequence.length,100);assert.equal(g.publicState().command,null);assert.equal(g.privateState('a').command,g.commandSequence[0]);const json=JSON.stringify(g.publicState());assert.ok(!json.includes('commandSequence'));assert.ok(!json.includes('shownAt'));g.input('a',{type:'react',choice:g.commandSequence[0],commandIndex:0},200);assert.equal(g.states.a.index,1);assert.equal(g.states.a.deadline,1360);assert.equal(g.states.b.index,0);assert.equal(g.privateState('a').command,g.commandSequence[1]);assert.equal(g.privateState('b').command,g.commandSequence[0]);assert.throws(()=>g.input('a',{type:'react',choice:g.commandSequence[1],commandIndex:0},210));
});
test('button bash wrong commands delay 300ms and simultaneous AFK strikes do not manufacture a winner',()=>{
  const g=new ButtonBashGame(players,0);g.input('a',{type:'react',choice:(g.commandSequence[0]+1)%6,commandIndex:0},100);assert.equal(g.states.a.nextAt,400);assert.equal(g.privateState('a').command,null);g.tick(399,10);assert.equal(g.privateState('a').command,null);g.tick(400,1);assert.equal(g.privateState('a').command,g.commandSequence[1]);
  const afk=new ButtonBashGame(players,0);for(let t=100;t<10000&&!afk.done;t+=100)afk.tick(t,100);assert.equal(afk.done,true);assert.equal(afk.states.a.strikes,3);assert.equal(afk.states.b.strikes,3);assert.equal(afk.placementScores.a,afk.placementScores.b);
});

test('difference scenes randomize object IDs and order, keep exact five hit regions private, and award private finds',()=>{
  const g=new DifferenceGame(players,0);assert.equal(g.left.length,30);assert.equal(g.right.length,29);assert.equal(g.differences.length,5);const leftIds=new Set(g.left.map(o=>o.id));assert.ok(g.right.every(o=>!leftIds.has(o.id)));const publicView=g.publicState();assert.equal(publicView.solution,undefined);const json=JSON.stringify(publicView);assert.ok(!json.includes('differences'));assert.ok(!json.includes('regions'));assert.ok(g.differences.every(d=>!json.includes(d.id)));const p=g.differences[0].marker;g.input('a',{type:'spot',x:p.x/g.w,y:p.y/g.h},1000);assert.equal(g.scores.a,200);assert.equal(g.serialize('a').found.length,1);assert.equal(g.serialize('b').found.length,0);g.input('a',{type:'spot',x:p.x/g.w,y:p.y/g.h},1500);assert.equal(g.scores.a,200);assert.throws(()=>g.input('a',{type:'spot',x:500,y:300},1600));
});
test('wrong difference guesses lock for one second and an all-found bonus is server-calculated',()=>{
  const g=new DifferenceGame(players,0);g.input('a',{type:'spot',x:0,y:0},1000);assert.equal(g.nextGuess.a,2000);const p=g.differences[0].marker;g.input('a',{type:'spot',x:p.x/g.w,y:p.y/g.h},1500);assert.equal(g.scores.a,0);for(const[d,i]of g.differences.map((d,i)=>[d,i] as const))g.input('a',{type:'spot',x:d.marker.x/g.w,y:d.marker.y/g.h},2000+i*300);assert.equal(g.found.a.length,5);assert.ok(g.scores.a>1000&&g.scores.a<=1500);
});

test('every timed arcade engine rejects late inputs without score mutation',()=>{for(const definition of arcadeDefinitions){if(definition.metadata.id==='quick-draw'||definition.metadata.id==='reaction-tournament')continue;const game=definition.init(players,1000),before={...game.scores},deadline=game.publicState().deadline!;assert.throws(()=>game.input('a',{type:'invented-score',score:10000},deadline),/ended/);assert.deepEqual(game.scores,before);}});
test('grid direction release resumes the most recent held key and preserves stopped facing',async()=>{await build({entryPoints:['client/src/games/ArcadeGame.tsx'],outfile:'test-results/arcade-controls.js',bundle:true,format:'esm',platform:'node',packages:'external',jsx:'automatic',loader:{'.css':'empty'},logLevel:'silent'});const {releaseHeldDirection}=await import(pathToFileURL(resolve('test-results/arcade-controls.js')).href);const held=new Set([0,1]);assert.equal(releaseHeldDirection(held,1,1),0);held.add(2);held.add(3);assert.equal(releaseHeldDirection(held,0,3),3);assert.equal(releaseHeldDirection(held,3,3),2);assert.equal(releaseHeldDirection(held,2,2),2);assert.equal(held.size,0);});
test('all eighteen arcade renderers handle player, observer and final states without invalid SVG values',async()=>{
  await build({entryPoints:['client/src/games/ArcadeGame.tsx'],outfile:'test-results/arcade-render.js',bundle:true,format:'esm',platform:'node',packages:'external',jsx:'automatic',loader:{'.css':'empty'},logLevel:'silent'});const {default:ArcadeGame}=await import(pathToFileURL(resolve('test-results/arcade-render.js')).href);
  for(const definition of arcadeDefinitions){const game=definition.init(players,1000);for(const spectator of [false,true]){const html=renderToStaticMarkup(createElement(ArcadeGame,{view:game.serialize(spectator?null:'a'),send:()=>{},playerId:spectator?'observer':'a',players:players.map(p=>({...p,connected:true,ready:true,spectator:false,joinedAt:0,stats:{wins:0,games:0,points:0}})),now:1000,spectator}));assert.ok(html.includes('Objective &amp; controls'),game.id);assert.ok(!/="(?:NaN|undefined)"/.test(html),game.id);}for(let now=1100;now<=600000&&!game.done;now+=100)game.tick(now,100);assert.doesNotThrow(()=>renderToStaticMarkup(createElement(ArcadeGame,{view:game.serialize('a'),send:()=>{},playerId:'a',players,now:600000,spectator:false})),game.id);}
});
