import test from 'node:test';
import assert from 'node:assert/strict';
import {RoomManager,GRACE_MS,rankScores} from '../server/rooms.js';
import {registry} from '../server/games/registry.js';
const token=(n:number)=>'secure-test-token-'+String(n).padStart(24,'0');
const setup=()=>{const messages:{socket:string;event:string;data:any}[]=[];const manager=new RoomManager(registry,(socket,event,data)=>messages.push({socket,event,data}));const host=manager.create('s0','Alex',token(0),1000);return {manager,messages,host,room:manager.rooms.get(host.code)!};};
test('room codes are cryptographic human-readable six characters and names are unique',()=>{const {manager,host,room}=setup();assert.match(host.code,/^[A-HJ-NP-Z2-9]{6}$/);manager.join('s1',host.code.toLowerCase(),'Alex',token(1),1001);assert.deepEqual(room.players.map(p=>p.name),['Alex','Alex 2']);assert.throws(()=>manager.join('x','XXXXXX','Name',token(3),1002),/ROOM_NOT_FOUND/);assert.throws(()=>manager.create('x','',token(3),1002),/NAME_INVALID/);});
test('a bound socket cannot create a duplicate seat or leave a ghost host with another token',()=>{const {manager,host,room}=setup();const guest=manager.join('s1',host.code,'Bee',token(1),1100);assert.throws(()=>manager.join('s0',host.code,'Imposter',token(2),1200),/ALREADY_IN_ROOM/);assert.equal(room.players.length,2);assert.equal(manager.host('s0').player.id,host.playerId);manager.disconnect('s0',1300);assert.equal(room.hostId,guest.playerId);assert.equal(room.players.filter(p=>p.connected).length,1);});
test('host migrates to longest continuously connected member and refresh restores seat',()=>{const {manager,host,room}=setup();const a=manager.join('s1',host.code,'Bee',token(1),2000);manager.join('s2',host.code,'Cee',token(2),3000);manager.disconnect('s0',4000);assert.equal(room.hostId,a.playerId);const restored=manager.join('refresh',host.code,'Ignored',token(0),4500);assert.equal(restored.playerId,host.playerId);assert.equal(room.hostId,a.playerId);assert.equal(room.players.length,3);assert.equal(room.players[0].name,'Alex');});
test('reconnect grace is at least a minute; expired seats and empty rooms are cleaned',()=>{const {manager,room}=setup();assert.ok(GRACE_MS>=60_000);manager.disconnect('s0',2000);manager.tick(2000+GRACE_MS-1,50);assert.equal(room.players.length,1);manager.tick(2000+GRACE_MS+1,50);assert.equal(manager.rooms.size,0);});
test('20 seats, per-game limits, membership and host authorization enforced',()=>{const {manager,host}=setup();for(let i=1;i<20;i++)manager.join('s'+i,host.code,'P'+i,token(i),1000+i);assert.throws(()=>manager.join('overflow',host.code,'P',token(21),1100),/ROOM_FULL/);assert.throws(()=>manager.select('s1','trivia-blitz',1200),/NOT_HOST/);manager.select('s0','connect-four',1200);assert.throws(()=>manager.start('s0',1300),/GAME_FULL/);manager.select('s0','trivia-blitz',1400);manager.start('s0',1500);manager.tick(5500,50);assert.equal(manager.rooms.get(host.code)?.phase,'PLAYING');assert.throws(()=>manager.input('stranger',0,{type:'answer'},5600),/ROOM_NOT_FOUND/);});
test('duplicate and reordered inputs cannot make additional moves; results preserve lobby stats',()=>{const {manager,host,room}=setup();manager.join('s1',host.code,'Bee',token(1),1001);manager.select('s0','connect-four',1100);manager.start('s0',1200);manager.tick(5200,50);manager.input('s0',3,{type:'drop',column:0},5300);manager.input('s0',3,{type:'drop',column:1},5301);manager.input('s0',2,{type:'drop',column:1},5302);assert.equal(room.game!.serialize(null).board.filter(Boolean).length,1);for(let i=0;i<3;i++){manager.input('s1',i,{type:'drop',column:6},5400+i*2);manager.input('s0',i+4,{type:'drop',column:i+1},5401+i*2);}manager.tick(5500,50);assert.equal(room.phase,'RESULTS');assert.equal(room.results[0].playerId,host.playerId);assert.equal(room.players[0].stats.wins,1);manager.lobby('s0',5600);assert.equal(room.phase,'LOBBY');assert.equal(room.players[0].stats.wins,1);assert.equal(room.game,null);});
test('late joins spectate and cannot input; credentials never appear in any snapshot',()=>{const {manager,host,room,messages}=setup();manager.join('s1',host.code,'Bee',token(1),1001);manager.select('s0','crazy-eights',1100);manager.start('s0',1200);manager.tick(5200,50);manager.join('watcher',host.code,'See',token(2),5300);assert.equal(room.players[2].spectator,true);assert.throws(()=>manager.input('watcher',0,{type:'draw'},5400),/INVALID_ACTION/);const view=manager.snapshot(room,room.players[2].id,5500);assert.ok(!JSON.stringify(view).includes(token(0)));assert.ok(!JSON.stringify(view).includes(token(2)));const a=manager.snapshot(room,host.playerId,5500);assert.ok(!JSON.stringify(a).includes('socketId'));for(const message of messages)assert.ok(!JSON.stringify(message.data).includes('secure-test-token'));manager.lobby('s0',5600);assert.ok(room.players.every(p=>!p.spectator));});
test('kick removes membership and blocks the same token from rejoining',()=>{const {manager,host,room}=setup();const guest=manager.join('s1',host.code,'Bee',token(1),1001);manager.kick('s0',guest.playerId,2000);assert.equal(room.players.length,1);assert.throws(()=>manager.join('new',host.code,'Bee',token(1),2100),/KICKED/);assert.throws(()=>manager.input('s1',0,{},2200),/ROOM_NOT_FOUND/);});
test('one vote per player, host resolves selections, and ties share placement',()=>{const {manager,host,room}=setup();manager.join('s1',host.code,'Bee',token(1),1001);manager.vote('s1','snake-arena',1100);manager.vote('s1','coin-rush',1200);assert.deepEqual(Object.values(room.votes),['coin-rush']);assert.deepEqual(rankScores({a:20,b:20,c:10}).map(r=>r.place),[1,1,3]);});
test('abandoned countdown recovers without starting below minimum',()=>{const {manager,host,room}=setup();manager.join('s1',host.code,'Bee',token(1),1001);manager.start('s0',2000);manager.disconnect('s1',2500);manager.tick(7000,50);assert.equal(room.phase,'LOBBY');assert.equal(room.game,null);});
test('a countdown disconnect who misses initialization returns as a spectator until the next game',()=>{
  const {manager,host,room}=setup();manager.join('s1',host.code,'Bee',token(1),1100);const third=manager.join('s2',host.code,'Cee',token(2),1200);manager.select('s0','crazy-eights',1300);manager.start('s0',2000);manager.disconnect('s2',2500);manager.tick(6000,50);
  assert.equal(room.phase,'PLAYING');assert.equal(Object.hasOwn(room.game!.scores,third.playerId),false);assert.equal(room.players.find(p=>p.id===third.playerId)!.spectator,true);
  manager.join('s2-new',host.code,'Cee',token(2),6500);assert.equal(room.players.find(p=>p.id===third.playerId)!.spectator,true);assert.deepEqual(manager.snapshot(room,third.playerId,6600).game!.hand,[]);assert.throws(()=>manager.input('s2-new',0,{type:'draw'},6700),/INVALID_ACTION/);
  manager.lobby('s0',7000);manager.start('s0',7100);manager.tick(11100,50);assert.equal(room.players.find(p=>p.id===third.playerId)!.spectator,false);assert.equal(Object.hasOwn(room.game!.scores,third.playerId),true);assert.equal(manager.snapshot(room,third.playerId,11200).game!.hand.length,5);
});
test('an idempotent join cannot reset duplicate-input protection',()=>{
  const {manager,host,room}=setup();manager.join('s1',host.code,'Bee',token(1),1100);manager.select('s0','connect-four',1200);manager.start('s0',1300);manager.tick(5300,50);manager.input('s0',7,{type:'drop',column:0},5400);manager.input('s1',0,{type:'drop',column:6},5500);
  const originalConnectedAt=room.players[0].connectedAt;manager.join('s0',host.code,'Alex',token(0),5600);assert.equal(room.players[0].lastSeq,7);assert.equal(room.players[0].connectedAt,originalConnectedAt);manager.input('s0',7,{type:'drop',column:1},5700);manager.input('s0',6,{type:'drop',column:2},5750);assert.equal(room.game!.serialize(null).board.filter(Boolean).length,2);manager.input('s0',8,{type:'drop',column:1},5800);assert.equal(room.game!.serialize(null).board.filter(Boolean).length,3);
});
test('an idempotent join preserves continuous-connection seniority for host migration',()=>{
  const {manager,host,room}=setup();const older=manager.join('s1',host.code,'Bee',token(1),2000);manager.join('s2',host.code,'Cee',token(2),3000);manager.join('s1',host.code,'Bee',token(1),4000);assert.equal(room.players.find(p=>p.id===older.playerId)!.connectedAt,2000);manager.disconnect('s0',5000);assert.equal(room.hostId,older.playerId);
});
test('drawing transport sends bounded stroke deltas, preserves privacy, and resets on undo/clear',()=>{
  const {manager,host,room,messages}=setup();manager.join('s1',host.code,'Bee',token(1),1001);manager.start('s0',2000);manager.tick(6000,50);
  const artistId=room.game!.publicState().drawer,artistSocket=room.players.find(p=>p.id===artistId)!.socketId!,guestSocket=room.players.find(p=>p.id!==artistId)!.socketId!;
  manager.broadcastGame(room,6100);messages.length=0;
  manager.input(artistSocket,0,{type:'stroke',strokeId:'first',tool:'pen',points:[[.1,.2],[.2,.3]],color:'#ff0000',width:8},6200);manager.broadcastGame(room,6300);
  const guest=messages.find(m=>m.socket===guestSocket&&m.event==='game:state')!.data;assert.equal(guest.game.strokes,undefined);assert.equal(guest.game.secret,undefined);assert.equal(guest.strokeDelta.from,0);assert.equal(guest.strokeDelta.items.length,1);
  manager.input(artistSocket,1,{type:'stroke',strokeId:'second',tool:'pen',points:[[.2,.3],[.4,.5]],color:'#ff0000',width:8},6400);messages.length=0;manager.broadcastGame(room,6500);
  const next=messages.find(m=>m.socket===guestSocket)!.data;assert.equal(next.strokeDelta.from,1);assert.equal(next.strokeDelta.items.length,1);
  manager.input(artistSocket,2,{type:'undo'},6600);messages.length=0;manager.broadcastGame(room,6700);assert.equal(messages.find(m=>m.socket===guestSocket)!.data.strokeDelta.reset,true);assert.equal(messages.find(m=>m.socket===guestSocket)!.data.strokeDelta.items.length,1);
  manager.input(artistSocket,3,{type:'clear',confirm:true},6800);messages.length=0;manager.broadcastGame(room,6900);assert.equal(messages.find(m=>m.socket===guestSocket)!.data.strokeDelta.reset,true);assert.deepEqual(messages.find(m=>m.socket===guestSocket)!.data.strokeDelta.items,[]);
});