import {randomBytes,randomInt} from 'node:crypto';
import type {GameConfig,GameDefinition,GameInstance,Player,RoomPhase,RoomState,Placement} from '../shared/types.js';
import {clean,assert} from './games/base.js';
import {defaultConfig,validateConfig} from '../shared/game-config.js';
import {ShuffleBag} from './content/shuffle-bag.js';
import {placementPoints,rankScores,securePrivateState} from './games/utilities.js';
export {rankScores} from './games/utilities.js';

export const GRACE_MS=90_000;
const COLORS=['#bdff47','#a89aff','#ff8bb7','#62d8ff','#ffd369','#ff9364','#74edc4','#d4aaff','#f27474','#93baff','#d5e67d','#ffbadd','#7be0df','#ffbc85','#c1a0ff','#d8dbed','#9fda80','#ef90ee','#a3cce5','#eedab0'];
interface Member extends Player {token:string;socketId:string|null;disconnectedAt:number|null;connectedAt:number;lastSeq:number}
export interface Room {code:string;hostId:string;players:Member[];phase:RoomPhase;selectedGame:string;configs:Record<string,GameConfig>;matches:Record<string,number>;content:ShuffleBag;latencyMs:Record<string,number>;votes:Record<string,string>;countdownEnd:number;game:GameInstance|null;results:Placement[];revision:number;lastActivity:number;lastBroadcast:number;banned:Set<string>}
export class RoomManager {
  rooms=new Map<string,Room>(); bindings=new Map<string,{code:string;playerId:string}>();
  private drawings=new Map<string,{game:GameInstance;round:number|undefined;phase:string;count:number;first:any;last:any}>();
  private sentViews=new Map<string,string>();
  constructor(public games:Map<string,GameDefinition>,public emit:(socketId:string,event:string,payload:any)=>void,public disconnectSocket:(socketId:string)=>void=()=>{},public idleMs=7_200_000,public maxRooms=200){}
  validateIdentity(name:unknown,token:unknown){const n=clean(name,25);assert(typeof name==='string'&&n.length>=1&&name.length<=80,'NAME_INVALID');assert(typeof token==='string'&&/^[a-zA-Z0-9_-]{24,128}$/.test(token),'INVALID_SESSION');return {name:n,token:token as string};}
  code(){const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let code:string;do{code=Array.from({length:6},()=>alphabet[randomInt(alphabet.length)]).join('');}while(this.rooms.has(code));return code;}
  create(socketId:string,name:unknown,token:unknown,now:number){const identity=this.validateIdentity(name,token);assert(!this.bindings.has(socketId),'ALREADY_IN_ROOM');assert(this.rooms.size<this.maxRooms,'SERVER_BUSY');const code=this.code();const room:Room={code,hostId:'',players:[],phase:'LOBBY',selectedGame:'draw-guess',configs:{},matches:{},content:new ShuffleBag(),latencyMs:{},votes:{},countdownEnd:0,game:null,results:[],revision:0,lastActivity:now,lastBroadcast:0,banned:new Set()};this.rooms.set(code,room);return this.join(socketId,code,identity.name,identity.token,now);}
  join(socketId:string,code:unknown,name:unknown,token:unknown,now:number){const identity=this.validateIdentity(name,token);assert(typeof code==='string'&&/^[a-zA-Z2-9]{6}$/.test(code),'ROOM_NOT_FOUND');const room=this.rooms.get((code as string).toUpperCase());assert(room,'ROOM_NOT_FOUND');const r=room!;assert(!r.banned.has(identity.token),'KICKED');const binding=this.bindings.get(socketId);assert(!binding||binding.code===r.code,'ALREADY_IN_ROOM');let p=r.players.find(p=>p.token===identity.token);
    assert(!binding||binding.playerId===p?.id,'ALREADY_IN_ROOM');
    if(p){const newConnection=p.socketId!==socketId||!p.connected;if(p.socketId&&p.socketId!==socketId){const old=p.socketId;this.bindings.delete(old);this.drawings.delete(old);this.sentViews.delete(old);this.emit(old,'room:removed','This seat is now open in another tab.');this.disconnectSocket(old);}p.socketId=socketId;p.connected=true;p.disconnectedAt=null;if(newConnection){p.connectedAt=now;p.lastSeq=-1;r.game?.reconnect(p.id,now);}}
    else {assert(r.players.length<20,'ROOM_FULL');const existing=new Set(r.players.map(p=>p.name.toLowerCase()));let unique=identity.name;for(let n=2;existing.has(unique.toLowerCase());n++)unique=identity.name.slice(0,20)+' '+n;p={id:randomBytes(12).toString('hex'),name:unique,token:identity.token,socketId,connected:true,ready:false,spectator:r.phase!=='LOBBY',joinedAt:now,connectedAt:now,disconnectedAt:null,lastSeq:-1,color:COLORS[r.players.length%COLORS.length],stats:{wins:0,games:0,points:0}};r.players.push(p);if(r.game)r.game.join(p.id,now);}
    this.bindings.set(socketId,{code:r.code,playerId:p.id});if(!r.hostId||!r.players.some(p=>p.id===r.hostId&&p.connected))this.migrate(r);r.lastActivity=now;this.broadcast(r,now);return {code:r.code,playerId:p.id,token:p.token};
  }
  get(socketId:string){const b=this.bindings.get(socketId);assert(b,'ROOM_NOT_FOUND');const room=this.rooms.get(b!.code);const player=room?.players.find(p=>p.id===b!.playerId&&p.socketId===socketId);assert(room&&player&&player.connected,'ROOM_NOT_FOUND');return {room:room!,player:player!};}
  host(socketId:string){const ctx=this.get(socketId);assert(ctx.player.id===ctx.room.hostId,'NOT_HOST');return ctx;}
  migrate(room:Room){room.hostId=[...room.players].filter(p=>p.connected).sort((a,b)=>a.connectedAt-b.connectedAt||a.joinedAt-b.joinedAt)[0]?.id||'';}
  disconnect(socketId:string,now:number){const b=this.bindings.get(socketId);if(!b)return;this.bindings.delete(socketId);this.drawings.delete(socketId);this.sentViews.delete(socketId);const r=this.rooms.get(b.code);const p=r?.players.find(p=>p.id===b.playerId&&p.socketId===socketId);if(!r||!p)return;p.connected=false;p.ready=false;p.socketId=null;p.disconnectedAt=now;r.game?.leave(p.id,now);if(r.hostId===p.id)this.migrate(r);this.broadcast(r,now);}
  leave(socketId:string,now:number){const {room,player}=this.get(socketId);this.remove(room,player.id,now);}
  remove(room:Room,id:string,now:number){const p=room.players.find(p=>p.id===id);if(!p)return;if(p.socketId){this.bindings.delete(p.socketId);this.drawings.delete(p.socketId);this.sentViews.delete(p.socketId);}room.game?.leave(p.id,now);room.players=room.players.filter(p=>p.id!==id);delete room.votes[id];if(room.hostId===id)this.migrate(room);if(!room.players.length){this.destroy(room);return;}this.broadcast(room,now);}
  kick(socketId:string,id:unknown,now:number){const {room,player}=this.host(socketId);assert(typeof id==='string'&&id!==player.id,'INVALID_ACTION');const target=room.players.find(p=>p.id===id);assert(target,'INVALID_ACTION');room.banned.add(target!.token);if(target!.socketId)this.emit(target!.socketId,'room:removed','The host removed you from this room.');this.remove(room,target!.id,now);}
  ready(socketId:string,ready:unknown,now:number){const {room,player}=this.get(socketId);assert(room.phase==='LOBBY'&&typeof ready==='boolean','INVALID_ACTION');player.ready=ready as boolean;room.lastActivity=now;this.broadcast(room,now);}
  select(socketId:string,id:unknown,now:number){const {room}=this.host(socketId);assert(room.phase==='LOBBY'||room.phase==='RESULTS','GAME_IN_PROGRESS');assert(typeof id==='string'&&(id==='random'||this.games.has(id)),'INVALID_ACTION');if(id==='random'){const count=room.players.filter(p=>p.connected).length;const options=[...this.games.values()].filter(g=>count>=g.metadata.min&&count<=g.metadata.max);assert(options.length,'NOT_ENOUGH_PLAYERS');id=options[randomInt(options.length)].metadata.id;}room.selectedGame=this.games.get(id as string)!.metadata.id;room.lastActivity=now;this.broadcast(room,now);}
  configure(socketId:string,settings:unknown,reset:unknown,now:number){const {room}=this.host(socketId);assert(room.phase==='LOBBY'||room.phase==='RESULTS','GAME_IN_PROGRESS');assert(reset===undefined||typeof reset==='boolean','INVALID_CONFIG');room.configs[room.selectedGame]=reset?defaultConfig(room.selectedGame):validateConfig(room.selectedGame,settings,room.configs[room.selectedGame]);room.lastActivity=now;this.broadcast(room,now);}
  recordLatency(socketId:string,rtt:number){const binding=this.bindings.get(socketId);if(!binding||!Number.isFinite(rtt)||rtt<0)return;const room=this.rooms.get(binding.code);if(room)room.latencyMs[binding.playerId]=Math.min(50,rtt/2);}
  vote(socketId:string,id:unknown,now:number){const {room,player}=this.get(socketId);assert(room.phase==='LOBBY'||room.phase==='RESULTS','GAME_IN_PROGRESS');assert(typeof id==='string'&&this.games.has(id),'INVALID_ACTION');room.votes[player.id]=this.games.get(id as string)!.metadata.id;room.lastActivity=now;this.broadcast(room,now);}
  start(socketId:string,now:number){const {room}=this.host(socketId);assert(room.phase==='LOBBY'||room.phase==='RESULTS','GAME_IN_PROGRESS');const def=this.games.get(room.selectedGame)!;const participants=room.players.filter(p=>p.connected);assert(participants.length>=def.metadata.min,'NOT_ENOUGH_PLAYERS');assert(participants.length<=def.metadata.max,'GAME_FULL');room.game?.cleanup();room.game=null;for(const p of room.players){p.spectator=!p.connected;p.ready=false;}room.phase='COUNTDOWN';room.countdownEnd=now+3000;room.results=[];room.votes={};room.lastActivity=now;this.broadcast(room,now);}
  lobby(socketId:string,now:number){const {room}=this.host(socketId);room.game?.cleanup();room.game=null;room.phase='LOBBY';room.countdownEnd=0;for(const p of room.players){p.spectator=false;p.ready=false;}room.lastActivity=now;this.broadcast(room,now);}
  input(socketId:string,seq:unknown,action:unknown,now:number){const {room,player}=this.get(socketId);assert(Number.isSafeInteger(seq)&&Number(seq)>=0,'INVALID_ACTION');if(Number(seq)<=player.lastSeq)return;assert(room.phase==='PLAYING'&&room.game&&!player.spectator,'INVALID_ACTION');assert(action&&typeof action==='object'&&!Array.isArray(action),'INVALID_ACTION');player.lastSeq=Number(seq);room.game!.input(player.id,action,now);room.lastActivity=now;}
  finish(room:Room,now:number){if(room.phase!=='PLAYING'||!room.game)return;const game=room.game;room.results=rankScores(game.score(),{direction:game.scoreDirection,placementScores:game.placementScores,tieBreaks:game.tieBreaks}).map(result=>({...result,sessionPoints:placementPoints(result.place,game.participationOnly)}));for(const result of room.results){const p=room.players.find(p=>p.id===result.playerId);if(p){p.stats.games++;p.stats.points+=result.sessionPoints!;if(result.place===1&&!game.participationOnly)p.stats.wins++;}}room.phase='RESULTS';room.game.cleanup();room.lastActivity=now;this.broadcast(room,now);}
  tick(now:number,dt:number){for(const room of this.rooms.values()){
    if(now-room.lastActivity>this.idleMs){this.destroy(room);continue;}
    for(const p of [...room.players])if(!p.connected&&p.disconnectedAt!==null&&now-p.disconnectedAt>GRACE_MS)this.remove(room,p.id,now);
    if(!this.rooms.has(room.code))continue;
    try{if(room.phase==='COUNTDOWN'&&now>=room.countdownEnd){const participants=room.players.filter(p=>p.connected&&!p.spectator);const def=this.games.get(room.selectedGame)!;if(participants.length<def.metadata.min){room.phase='LOBBY';for(const p of room.players)p.spectator=false;this.broadcast(room,now);continue;}const matchIndex=room.matches[room.selectedGame]??0;room.game=def.init(participants.map(({id,name,color})=>({id,name,color})),now,{config:validateConfig(room.selectedGame,room.configs[room.selectedGame]??{}),matchIndex,content:room.content,latencyMs:room.latencyMs});room.matches[room.selectedGame]=matchIndex+1;const participantIds=new Set(participants.map(p=>p.id));for(const p of room.players)p.spectator=!participantIds.has(p.id);room.phase='PLAYING';this.broadcast(room,now);}
      if(room.phase==='PLAYING'&&room.game){room.game.tick(now,Math.min(dt,100));if(room.game.done)this.finish(room,now);else if(now-room.lastBroadcast>=100){this.broadcastGame(room,now);room.lastBroadcast=now;}}
    }catch(error){console.error('Game failure',room.selectedGame,error);room.game?.cleanup();room.game=null;room.phase='LOBBY';for(const p of room.players){p.spectator=false;if(p.socketId)this.emit(p.socketId,'server:error','This round stopped unexpectedly. Your room is still here; choose a game to try again.');}this.broadcast(room,now);}
  }}
  publicPlayer(p:Member):Player {return {id:p.id,name:p.name,color:p.color,connected:p.connected,ready:p.ready,spectator:p.spectator,joinedAt:p.joinedAt,stats:{...p.stats}};}
  gameView(room:Room,you:string|null){return room.game?securePrivateState(room.game,you,new Set(room.players.filter(p=>!p.spectator).map(p=>p.id))):null;}
  snapshot(room:Room,you:string,now:number):RoomState {return {code:room.code,hostId:room.hostId,you,players:room.players.map(p=>this.publicPlayer(p)),phase:room.phase,selectedGame:room.selectedGame,gameConfig:{...defaultConfig(room.selectedGame),...room.configs[room.selectedGame]},votes:{...room.votes},serverTime:now,countdownEnd:room.countdownEnd,game:this.gameView(room,you),results:room.results,revision:room.revision};}
  broadcast(room:Room,now:number){room.revision++;for(const p of room.players)if(p.connected&&p.socketId){this.drawings.delete(p.socketId);this.sentViews.delete(p.socketId);this.emit(p.socketId,'room:state',this.snapshot(room,p.id,now));}}
  broadcastGame(room:Room,now:number){room.revision++;for(const p of room.players)if(p.connected&&p.socketId){const game=this.gameView(room,p.id)!;let strokeDelta:any;
    if(Array.isArray(game.strokes)){const strokes=game.strokes,old=this.drawings.get(p.socketId);const reset=!old||old.game!==room.game||old.round!==game.round||old.phase!==game.phase||old.count>strokes.length||old.count>0&&(old.first!==strokes[0]||old.last!==strokes[old.count-1]);const from=reset?0:old!.count;strokeDelta={reset,from,items:strokes.slice(from)};this.drawings.set(p.socketId,{game:room.game!,round:game.round,phase:game.phase,count:strokes.length,first:strokes[0],last:strokes.at(-1)});delete game.strokes;}
    const signature=JSON.stringify({game,strokeDelta});if(this.sentViews.get(p.socketId)===signature)continue;this.sentViews.set(p.socketId,signature);this.emit(p.socketId,'game:state',{game,strokeDelta,serverTime:now,revision:room.revision});
  }}
  destroy(room:Room){room.game?.cleanup();room.content.clear();for(const p of room.players)if(p.socketId){this.emit(p.socketId,'room:removed','This room has expired. Start a fresh one.');this.bindings.delete(p.socketId);this.drawings.delete(p.socketId);this.sentViews.delete(p.socketId);}this.rooms.delete(room.code);}
  close(){for(const room of [...this.rooms.values()])this.destroy(room);this.drawings.clear();this.sentViews.clear();}
}
