import {randomBytes,randomInt} from 'node:crypto';
import type {GameContext,GamePlayer,GameView} from '../../shared/types.js';
import {assert,number,shuffle} from './base.js';
import {ArcadeBase,clamp,int,seeded,vector} from './arcade-common.js';
export type ReactionResult={status:'early'|'correct'|'wrong'|'miss';ms?:number;points:number;penaltyMs?:number};
export class ReactionGame extends ArcadeBase{
  triggerAt=0;readyUntil=0;revealUntil=0;rounds:number;command=0;answers:Record<string,ReactionResult>={};mode='signal';modes:string[]=[];targets:string[]=[];reactionTotals:Record<string,{ms:number;count:number}>={};progress:Record<string,{count:number;errors:number;next:number;lastAt:number}>={};
  constructor(id:string,players:GamePlayer[],now:number,context?:GameContext){super(id,players,now,context);this.rounds=this.setting('rounds',id==='quick-draw'?7:8);while(this.modes.length<this.rounds)this.modes.push(...shuffle(['signal','arrow','match','target','decoy','alternate']));players.forEach(p=>this.reactionTotals[p.id]={ms:0,count:0});this.setup(now);}
  setup(now:number){this.answers={};this.progress={};this.revealUntil=0;this.phase='ready';this.readyUntil=now+2000;this.triggerAt=this.readyUntil+randomInt(2000,6001);this.deadline=this.readyUntil;this.mode=this.id==='quick-draw'?'signal':this.modes[this.round-1];this.command=this.mode==='target'?randomInt(9):randomInt(4);this.targets=Array(9).fill('◆');if(this.mode==='target')this.targets[this.command]='◇';for(const p of this.players)this.progress[p.id]={count:0,errors:0,next:4,lastAt:0};}
  signal(now:number){if(this.phase==='ready'&&now>=this.readyUntil){this.phase='waiting';this.deadline=0;}if(this.phase==='waiting'&&now>=this.triggerAt){this.phase='signal';this.deadline=this.triggerAt+(this.mode==='alternate'?3000:2000);}}
  corrected(id:string,eventAt:unknown,now:number){const measured=this.context.latencyMs?.[id]??0,allowance=clamp(measured/2,0,50);if(eventAt===undefined)return now-Math.min(allowance,Math.max(0,now-this.triggerAt));const stamp=number(eventAt,now-250,now+50);return now-Math.min(allowance,Math.max(0,now-stamp));}
  input(id:string,a:any,now:number){this.check(id,a,now,false);assert(a.type==='react');if(a.round!==undefined)assert(a.round===this.round,'That prompt has ended.');this.signal(now);if(this.phase==='reveal'||this.answers[id])return;const corrected=this.corrected(id,a.eventAt,now);if(this.phase==='ready'||this.phase==='waiting'||corrected<this.triggerAt){this.answers[id]={status:'early',points:0,penaltyMs:1000};return;}if(now>=this.deadline)return;const choice=a.choice===undefined?-1:int(a.choice,0,8),ms=Math.max(0,Math.round(corrected-this.triggerAt));if(this.mode==='alternate'){const p=this.progress[id];if(now-p.lastAt<65)return;p.lastAt=now;if(choice===p.next){p.count++;p.next=p.next===4?5:4;}else p.errors++;return;}const correct=this.mode==='signal'||this.mode!=='decoy'&&choice===this.command;this.answers[id]={status:correct?'correct':'wrong',ms,points:correct?Math.max(0,1000-Math.floor(ms/2)):0};if(this.players.every(p=>this.answers[p.id]))this.reveal(now);}
  reveal(now:number){if(this.phase==='reveal')return;for(const p of this.players){if(!this.answers[p.id]){if(this.mode==='alternate'){const progress=this.progress[p.id],points=clamp(progress.count*100-progress.errors*200,0,1000);this.answers[p.id]={status:points?'correct':'miss',points,ms:3000};}else if(this.mode==='decoy')this.answers[p.id]={status:'correct',points:1000,ms:2000};else this.answers[p.id]={status:'miss',points:0};}}
    if(this.id==='quick-draw'){const valid=Object.entries(this.answers).filter(([,r])=>r.status==='correct');for(const[id,result]of Object.entries(this.answers)){result.points=result.status==='correct'?([5,3,2][valid.filter(([,r])=>r.ms!<result.ms!).length]??1):0;if(result.status==='correct'){this.reactionTotals[id].ms+=result.ms!;this.reactionTotals[id].count++;}const total=this.reactionTotals[id];this.tieBreaks[id]=[-(total.count?total.ms/total.count:1e9)];}}
    for(const[id,result]of Object.entries(this.answers))this.add(id,result.points);this.phase='reveal';this.revealUntil=now+2000;this.deadline=this.revealUntil;}
  tick(now:number,_dt:number){if(this.done)return;this.signal(now);if(this.phase==='signal'&&now>=this.deadline)this.reveal(now);if(this.phase==='reveal'&&now>=this.revealUntil){if(this.round>=this.rounds)this.finish(now);else{this.round++;this.setup(now);}}}
  serialize(id:string|null):GameView{const visible=this.phase==='signal'||this.phase==='reveal'||this.done;return{...this.base(),kind:'reaction',rounds:this.rounds,mode:this.mode,command:visible&&['arrow','match'].includes(this.mode)?this.command:null,targets:visible&&this.mode==='target'?[...this.targets]:[],yourProgress:id&&this.mode==='alternate'?{...this.progress[id]}:null,yourResult:id?this.answers[id]??null:null,answers:this.phase==='reveal'||this.done?structuredClone(this.answers):undefined};}
}
type BashState={index:number;correct:number;strikes:number;responseTotal:number;shownAt:number;deadline:number;nextAt:number;alive:boolean;completed:boolean};
export class ButtonBashGame extends ArcadeBase{
  commandSequence:number[];states:Record<string,BashState>={};limit:number;
  constructor(players:GamePlayer[],now:number,context?:GameContext){super('button-bash',players,now,context);this.limit=this.setting('rounds',100);this.commandSequence=Array.from({length:this.limit},()=>randomInt(6));this.deadline=now+this.limit*1600+2000;for(const p of players)this.states[p.id]={index:0,correct:0,strikes:0,responseTotal:0,shownAt:now,deadline:now+1200,nextAt:0,alive:true,completed:false};}
  advance(id:string,now:number,correct:boolean,end=true){const s=this.states[id];if(correct){s.correct++;s.responseTotal+=now-s.shownAt;this.scores[id]=s.correct;}else s.strikes++;s.index++;if(s.strikes>=3)s.alive=false;if(s.index>=this.limit)s.completed=true;if(s.alive&&!s.completed){s.nextAt=correct?0:now+300;s.shownAt=correct?now:0;s.deadline=correct?now+Math.max(350,1200-s.correct*40):0;}this.tieBreaks[id]=[-s.strikes,-(s.correct?s.responseTotal/s.correct:1e9)];if(end)this.checkEnd(now);}
  checkEnd(now:number){const alive=Object.values(this.states).filter(s=>s.alive);if(alive.length<=1||Object.values(this.states).every(s=>!s.alive||s.completed)){for(const[id,s]of Object.entries(this.states))this.placementScores[id]=alive.length===1&&s.alive?1e9:this.scores[id];this.finish(now);}}
  input(id:string,a:any,now:number){this.check(id,a,now);assert(a.type==='react');const s=this.states[id];assert(s.alive&&!s.completed&&!s.nextAt&&now<s.deadline,'Wait for your next command.');assert(a.commandIndex===s.index,'That command has ended.');const choice=int(a.choice,0,5);this.advance(id,now,choice===this.commandSequence[s.index]);}
  tick(now:number,_dt:number){if(this.done)return;if(now>=this.deadline){this.finish(now);return;}for(const[id,s]of Object.entries(this.states)){if(!s.alive||s.completed)continue;if(s.nextAt&&now>=s.nextAt){s.nextAt=0;s.shownAt=now;s.deadline=now+Math.max(350,1200-s.correct*40);}else if(!s.nextAt&&now>=s.deadline)this.advance(id,now,false,false);}this.checkEnd(now);}
  serialize(id:string|null):GameView{const s=id?this.states[id]:undefined;return{...this.base(),kind:'bash',limit:this.limit,statuses:Object.fromEntries(Object.entries(this.states).map(([p,s])=>[p,{correct:s.correct,strikes:s.strikes,alive:s.alive,completed:s.completed}])),command:s&&s.alive&&!s.completed&&!s.nextAt&&!this.done?this.commandSequence[s.index]:null,commandIndex:s?.index??null,commandDeadline:s?.deadline??0,nextAt:s?.nextAt??0,yourStatus:s?{correct:s.correct,strikes:s.strikes,alive:s.alive,completed:s.completed}:null};}
}
export class RaceGame extends ArcadeBase{
  length=9000;obstacles:number[]=[];pits:{x:number;w:number}[]=[];light='green';switchAt:number;lightChanged:number;finishOrder:string[]=[];
  constructor(id:string,players:GamePlayer[],now:number,context?:GameContext){super(id,players,now,context);this.deadline=now+this.setting('time',90)*1000;this.switchAt=now+randomInt(1500,4001);this.lightChanged=now;if(id==='red-light')this.length=100;else{const rng=seeded(randomBytes(4).readUInt32LE());for(let x=450;x<this.length-200;x+=480){const at=x+Math.floor(rng()*100);if(Math.floor(x/480)%3===1)this.pits.push({x:at,w:80+Math.floor(rng()*30)});else this.obstacles.push(at);}}players.forEach((p,i)=>this.pawns[p.id]={x:0,y:i,alive:true,lastMove:now,running:false,moving:false,inputAt:0,jumpAt:-10000,held:false,z:0,vz:0,hitAt:-1000,checkpoint:0,finished:false,finishAt:0});}
  input(id:string,a:any,now:number){this.check(id,a,now);this.alive(id);const p=this.pawns[id];if(p.finished)return;if(this.id==='one-button-racing'){assert(a.type==='jump');assert(a.held===undefined||typeof a.held==='boolean');if(a.held===false){p.held=false;return;}if(p.z===0&&!p.held){p.vz=370;p.jumpAt=now;}p.held=a.held===true;}else{assert(a.type==='move'||a.type==='run');const running=a.type==='run'?(assert(typeof a.run==='boolean'),a.run):Math.hypot(...Object.values(vector(a)))>.1;p.running=running;p.moving=running;p.inputAt=now;}}
  rankings(now:number){for(const[id,p]of Object.entries(this.pawns)){this.scores[id]=Math.round(p.x*100)/100;this.placementScores[id]=p.finished?1e9-(p.finishAt-this.startedAt):p.alive?100000+p.x:p.x;this.tieBreaks[id]=[p.checkpoint,p.eliminatedAt??now];}}
  tick(now:number,delta:number){if(this.done)return;const dt=clamp(delta,0,100)/1000;if(this.id==='red-light'&&now>=this.switchAt){this.light=this.light==='green'?'red':'green';this.lightChanged=now;this.switchAt=now+(this.light==='green'?randomInt(1500,4001):randomInt(1000,3001));}
    for(const[id,p]of Object.entries(this.pawns)){if(!p.alive||p.finished)continue;if(this.id==='red-light'){const running=p.running&&now-p.inputAt<450&&!this.disconnected.has(id);if(running){if(this.light==='green')p.x+=11*dt;else if(now-this.lightChanged>100){p.alive=false;p.eliminatedAt=now;p.running=false;p.moving=false;}}}else{const old=p.x;if(p.z>0||p.vz>0){if(p.held&&now-p.jumpAt<=400)p.vz+=800*dt;p.vz-=1100*dt;p.z=Math.max(0,p.z+p.vz*dt);if(p.z===0)p.vz=0;}if(!this.disconnected.has(id))p.x+=180*dt;const crash=this.obstacles.some(x=>old<x+15&&p.x>=x-15&&p.z<42)||this.pits.some(pit=>p.x>=pit.x&&p.x<=pit.x+pit.w&&p.z<10);if(crash&&now-p.hitAt>750){p.x=p.checkpoint;p.z=0;p.vz=0;p.held=false;p.hitAt=now;}p.checkpoint=Math.max(p.checkpoint,Math.floor(p.x/1500)*1500);}if(p.x>=this.length){p.x=this.length;p.finished=true;p.finishAt=now;this.finishOrder.push(id);}}
    this.rankings(now);if(now>=this.deadline||Object.values(this.pawns).every(p=>!p.alive||p.finished))this.finish(now);}
  serialize():GameView{return{...this.base(),kind:'race',length:this.length,obstacles:[...this.obstacles],pits:this.pits,pawns:structuredClone(this.pawns),light:this.light,lightChanged:this.lightChanged,finishOrder:[...this.finishOrder]};}
}
