import {randomBytes,randomInt} from 'node:crypto';
import type {GameContext,GamePlayer,GameView} from '../../shared/types.js';
import holes from './golf-holes.json';
import {assert,number,shuffle} from './base.js';
import {ArcadeBase,clamp,distance,overlaps,seeded,type Point,type Rect} from './arcade-common.js';
export const golfCourses=holes as {name:string;par:number;start:Point;hole:Point;walls:Rect[];circles:(Point&{r:number})[];hazards:Rect[]}[];
export class GolfGame extends ArcadeBase{
  holeIndex=0;totals:Record<string,number>={};elapsed:Record<string,number>={};holeStarted=0;accumulator=0;w=1200;h=700;
  constructor(players:GamePlayer[],now:number,context?:GameContext){super('mini-golf',players,now,context);this.scoreDirection='asc';players.forEach(p=>{this.totals[p.id]=0;this.elapsed[p.id]=0;});this.setup(now);}
  setup(now:number){this.deadline=now+this.setting('time',90)*1000;this.holeStarted=now;this.round=this.holeIndex+1;this.accumulator=0;for(const p of this.players)this.pawns[p.id]={...golfCourses[this.holeIndex].start,vx:0,vy:0,alive:true,lastMove:0,strokes:0,holed:false,capped:false,shotOrigin:{...golfCourses[this.holeIndex].start}};}
  input(id:string,a:any,now:number){this.check(id,a,now);assert(a.type==='shot');const p=this.pawns[id];assert(!p.holed&&p.strokes<10);assert(Math.hypot(p.vx,p.vy)<8,'Wait until your ball stops.');const v={x:number(a.x,-1,1),y:number(a.y,-1,1)},power=number(a.power,0,100),n=Math.hypot(v.x,v.y);assert(n>.01&&power>0);p.shotOrigin={x:p.x,y:p.y};p.vx=v.x/n*power*9;p.vy=v.y/n*power*9;p.strokes++;p.lastMove=now;this.scores[id]=this.totals[id]+p.strokes;}
  pickup(id:string,now:number){const p=this.pawns[id];if(p.holed)return;p.strokes+=2;p.holed=true;p.capped=true;p.vx=0;p.vy=0;this.elapsed[id]+=now-this.holeStarted;}
  simulate(now:number){const dt=1/60,course=golfCourses[this.holeIndex];for(const[id,p]of Object.entries(this.pawns)){if(p.holed)continue;const oldX=p.x;p.x+=p.vx*dt;if(course.walls.some(w=>overlaps(p,10,w))){p.x=oldX;p.vx*=-.72;}const oldY=p.y;p.y+=p.vy*dt;if(course.walls.some(w=>overlaps(p,10,w))){p.y=oldY;p.vy*=-.72;}for(const c of course.circles){const d=distance(p,c),r=c.r+10;if(d<r){const nx=d?(p.x-c.x)/d:1,ny=d?(p.y-c.y)/d:0;p.x=c.x+nx*r;p.y=c.y+ny*r;const dot=p.vx*nx+p.vy*ny;if(dot<0){p.vx-=1.72*dot*nx;p.vy-=1.72*dot*ny;}}}p.vx*=Math.exp(-1.1*dt);p.vy*=Math.exp(-1.1*dt);
      if(p.x<0||p.x>this.w||p.y<0||p.y>this.h||course.hazards.some(w=>overlaps(p,7,w))){p.x=p.shotOrigin.x;p.y=p.shotOrigin.y;p.vx=0;p.vy=0;p.strokes++;}
      if(distance(p,course.hole)<17&&Math.hypot(p.vx,p.vy)<135){p.holed=true;p.x=course.hole.x;p.y=course.hole.y;p.vx=0;p.vy=0;this.elapsed[id]+=now-this.holeStarted;}
      if(Math.hypot(p.vx,p.vy)<8){p.vx=0;p.vy=0;if(p.strokes>=10&&!p.holed)this.pickup(id,now);}this.scores[id]=this.totals[id]+p.strokes;this.tieBreaks[id]=[-this.elapsed[id]];}}
  tick(now:number,delta:number){if(this.done)return;this.accumulator+=clamp(delta,0,250)/1000;while(this.accumulator+1e-8>=1/60){this.simulate(now);this.accumulator-=1/60;}if(now>=this.deadline||Object.values(this.pawns).every(p=>p.holed)){for(const p of this.players){const ball=this.pawns[p.id];if(!ball.holed){ball.strokes=Math.max(10,ball.strokes);this.pickup(p.id,now);}this.totals[p.id]+=ball.strokes;this.scores[p.id]=this.totals[p.id];this.tieBreaks[p.id]=[-this.elapsed[p.id]];}this.holeIndex++;if(this.holeIndex>=golfCourses.length)this.finish(now);else this.setup(now);}}
  serialize():GameView{return{...this.base(),kind:'golf',w:this.w,h:this.h,holeIndex:Math.min(golfCourses.length-1,this.holeIndex),holeCount:golfCourses.length,course:golfCourses[Math.min(golfCourses.length-1,this.holeIndex)],pawns:structuredClone(this.pawns),totals:{...this.totals},elapsed:{...this.elapsed}};}
}
export type SceneObject=Point&{id:string;shape:number;color:number;size:number;rotation:number};
type Difference={id:string;regions:(Point&{r:number})[];marker:Point};
export class DifferenceGame extends ArcadeBase{
  w=720;h=500;left:SceneObject[]=[];right:SceneObject[]=[];differences:Difference[]=[];found:Record<string,string[]>={};nextGuess:Record<string,number>={};
  constructor(players:GamePlayer[],now:number,context?:GameContext){super('spot-difference',players,now,context);this.deadline=now+this.setting('time',90)*1000;const rng=seeded(randomBytes(4).readUInt32LE());const originals:SceneObject[]=Array.from({length:30},(_,i)=>({id:randomBytes(8).toString('hex'),x:60+i%6*120,y:50+Math.floor(i/6)*100,shape:Math.floor(rng()*6),color:Math.floor(rng()*6),size:19+Math.floor(rng()*7),rotation:0})),altered=structuredClone(originals),changed=shuffle(Array.from({length:30},(_,i)=>i)).slice(0,5);changed.forEach((i,kind)=>{const old=originals[i],p=altered[i],regions=[{x:old.x,y:old.y,r:40}];if(kind===0)p.shape=-1;else if(kind===1)p.color=(p.color+1+randomInt(5))%6;else if(kind===2)p.size+=12;else if(kind===3){p.x+=24;p.y+=13;regions.push({x:p.x,y:p.y,r:40});}else p.shape=(p.shape+1+randomInt(5))%6;this.differences.push({id:randomBytes(10).toString('hex'),regions,marker:{x:p.x,y:p.y}});});this.left=shuffle(originals.map(o=>({...o,id:randomBytes(8).toString('hex')})));this.right=shuffle(altered.filter(o=>o.shape!==-1).map(o=>({...o,id:randomBytes(8).toString('hex')})));players.forEach(p=>this.found[p.id]=[]);}
  input(id:string,a:any,now:number){this.check(id,a,now);assert(a.type==='spot');const point={x:number(a.x,0,1)*this.w,y:number(a.y,0,1)*this.h};if(now<(this.nextGuess[id]??0)||this.found[id].length===5)return;const hit=this.differences.find(d=>d.regions.some(r=>distance(r,point)<=r.r));this.nextGuess[id]=now+250;if(hit&&!this.found[id].includes(hit.id)){this.found[id].push(hit.id);this.add(id,200);if(this.found[id].length===5){this.add(id,Math.ceil(500*(this.deadline-now)/(this.deadline-this.startedAt)));this.tieBreaks[id]=[-(now-this.startedAt)];}}else if(!hit)this.nextGuess[id]=now+1000;if(this.players.every(p=>this.found[p.id].length===5))this.finish(now);}
  tick(now:number,_dt:number){if(now>=this.deadline)this.finish(now);}
  serialize(id:string|null):GameView{const marks=(keys:string[])=>this.differences.filter(d=>keys.includes(d.id)).map(d=>({...d.marker}));return{...this.base(),kind:'difference',w:this.w,h:this.h,left:structuredClone(this.left),right:structuredClone(this.right),found:id?marks(this.found[id]??[]):[],foundCounts:Object.fromEntries(Object.entries(this.found).map(([p,f])=>[p,f.length])),solution:this.done?this.differences.map(d=>({...d.marker})):undefined};}
}
