import {randomBytes,randomInt} from 'node:crypto';
import type {GameContext,GamePlayer,GameView} from '../../shared/types.js';
import {assert} from './base.js';
import {ArcadeBase,cellKey,dirs,int,seeded,type Point} from './arcade-common.js';

export class TerritoryGame extends ArcadeBase {
  w=24;h=18;cells:(string|null)[]=Array(432).fill(null);choices:Record<string,number>={};stalled=0;turns:number;lastResolution:{tile:number;winner:string|null}[]=[];
  constructor(players:GamePlayer[],now:number,context?:GameContext){super('territory-wars',players,now,context);this.deadline=now+this.setting('turnSeconds',3)*1000;this.turns=this.setting('rounds',60);const spawns=[[0,0],[23,17],[23,0],[0,17],[11,0],[11,17],[0,8],[23,8]];players.forEach((p,i)=>{const[x,y]=spawns[i];this.cells[y*this.w+x]=p.id;this.scores[p.id]=1;});}
  neighbors(k:number){const x=k%this.w,y=Math.floor(k/this.w);return dirs.map(d=>({x:x+d.x,y:y+d.y})).filter(p=>p.x>=0&&p.x<this.w&&p.y>=0&&p.y<this.h).map(p=>p.y*this.w+p.x);}
  support(id:string,k:number,board=this.cells){return this.neighbors(k).filter(n=>board[n]===id).length;}
  legal(id:string,k:number){return this.cells[k]!==id&&this.support(id,k)>0;}
  input(id:string,a:any,now:number){this.check(id,a,now);assert(a.type==='claim');const k=int(a.y,0,this.h-1)*this.w+int(a.x,0,this.w-1);assert(this.legal(id,k),'Select one tile beside your territory.');this.choices[id]=k;}
  enclose(){const seen=new Set<number>();for(let start=0;start<this.cells.length;start++){if(this.cells[start]||seen.has(start))continue;const region=[start],owners=new Set<string>();let edge=false;seen.add(start);for(let i=0;i<region.length;i++){const k=region[i],x=k%this.w,y=Math.floor(k/this.w);if(x===0||x===this.w-1||y===0||y===this.h-1)edge=true;for(const n of this.neighbors(k)){const owner=this.cells[n];if(owner)owners.add(owner);else if(!seen.has(n)){seen.add(n);region.push(n);}}}if(!edge&&owners.size===1){const owner=[...owners][0];region.forEach(k=>this.cells[k]=owner);}}}
  tick(now:number,_dt:number){if(this.done||now<this.deadline)return;const before=[...this.cells],targets=new Map<number,string[]>();for(const[id,k]of Object.entries(this.choices))if(this.legal(id,k)){targets.set(k,[...(targets.get(k)??[]),id]);}this.lastResolution=[];
    for(const[k,ids]of targets){const supports=ids.map(id=>({id,n:this.support(id,k,before)})).sort((a,b)=>b.n-a.n),best=supports[0];let winner:string|null=null;if((supports.length===1||best.n>supports[1].n)&&(!before[k]||best.n>this.support(before[k]!,k,before)))winner=best.id;if(winner)this.cells[k]=winner;this.lastResolution.push({tile:k,winner});}
    this.enclose();for(const p of this.players)this.scores[p.id]=this.cells.filter(c=>c===p.id).length;
    const canExpand=this.players.some(p=>this.cells.some((c,k)=>c!==p.id&&this.support(p.id,k)>0&&(!c||this.support(p.id,k)>this.support(c,k))));this.stalled=canExpand?0:this.stalled+1;this.choices={};if(this.round>=this.turns||this.stalled>=3)this.finish(now);else{this.round++;this.deadline=now+this.setting('turnSeconds',3)*1000;}}
  serialize(id:string|null=null):GameView{return{...this.base(),kind:'territory',w:this.w,h:this.h,cells:[...this.cells],turns:this.turns,selected:id?this.choices[id]??null:null,submitted:Object.keys(this.choices),lastResolution:this.lastResolution};}
}

export interface Snake{body:Point[];direction:number;queued:number;alive:boolean;eliminatedAt?:number}
export function snakeCollisions(snakes:Record<string,Snake>,heads:Record<string,Point>,growing:Set<string>,w:number,h:number){const dead=new Set<string>(),occupied=new Set<string>(),counts=new Map<string,number>();for(const[id,s]of Object.entries(snakes))if(s.alive)for(const p of growing.has(id)?s.body:s.body.slice(0,-1))occupied.add(cellKey(p));for(const p of Object.values(heads))counts.set(cellKey(p),(counts.get(cellKey(p))??0)+1);for(const[id,p]of Object.entries(heads))if(p.x<0||p.x>=w||p.y<0||p.y>=h||occupied.has(cellKey(p))||(counts.get(cellKey(p))??0)>1)dead.add(id);return dead;}
export class SnakeGame extends ArcadeBase{
  w=50;h=36;snakes:Record<string,Snake>={};food:Point[]=[];nextStep:number;
  constructor(players:GamePlayer[],now:number,context?:GameContext){super('snake-arena',players,now,context);this.deadline=now+this.setting('time',180)*1000;this.nextStep=now+100;players.forEach((p,i)=>{const x=6+i%4*12,y=5+Math.floor(i/4)*12,direction=i%2?3:1;this.snakes[p.id]={body:Array.from({length:4},(_,j)=>({x:x-j*dirs[direction].x,y})),direction,queued:direction,alive:true};this.pawns[p.id]={x,y,alive:true,lastMove:0};});this.fillFood();}
  fillFood(){if(this.food.length>=Math.max(3,this.players.length))return;const used=new Set(Object.values(this.snakes).flatMap(s=>s.alive?s.body.map(cellKey):[]));this.food.forEach(p=>used.add(cellKey(p)));const available=Array.from({length:this.w*this.h},(_,k)=>({x:k%this.w,y:Math.floor(k/this.w)})).filter(p=>!used.has(cellKey(p)));while(this.food.length<Math.max(3,this.players.length)&&available.length)this.food.push(available.splice(randomInt(available.length),1)[0]);}
  input(id:string,a:any,now:number){this.check(id,a,now);this.alive(id);assert(a.type==='direction');const d=int(a.direction,0,3),s=this.snakes[id];assert((d+2)%4!==s.direction,'Snakes cannot reverse.');s.queued=d;}
  rank(now:number,last=false){for(const[id,s]of Object.entries(this.snakes)){this.tieBreaks[id]=[s.body.length,(s.eliminatedAt??now)-this.startedAt];this.placementScores[id]=last&&s.alive?1e9:this.scores[id];}}
  tick(now:number,_dt:number){if(this.done)return;if(now>=this.deadline){this.rank(now);this.finish(now);return;}let steps=0;while(now>=this.nextStep&&steps++<30&&!this.done){const at=this.nextStep;this.nextStep+=100;const heads:Record<string,Point>={},growing=new Set<string>();for(const[id,s]of Object.entries(this.snakes))if(s.alive){s.direction=s.queued;heads[id]={x:s.body[0].x+dirs[s.direction].x,y:s.body[0].y+dirs[s.direction].y};if(this.food.some(f=>cellKey(f)===cellKey(heads[id])))growing.add(id);}const dead=snakeCollisions(this.snakes,heads,growing,this.w,this.h);for(const[id,p]of Object.entries(heads)){const s=this.snakes[id];if(dead.has(id)){s.alive=false;s.eliminatedAt=at;this.pawns[id].alive=false;continue;}s.body.unshift(p);if(growing.has(id)){this.add(id,10);this.food=this.food.filter(f=>cellKey(f)!==cellKey(p));}else s.body.pop();}this.fillFood();const survivors=Object.values(this.snakes).filter(s=>s.alive);if(survivors.length<=1){this.rank(at,survivors.length===1);this.finish(at);}}}
  serialize():GameView{return{...this.base(),kind:'snake',w:this.w,h:this.h,snakes:structuredClone(this.snakes),food:structuredClone(this.food)};}
}

export class GridGame extends ArcadeBase{
  w=9;h=9;cells:number[]=[];warnings:Record<number,number>={};nextEvent:number;target=0;safe=false;exit:Point={x:0,y:0};lastShrink=0;roundAt:number;strikes:Record<string,number>={};finishOrder:string[]=[];pathDistances:number[]=[];
  constructor(id:string,players:GamePlayer[],now:number,context?:GameContext){super(id,players,now,context);this.deadline=now+this.setting('time',id==='maze-race'?90:120)*1000;this.nextEvent=now+2500;this.roundAt=now;if(id==='last-tile'){this.w=25;this.h=18;}if(id==='color-dash'){this.w=12;this.h=10;}if(id==='maze-race'){this.w=25;this.h=19;this.cells=Array(this.w*this.h).fill(-1);this.generateMaze();this.exit={x:this.w-2,y:this.h-2};this.calculateDistances();}else this.cells=Array(this.w*this.h).fill(0);players.forEach((p,i)=>{const point=id==='maze-race'?{x:1,y:1}:{x:1+(i%4)*Math.floor((this.w-2)/4),y:1+Math.floor(i/4)*Math.floor((this.h-2)/3)};this.pawns[p.id]={...point,alive:true,lastMove:now-200,finished:false};this.strikes[p.id]=0;});if(id==='color-dash')this.colorRound(now);}
  generateMaze(){const rng=seeded(randomBytes(4).readUInt32LE()),stack=[{x:1,y:1}];this.cells[this.w+1]=0;while(stack.length){const p=stack.at(-1)!,options=dirs.filter(d=>{const x=p.x+2*d.x,y=p.y+2*d.y;return x>0&&x<this.w-1&&y>0&&y<this.h-1&&this.cells[y*this.w+x]===-1;});if(!options.length){stack.pop();continue;}const d=options[Math.floor(rng()*options.length)],next={x:p.x+d.x*2,y:p.y+d.y*2};this.cells[(p.y+d.y)*this.w+p.x+d.x]=0;this.cells[next.y*this.w+next.x]=0;stack.push(next);}}
  calculateDistances(){this.pathDistances=Array(this.cells.length).fill(Infinity);const start=this.exit.y*this.w+this.exit.x,queue=[start];this.pathDistances[start]=0;for(let i=0;i<queue.length;i++){const k=queue[i],x=k%this.w,y=Math.floor(k/this.w);for(const d of dirs){const nx=x+d.x,ny=y+d.y,n=ny*this.w+nx;if(nx>=0&&nx<this.w&&ny>=0&&ny<this.h&&this.cells[n]!==-1&&!Number.isFinite(this.pathDistances[n])){this.pathDistances[n]=this.pathDistances[k]+1;queue.push(n);}}}}
  colorRound(now:number){const colors=Math.min(6,4+Math.floor((this.round-1)/5));this.target=randomInt(colors);this.cells=this.cells.map(()=>randomInt(colors));const minimum=Math.ceil(this.players.length/2);while(this.cells.filter(c=>c===this.target).length<minimum)this.cells[randomInt(this.cells.length)]=this.target;this.nextEvent=now+Math.max(1000,2500-(this.round-1)*100);this.safe=false;}
  input(id:string,a:any,now:number){this.check(id,a,now);this.alive(id);assert(a.type==='direction');const p=this.pawns[id];if(p.finished)return;const d=dirs[int(a.direction,0,3)],gap=this.id==='platform-panic'?200:110;if(now-p.lastMove<gap)return;p.lastMove=now;const x=p.x+d.x,y=p.y+d.y,k=y*this.w+x;if(x<0||x>=this.w||y<0||y>=this.h||this.cells[k]===-1){if(this.id==='last-tile'){this.eliminate(id,now);this.survivorEnd(now);}return;}if(this.id==='color-dash'&&this.safe&&this.cells[k]!==this.target)return;if(this.id==='last-tile')this.warnings[p.y*this.w+p.x]??=now+700;p.x=x;p.y=y;if(this.id==='maze-race'){this.scores[id]=Math.max(0,this.pathDistances[this.w+1]-this.pathDistances[k]);this.placementScores[id]=-this.pathDistances[k];if(x===this.exit.x&&y===this.exit.y){p.finished=true;p.finishAt=now;this.finishOrder.push(id);this.placementScores[id]=1e9-(now-this.startedAt);if(this.finishOrder.length===this.players.length)this.finish(now);}}}
  tick(now:number,_dt:number){if(this.done)return;if(now>=this.deadline){if(this.id==='color-dash')for(const[id,p]of Object.entries(this.pawns)){this.placementScores[id]=p.alive?10-this.strikes[id]:-this.strikes[id];this.tieBreaks[id]=[p.eliminatedAt??now];}if(this.id==='maze-race')for(const[id,p]of Object.entries(this.pawns))if(!p.finished)this.placementScores[id]=-this.pathDistances[p.y*this.w+p.x];this.finish(now);return;}if(this.id==='maze-race')return;for(const[key,at]of Object.entries(this.warnings))if(now>=at){this.cells[+key]=-1;delete this.warnings[+key];}
    if(this.id==='last-tile'&&now-this.startedAt>=30000&&now>=this.nextEvent){this.nextEvent=now+1500;const boundary=this.cells.map((v,k)=>v===-1?-1:k).filter(k=>k>=0&&dirs.some(d=>{const x=k%this.w+d.x,y=Math.floor(k/this.w)+d.y;return x<0||x>=this.w||y<0||y>=this.h||this.cells[y*this.w+x]===-1;}));for(let i=0;i<Math.min(14,boundary.length);i++)this.warnings[boundary.splice(randomInt(boundary.length),1)[0]]=now+700;}
    if(this.id==='platform-panic'&&now>=this.nextEvent){this.nextEvent=now+2500;const available=this.cells.map((v,k)=>v!==-1&&!(k in this.warnings)?k:-1).filter(k=>k>=0),count=Math.min(available.length-1,5+Math.min(7,this.round-1));for(let i=0;i<count;i++)this.warnings[available.splice(randomInt(available.length),1)[0]]=now+1000;this.round++;if(available.length<=1&&Object.keys(this.warnings).length===0){for(const[id,p]of Object.entries(this.pawns))if(p.alive)this.scores[id]=(now-this.startedAt)/1000;this.finish(now);}}
    if(this.id==='color-dash'&&now>=this.nextEvent){if(!this.safe){this.safe=true;this.nextEvent=now+1000;for(const[id,p]of Object.entries(this.pawns))if(p.alive&&this.cells[p.y*this.w+p.x]!==this.target){this.strikes[id]++;if(this.strikes[id]>=2)this.eliminate(id,now);else{const k=this.cells.indexOf(this.target);p.x=k%this.w;p.y=Math.floor(k/this.w);}}}else{if(this.round>=this.setting('rounds',20)){for(const[id,p]of Object.entries(this.pawns)){this.placementScores[id]=p.alive?10-this.strikes[id]:-this.strikes[id];this.tieBreaks[id]=[p.eliminatedAt??now];}this.finish(now);return;}this.round++;this.colorRound(now);}}
    for(const[id,p]of Object.entries(this.pawns))if(p.alive){if(this.cells[p.y*this.w+p.x]===-1)this.eliminate(id,now);else this.scores[id]=(now-this.startedAt)/1000;}this.survivorEnd(now);}
  serialize():GameView{return{...this.base(),kind:'grid',w:this.w,h:this.h,cells:[...this.cells],pawns:structuredClone(this.pawns),warnings:{...this.warnings},target:this.target,safe:this.safe,eventAt:this.nextEvent,exit:this.exit,strikes:{...this.strikes},finishOrder:[...this.finishOrder]};}
}
