import {randomInt} from 'node:crypto';
import type {GameContext,GamePlayer,GameView} from '../../shared/types.js';
import {assert,number} from './base.js';
import {ArcadeBase,clamp,distance,overlaps,vector,type Pawn,type Point,type Rect} from './arcade-common.js';
type Bullet=Point&{vx:number;vy:number;owner:string;life:number;r:number;activateAt:number;shape:'circle'|'rect';w?:number;h?:number};
export class ArenaGame extends ArcadeBase{
  w=1200;h=700;playerRadius=18;obstacles:Rect[]=[];bullets:Bullet[]=[];coins:Point[]=[];crown:Point={x:600,y:350};holder:string|null=null;protectedUntil=0;pickupAt=0;nextSpawn:number;radius=400;center:Point={x:600,y:350};
  constructor(id:string,players:GamePlayer[],now:number,context?:GameContext){super(id,players,now,context);if(id==='pixel-battle'){this.w=1600;this.h=900;this.obstacles=[{x:470,y:180,w:90,h:190},{x:1040,y:510,w:90,h:210},{x:735,y:385,w:130,h:130}];}if(id==='sumo-circles'){this.w=1100;this.h=950;this.playerRadius=28;}this.center={x:this.w/2,y:this.h/2};this.crown={...this.center};this.deadline=now+this.setting('time',id==='pixel-battle'||id==='capture-crown'?180:id==='coin-rush'?90:120)*1000;this.nextSpawn=now+1000;players.forEach((p,i)=>{const angle=i/players.length*Math.PI*2,preferred={x:this.center.x+Math.cos(angle)*Math.min(270,this.h*.32),y:this.center.y+Math.sin(angle)*Math.min(270,this.h*.32)};this.pawns[p.id]={...this.safeSpawn(preferred),alive:true,lastMove:now,vx:0,vy:0,ix:0,iy:0,mx:0,my:0,inputAt:0,health:100,lastFire:now-300,dashAt:now-3000,respawnAt:0,immune:now+1500,hold:0,deaths:0,damage:0,pickupLock:0,tagAt:0,stealLock:0,stolenFrom:0,dashUntil:0};});if(id==='coin-rush')while(this.coins.length<15)this.spawnCoin();}
  safeSpawn(preferred?:Point,excludeId?:string):Point{const clear=(p:Point)=>p.x>=40&&p.x<=this.w-40&&p.y>=40&&p.y<=this.h-40&&!this.obstacles.some(o=>overlaps(p,this.playerRadius+10,o)),free=(p:Point)=>Object.entries(this.pawns).every(([id,o])=>id===excludeId||!o.alive||distance(p,o)>this.playerRadius*3);if(preferred&&clear(preferred)&&free(preferred))return preferred;const candidates:Point[]=[];for(let y=50;y<this.h-50;y+=70)for(let x=50;x<this.w-50;x+=70)if(clear({x,y}))candidates.push({x,y});const unoccupied=candidates.filter(free),pool=unoccupied.length?unoccupied:candidates;assert(pool.length>0);return pool[randomInt(pool.length)];}
  spawnCoin(){this.coins.push({x:30+randomInt(this.w-60),y:30+randomInt(this.h-60)});}
  input(id:string,a:any,now:number){this.check(id,a,now);this.alive(id);const p=this.pawns[id];if(a.type==='move'){const v=vector(a);p.mx=v.x;p.my=v.y;p.inputAt=now;return;}if(a.type==='fire'&&this.id==='pixel-battle'){const x=number(a.x,0,this.w),y=number(a.y,0,this.h);if(now-p.lastFire<300)return;const n=Math.hypot(x-p.x,y-p.y);if(n<1)return;p.lastFire=now;this.bullets.push({x:p.x+(x-p.x)/n*24,y:p.y+(y-p.y)/n*24,vx:(x-p.x)/n*700,vy:(y-p.y)/n*700,owner:id,life:now+2000,r:5,activateAt:now,shape:'circle'});return;}if(a.type==='dash'&&['sumo-circles','coin-rush','capture-crown'].includes(this.id)){const v=vector(a),cooldown=this.id==='sumo-circles'?2000:3000;if(now-p.dashAt<cooldown||Math.hypot(v.x,v.y)<.1)return;p.ix+=v.x*500;p.iy+=v.y*500;p.dashAt=now;p.dashUntil=now+350;return;}assert(false);}
  move(p:Pawn,dt:number,bound=true){const oldX=p.x;p.x+=(p.vx+p.ix)*dt;if(this.obstacles.some(o=>overlaps(p,this.playerRadius,o))){p.x=oldX;p.vx=0;p.ix=0;}const oldY=p.y;p.y+=(p.vy+p.iy)*dt;if(this.obstacles.some(o=>overlaps(p,this.playerRadius,o))){p.y=oldY;p.vy=0;p.iy=0;}if(bound){p.x=clamp(p.x,this.playerRadius,this.w-this.playerRadius);p.y=clamp(p.y,this.playerRadius,this.h-this.playerRadius);}p.ix*=Math.exp(-4.5*dt);p.iy*=Math.exp(-4.5*dt);}
  dropCrown(now:number){if(!this.holder)return;const p=this.pawns[this.holder];this.crown={x:p.x,y:p.y};p.pickupLock=now+1000;this.holder=null;this.pickupAt=now+50;}
  crownTick(now:number,dt:number){if(this.holder&&this.disconnected.has(this.holder))this.dropCrown(now);if(!this.holder&&(this.crown.x<0||this.crown.x>this.w||this.crown.y<0||this.crown.y>this.h||this.obstacles.some(o=>overlaps(this.crown,10,o))))this.crown={...this.center};if(!this.holder&&now>=this.pickupAt){const pick=this.players.filter(p=>!this.disconnected.has(p.id)&&this.pawns[p.id].alive&&now>=this.pawns[p.id].pickupLock&&distance(this.pawns[p.id],this.crown)<this.playerRadius+12).sort((a,b)=>distance(this.pawns[a.id],this.crown)-distance(this.pawns[b.id],this.crown))[0];if(pick){this.holder=pick.id;this.protectedUntil=now+400;}}
    if(this.holder){const id=this.holder,p=this.pawns[id];p.hold+=dt*1000;this.scores[id]=Math.round(p.hold);this.crown={x:p.x,y:p.y};if(p.hold>=30000){this.finish(now);return;}if(now>=this.protectedUntil){const tag=this.players.find(other=>other.id!==id&&!this.disconnected.has(other.id)&&this.pawns[other.id].alive&&now>=this.pawns[other.id].tagAt&&distance(p,this.pawns[other.id])<this.playerRadius*2);if(tag){this.pawns[tag.id].tagAt=now+1000;this.dropCrown(now);}}}}
  spawnHazard(now:number){const side=randomInt(4),point={x:side===1?this.w+30:side===3?-30:randomInt(this.w),y:side===0?-30:side===2?this.h+30:randomInt(this.h)},target={x:100+randomInt(this.w-200),y:100+randomInt(this.h-200)},n=distance(point,target),elapsed=(now-this.startedAt)/1000,big=randomInt(5)===0,speed=190+Math.min(150,elapsed*1.5);this.bullets.push({...point,vx:(target.x-point.x)/n*speed,vy:(target.y-point.y)/n*speed,owner:'hazard',life:now+10000,r:big?32:11,activateAt:now+(big?600:0),shape:big?'rect':'circle',w:big?64:undefined,h:big?38:undefined});}
  tick(now:number,delta:number){if(this.done)return;const dt=clamp(delta,0,100)/1000;if(now>=this.deadline){for(const[id,p]of Object.entries(this.pawns))if((this.id==='dodge'||this.id==='sumo-circles')&&p.alive)this.scores[id]=(this.deadline-this.startedAt)/1000;this.finish(now);return;}if(this.id==='sumo-circles')this.radius=Math.max(220,400-Math.max(0,now-this.startedAt-30000)/250);
    for(const[id,p]of Object.entries(this.pawns)){if(!p.alive){if(this.id==='pixel-battle'&&now>=p.respawnAt)Object.assign(p,this.safeSpawn(undefined,id),{alive:true,health:100,vx:0,vy:0,ix:0,iy:0,mx:0,my:0,inputAt:0,immune:now+1500});else continue;}const active=now-p.inputAt<500&&!this.disconnected.has(id),mx=active?p.mx:0,my=active?p.my:0;if(this.id==='sumo-circles'){p.vx=(p.vx+mx*1100*dt)*Math.exp(-3*dt);p.vy=(p.vy+my*1100*dt)*Math.exp(-3*dt);const speed=Math.hypot(p.vx,p.vy);if(speed>250){p.vx*=250/speed;p.vy*=250/speed;}}else{const speed=this.id==='pixel-battle'?220:this.id==='capture-crown'&&this.holder===id?234:260;p.vx=mx*speed;p.vy=my*speed;}this.move(p,dt,this.id!=='sumo-circles');if(this.id==='sumo-circles'&&distance(p,this.center)>this.radius+this.playerRadius)this.eliminate(id,now);if((this.id==='dodge'||this.id==='sumo-circles')&&p.alive)this.scores[id]=(now-this.startedAt)/1000;if(this.id==='coin-rush')this.coins=this.coins.filter(c=>{if(distance(c,p)<this.playerRadius+10){this.add(id,1);return false;}return true;});}
    if(this.id==='sumo-circles'){const alive=Object.values(this.pawns).filter(p=>p.alive);for(let i=0;i<alive.length;i++)for(let j=i+1;j<alive.length;j++){const a=alive[i],b=alive[j],d=distance(a,b);if(d<this.playerRadius*2){const nx=d?(b.x-a.x)/d:1,ny=d?(b.y-a.y)/d:0,push=(this.playerRadius*2-d)/2;a.x-=nx*push;a.y-=ny*push;b.x+=nx*push;b.y+=ny*push;const relative=(a.vx+a.ix-b.vx-b.ix)*nx+(a.vy+a.iy-b.vy-b.iy)*ny,impulse=Math.max(0,relative)*.85+45;a.ix-=nx*impulse;a.iy-=ny*impulse;b.ix+=nx*impulse;b.iy+=ny*impulse;}}for(const[id,p]of Object.entries(this.pawns))if(p.alive&&distance(p,this.center)>this.radius+this.playerRadius)this.eliminate(id,now);this.survivorEnd(now);}
    if(this.id==='coin-rush'){for(const[id,p]of Object.entries(this.pawns))if(now<p.dashUntil)for(const[other,q]of Object.entries(this.pawns))if(id!==other&&now>=q.stealLock&&this.scores[other]>0&&distance(p,q)<this.playerRadius*2){this.add(other,-1);this.add(id,1);q.stealLock=now+2000;q.stolenFrom++;}while(this.coins.length<15)this.spawnCoin();}if(this.id==='capture-crown')this.crownTick(now,dt);
    if(this.id==='dodge'&&now>=this.nextSpawn){const rate=Math.min(8,1+Math.floor((now-this.startedAt)/10000));this.nextSpawn=now+1000/rate;if(this.bullets.length<160)this.spawnHazard(now);}
    const remaining:Bullet[]=[];for(const b of this.bullets){if(now>=b.life)continue;if(now<b.activateAt){remaining.push(b);continue;}let hit=false;for(let step=0;step<4&&!hit;step++){b.x+=b.vx*dt/4;b.y+=b.vy*dt/4;if(b.x< -100||b.x>this.w+100||b.y< -100||b.y>this.h+100||this.obstacles.some(o=>overlaps(b,b.r,o))){hit=true;break;}for(const[id,p]of Object.entries(this.pawns))if(p.alive&&id!==b.owner&&(this.id==='dodge'||now>=p.immune)&&(b.shape==='rect'?overlaps(p,this.playerRadius,{x:b.x-b.w!/2,y:b.y-b.h!/2,w:b.w!,h:b.h!}):distance(p,b)<this.playerRadius+b.r)){hit=true;if(this.id==='dodge')this.eliminate(id,now);else{const damage=Math.min(25,p.health);p.health-=25;this.pawns[b.owner].damage+=damage;if(p.health<=0){p.alive=false;p.deaths++;p.mx=0;p.my=0;p.respawnAt=now+2000;this.add(b.owner,1);}}break;}}if(!hit)remaining.push(b);}this.bullets=remaining;if(this.id==='pixel-battle')for(const[id,p]of Object.entries(this.pawns))this.tieBreaks[id]=[-p.deaths,p.damage];if(this.id==='dodge')this.survivorEnd(now);}
  serialize():GameView{return{...this.base(),kind:'arena',w:this.w,h:this.h,playerRadius:this.playerRadius,center:this.center,pawns:Object.fromEntries(Object.entries(this.pawns).map(([id,p])=>[id,{x:p.x,y:p.y,alive:p.alive,health:p.health,immune:p.immune,dashAt:p.dashAt,respawnAt:p.respawnAt,deaths:p.deaths,damage:p.damage,hold:p.hold,pickupLock:p.pickupLock}])),obstacles:this.obstacles,bullets:this.bullets.map(b=>({x:b.x,y:b.y,owner:b.owner,vx:b.vx,vy:b.vy,r:b.r,shape:b.shape,w:b.w,h:b.h,activateAt:b.activateAt})),coins:structuredClone(this.coins),crown:this.crown,holder:this.holder,radius:this.radius};}
}
