import {randomInt} from 'node:crypto';
import {BaseGame,assert,clean,norm,number,pick,shuffle} from './base.js';
import type {GameContext,GamePlayer,GameView} from '../../shared/types.js';
import {categories,commonWords,drawingWords,trivia,numeric,emojiClues,liarPrompts,fakePrompts,passwordWords,typingPhrases,impostorPairs,oddDrawingPairs,majorityPrompts,minorityPrompts,wouldRather,hangmanWords,scrambleWords} from '../content/party.js';
import {DrawingCanvasEngine,type DrawingStroke,exact,emojiNorm,categoryNorm,scramble,responseGroups,rankPoints} from './party-tools.js';

type Entry={author:string;kind:'text'|'drawing';text?:string;strokes?:DrawingStroke[];skipped?:boolean};
type PendingAnswer={value:number;at:number;lockAt:number};
const memoryIds=['memory-mayhem','sequence'],socialIds=['would-you-rather','majority-rules','minority-rules'];
const dictionary=new Set(commonWords.map(v=>v.toLowerCase()));
const defaults:Record<string,number>={'draw-guess':1,'impostor-word':3,'type-race':1,'bomb-pass':99,'guess-drawing':3,'trivia-blitz':10,'word-chain':1,'memory-mayhem':20,'the-liar':3,'higher-lower':104,'fake-answer':5,'auction-wars':10,'doodle-telephone':1,'speed-math':12,'closest-wins':8,'categories':8,'word-scramble':10,'hangman-battle':1,'password':8,'emoji-guess':10,'would-you-rather':10,'majority-rules':10,'minority-rules':10,'secret-number':5,'sequence':20};
export const partyInstructions:Record<string,string>={
 'draw-guess':'Everyone takes equal turns drawing. You have 75 seconds. Guess the exact word to earn 100–1000 points based on speed; the artist earns 250 per correct guess. Use the canvas pens, eraser, Undo and confirmed Clear. Correct answers stay hidden from other guessers.',
 'impostor-word':'Read your private card for 20 seconds, discuss for 90, then vote privately for 30. You may change your vote until the deadline. No self-votes. Correct civilian votes earn 500. A surviving impostor earns 750; ties survive by default. If caught, the impostor gets one final word guess for 500.',
 'type-race':'Type the exact sentence within 120 seconds. A typo stops progress until corrected. Paste and drop are disabled. The server confirms each typed segment. Finish time ranks first, then unfinished progress and accuracy. WPM and keystroke accuracy are displayed.',
 'bomb-pass':'Solve your private 8-second challenge to unlock passing, then choose another player. The hidden 8–20 second fuse keeps burning across passes. Wrong answers trigger a new challenge after one second. Explosions eliminate the holder. A disconnected holder forfeits after two seconds and the bomb transfers. Last survivor wins.',
 'guess-drawing':'Privately draw your assigned prompt in 45 seconds. One player receives a related but different prompt. Inspect the anonymous gallery for 20 seconds, then vote for the odd drawing. No self-votes. Normal correct voters earn 500. The odd artist earns 250 per opponent fooled and 750 if not caught.',
 'trivia-blitz':'Choose an answer within 12 seconds. Your selection confirms after half a second; you can change it during that confirmation. Correct answers earn 500 plus up to 500 for speed. Choices remain private until reveal. Ties favor faster total correct responses.',
 'word-chain':'You have eight seconds to enter an unused alphabetic dictionary word of at least two letters starting with the previous word’s last letter. Invalid guesses do not reset the timer. Two timeouts eliminate. Last active player wins; at 100 turns, fewest strikes, most valid words, then fastest average response decide.',
 'memory-mayhem':'Watch a three-step pattern, then repeat it. One step is added each round. Only the current light is transmitted during playback. Wrong input or timeout gives a strike; two strikes eliminate. Correct rounds earn 100 × round. Up to 20 rounds. Rejoining during playback waits until the next round.',
 'the-liar':'Answer the prompt honestly unless your private role says to lie. Responses stay anonymous. Write for 30 seconds, discuss for 45, then vote for 20. No self-votes. Truthful correct voters earn 500. The liar earns 200 per wrong opponent vote plus 750 if not caught.',
 'higher-lower':'Predict the next card within five seconds. Cards come from a shuffled standard deck; suits do not matter. Equal values are a push. Correct predictions earn 100; wrong or missing answers add a strike. Two strikes eliminate. Last survivor wins.',
 'fake-answer':'Invent a believable false answer in 30 seconds, then choose the truth in 20. Your fake must be unique and cannot match the truth. You cannot vote for your own fake. Choosing truth earns 1000; every opponent fooled earns the author 500. Five rounds.',
 'auction-wars':'Start with 1000 virtual dollars and bid on ten lots. You may revise a sealed integer bid until the 15-second deadline. Highest bid wins; tied highest bids favor the earliest final bid. Hidden lot values are revealed afterward. Final score is asset value plus one quarter of remaining cash.',
 'doodle-telephone':'Write a starting phrase in 30 seconds. Chains rotate through everyone, alternating a 45-second drawing and a 25-second description. Only the previous item is shown privately. Explore the complete chains with slideshow controls at the end. This game awards session participation without a competitive winner.',
 'speed-math':'Twelve ten-second problems grow from addition/subtraction to multiplication/division and two-step expressions. Results are whole numbers. One private answer per problem. Correct earns 500 plus up to 500 for speed; faster total correct responses breaks ties.',
 'closest-wins':'Estimate eight numeric facts in 20 seconds each. Closest earns 1000, second 500, third 250; exact answers add 250. Equal error shares rank points. Reveal lists guesses in order of absolute error.',
 'categories':'One category and letter, 15 seconds, one answer. The offline dictionary checks the category and accepts basic singular/plural formatting. A unique valid answer earns 500; duplicates earn 250. Eight rounds. No external judging service.',
 'word-scramble':'Unscramble ten words in 20 seconds each. Try up to twice per second. First correct earns 1000; later solvers earn 700, 600 and so on, with a 300 minimum. Correct solvers lock for that round.',
 'hangman-battle':'Solve the same word or phrase privately within 90 seconds. You have six lives. A wrong letter costs one; a wrong whole solution costs two. Repeated letters are free. First solve earns 1000, second 700, later solves 500. Other players cannot see your letters.',
 'password':'Two balanced teams alternate up to four one-word clues for each password. Both teams have a private clue-giver. Only the active team’s other members can make one collective guess per clue. Clues allow letters/hyphens but cannot contain the password or its simple stem. Correct guesses score 4/3/2/1 team points by clue number. Eight passwords.',
 'emoji-guess':'Find the object, activity or phrase described by the emoji. Twenty seconds per clue; at most two guesses per second. Articles, spacing and punctuation are ignored. First correct earns 1000; later scores descend from 700 to a minimum of 300. Ten rounds.',
 'would-you-rather':'Choose A or B privately within 12 seconds. Strict-majority choices earn 500; an even split gives everyone who answered 250. You may change your choice before the deadline. Ten rounds.',
 'majority-rules':'Choose one of the displayed options privately within 12 seconds. The largest group earns 500. If several groups tie for largest, each tied group earns 300. You may change your choice before the deadline. Ten rounds.',
 'minority-rules':'Choose privately within 12 seconds. The smallest nonempty group earns 500; tied smallest groups all score. If every occupied group has equal size, all earn 250. Empty options never win. Ten rounds.',
 'secret-number':'Race privately to find an integer from 1 to 1000 in 60 seconds. Only you see your higher/lower hints. Maximum 20 guesses and one guess per half-second. First exact earns 1000; later scores descend. If nobody solves, final distance then fewer attempts ranks the round. Five rounds.',
 'sequence':'Watch the four pads flash a three-step pattern, then repeat it privately. Patterns grow by one step. Only the current light is transmitted. Two errors/timeouts eliminate. Correct rounds earn 100 × round; up to 20 rounds. Rejoining during playback waits until the next round.'
};

/** Shared authoritative phase engine for timed questions, private words and prompt voting. */
export class PartyGame extends BaseGame {
  data:any={};submissions:Record<string,any>={};submittedAt:Record<string,number>={};alive:string[];strikes:Record<string,number>={};sequence:number[]=[];clue='';used=new Set<string>();
  readonly canvas=new DrawingCanvasEngine();private secret='';private aliases:string[]=[];private role='';private options:string[]=[];private optionOwners:string[][]=[];private galleryOrder:string[]=[];
  private chains:Entry[][]=[];private pendingEntries:Record<string,Entry>={};private pendingAnswers:Record<string,PendingAnswer>={};private phaseStart=0;private clock=0;private turnIndex=0;private turnCount=0;private fuse=0;private holderAwayAt=0;
  private reveal:any=null;private maxRounds=8;private budgets:Record<string,number>={};private assets:Record<string,number>={};private letters:Record<string,string[]>={};private guesses:Record<string,number>={};
  private typed:Record<string,string>={};private keystrokes:Record<string,number>={};private goodKeys:Record<string,number>={};private inputAt:Record<string,number>={};private progress:Record<string,number[]>={};private correctTime:Record<string,number>={};private validWords:Record<string,number>={};private memoryWaiting=new Set<string>();private privateNumbers:Record<string,{low:number;high:number;history:{value:number;hint:string}[]}>={};
  constructor(id:string,players:GamePlayer[],now:number,context?:GameContext){
    super(id,players,now,context);this.alive=players.map(p=>p.id);this.clock=now;
    for(const p of players){this.strikes[p.id]=0;this.budgets[p.id]=1000;this.assets[p.id]=0;this.correctTime[p.id]=0;this.validWords[p.id]=0;}
    this.maxRounds=Math.max(1,Math.floor(Number(this.config.rounds)||defaults[id]||8));
    if(id==='draw-guess')this.maxRounds=Math.ceil(Math.max(players.length,this.maxRounds)/players.length)*players.length;
    if(id==='doodle-telephone'){this.maxRounds=players.length;this.participationOnly=true;}
    if(id==='bomb-pass')this.maxRounds=players.length-1;if(id==='word-chain')this.maxRounds=1;
    this.startRound(now);
  }
  get strokes(){return this.canvas.canvases;}
  private draw<T>(key:string,items:readonly T[]):T{return this.drawContent(key,items);}
  private ms(key:string,seconds:number){const v=Number(this.config[key]);return Math.max(1,Math.min(600,Number.isFinite(v)&&v>0?v:seconds))*1000;}
  private phaseFor(phase:string,duration:number,now:number){this.phase=phase;this.phaseStart=now;this.deadline=now+duration;this.clock=now;}
  private active(){return this.players.filter(p=>this.alive.includes(p.id));}
  private turn(){return this.alive[(this.turnIndex+this.alive.length)%Math.max(1,this.alive.length)];}
  private all(){const required=this.active().filter(p=>!this.disconnected.has(p.id)&&!this.memoryWaiting.has(p.id));return required.length>0&&required.every(p=>p.id in this.submissions);}
  private submitted(id:string,value:any,now:number,change=false){assert(change||!(id in this.submissions),'Your answer is already locked.');this.submissions[id]=value;this.submittedAt[id]=now;}
  private speed(at:number){return 500+Math.floor(500*Math.max(0,Math.min(1,(this.deadline-at)/(this.deadline-this.phaseStart))));}
  private rewardSpeed(id:string,at:number){this.add(id,this.speed(at));this.correctTime[id]+=Math.max(0,at-this.phaseStart);this.tieBreaks[id]=[-this.correctTime[id]];}
  private reset(){this.submissions={};this.submittedAt={};this.canvas.reset();this.pendingEntries={};this.pendingAnswers={};this.inputAt={};this.progress={};this.options=[];this.optionOwners=[];this.galleryOrder=[];this.letters={};this.guesses={};this.reveal=null;this.clue='';this.aliases=[];this.memoryWaiting.clear();}
  private startRound(now:number){
    this.reset();const id=this.id;this.phaseFor('answer',this.ms('roundSeconds',20),now);
    if(id==='draw-guess'){const item=this.draw('drawing',drawingWords);this.secret=item.word;this.data={category:item.category,drawer:this.draw('drawers',this.players.map(p=>p.id)),chat:[]};this.phaseFor('draw',this.ms('roundSeconds',75),now);}
    else if(id==='impostor-word'){const item=this.draw('impostor',impostorPairs);this.secret=item.word;this.role=this.draw('impostors',this.players.map(p=>p.id));this.data={category:item.category,clues:[]};this.phaseFor('read',this.ms('readSeconds',20),now);}
    else if(id==='type-race'){this.data={phrase:this.draw('typing',typingPhrases),paceFlags:{},typeAcks:{},typeSeen:{}};this.typed={};this.keystrokes={};this.goodKeys={};this.phaseFor('race',this.ms('roundSeconds',120),now);}
    else if(id==='bomb-pass'){this.data={last:'The fuse is lit.'};this.turnIndex=randomInt(this.alive.length);this.fuse=now+randomInt(8000,20001);this.holderAwayAt=0;this.bombChallenge(now);}
    else if(id==='guess-drawing'){const pair=this.draw('odd-drawing',oddDrawingPairs);this.secret=pair.normal;this.role=this.draw('odd-artists',this.players.map(p=>p.id));this.data={category:pair.category,odd:pair.odd};this.phaseFor('draw',this.ms('roundSeconds',45),now);}
    else if(id==='trivia-blitz'){const q=this.draw('trivia',trivia);this.secret=q.answer;this.data={question:q.question};this.options=shuffle(q.options);this.phaseFor('answer',this.ms('roundSeconds',12),now);}
    else if(id==='word-chain'){this.data={previous:this.draw('chain-starts',commonWords.filter(w=>/^[a-z]{3,}$/.test(w))),last:'Use the last letter to start your word.'};this.used.add(this.data.previous);this.turnIndex=randomInt(this.alive.length);this.phaseFor('turn',this.ms('turnSeconds',8),now);}
    else if(memoryIds.includes(id)){const size=id==='memory-mayhem'&&this.round>8&&this.config.sixButtons===true?6:4;if(this.round===1)this.sequence=Array.from({length:3},()=>randomInt(size));else this.sequence.push(randomInt(size));const light=id==='sequence'?Math.max(250,500-(this.round-1)*25):Math.max(250,600-(this.round-1)*25);this.data={size,light,stepMs:light+150};this.phaseFor('show',this.sequence.length*this.data.stepMs+500,now);}
    else if(id==='the-liar'){this.role=this.draw('liars',this.players.map(p=>p.id));this.data={question:this.draw('liar',liarPrompts)};this.phaseFor('write',this.ms('roundSeconds',30),now);}
    else if(id==='higher-lower'){const current=this.data.next??this.card();this.data={current,next:this.card()};this.phaseFor('predict',this.ms('roundSeconds',5),now);}
    else if(id==='fake-answer'){const q=this.draw('fake',fakePrompts);this.secret=q.answer;this.aliases=(q as any).aliases??[];this.data={question:q.question};this.phaseFor('write',this.ms('roundSeconds',30),now);}
    else if(id==='auction-wars'){const names=['Moonstone compass','Clockwork songbird','Rainbow telescope','Tiny treasure chest','Crystal sailing ship','Golden garden key','Silver music box','Painted porcelain moon','Vintage star map','Hand-carved wooden fox'];const category=['Instruments','Curiosities','Art','Collectibles'][this.round%4];this.data={item:names[(this.round-1)%names.length],category,description:`A carefully crafted ${category.toLowerCase()} lot. Its exact value is revealed after bidding.`,value:randomInt(50,501)};for(const p of this.players)this.scores[p.id]=this.assets[p.id]+this.budgets[p.id]*0.25;this.phaseFor('bid',this.ms('roundSeconds',15),now);}
    else if(id==='doodle-telephone'){if(this.round===1)this.chains=this.players.map(()=>[]);this.phaseFor(this.round===1?'phrase':this.round%2===0?'draw':'describe',this.round===1?30000:this.round%2===0?this.ms('roundSeconds',45):25000,now);}
    else if(id==='speed-math'){this.mathQuestion();this.phaseFor('answer',this.ms('roundSeconds',10),now);}
    else if(id==='closest-wins'){const q=this.draw('numeric',numeric);this.secret=String(q.answer);this.data={question:q.question,unit:q.unit,min:q.answer<0?-1e9:0,max:1e12};}
    else if(id==='categories'){const category=this.draw('categories',Object.keys(categories)),words=categories[category].filter(w=>/^[a-z]/i.test(w)&&!/[qxz]/i.test(w[0]));const letter=pick(words.length?words:categories[category])[0].toUpperCase();this.data={category,letter,question:`${category} beginning with ${letter}`};this.phaseFor('answer',this.ms('roundSeconds',15),now);}
    else if(id==='word-scramble'){this.secret=this.draw('scramble',scrambleWords.filter(w=>/^[a-z]{4,12}$/i.test(w)));this.data={scramble:scramble(this.secret),feedback:{}};}
    else if(id==='hangman-battle'){this.secret=this.draw('hangman',hangmanWords).toLowerCase();this.data={};this.phaseFor('solve',this.ms('roundSeconds',90),now);}
    else if(id==='password'){this.secret=this.draw('password',passwordWords);const teams=[this.players.filter((_,i)=>i%2===0).map(p=>p.id),this.players.filter((_,i)=>i%2===1).map(p=>p.id)];this.data={teams,givers:teams.map(team=>team[(this.round-1)%team.length]),clueNumber:1,history:[]};this.passwordAttempt(now);}
    else if(id==='emoji-guess'){const clue=this.draw('emoji',emojiClues);this.secret=clue.acceptedAnswers[0];this.aliases=clue.acceptedAnswers.slice(1);this.data={emoji:clue.emojiSequence,category:clue.category,feedback:{}};}
    else if(id==='would-you-rather'){const pair=this.draw('rather',wouldRather);this.data={question:'Would you rather…'};this.options=[pair[0],pair[1]];this.phaseFor('answer',this.ms('roundSeconds',12),now);}
    else if(id==='majority-rules'||id==='minority-rules'){const item=this.draw(id,id==='majority-rules'?majorityPrompts:minorityPrompts);this.data={question:item.question};this.options=[...item.options];this.phaseFor('answer',this.ms('roundSeconds',12),now);}
    else if(id==='secret-number'){this.secret=String(randomInt(1,1001));this.data={};this.privateNumbers={};for(const p of this.players)this.privateNumbers[p.id]={low:1,high:1000,history:[]};this.phaseFor('deduce',this.ms('roundSeconds',60),now);}
  }
  private card(){return this.draw('comparison-deck',Array.from({length:52},(_,i)=>i))%13+1;}
  private mathQuestion(){const r=this.round;let expression:string,result:number;if(r<=4){const a=randomInt(1,51),b=randomInt(1,51);if(randomInt(2)){expression=`${a} + ${b}`;result=a+b;}else{expression=`${a} − ${b}`;result=a-b;}}
    else if(r<=8){const a=randomInt(2,13),b=randomInt(2,13);if(randomInt(2)){expression=`${a} × ${b}`;result=a*b;}else{expression=`${a*b} ÷ ${b}`;result=a;}}
    else{const a=randomInt(2,13),b=randomInt(2,13),c=randomInt(2,10);if(randomInt(2)){expression=`(${a} + ${b}) × ${c}`;result=(a+b)*c;}else{expression=`${a*b} ÷ ${b} + ${c}`;result=a+c;}}this.secret=String(result);this.data={question:expression};}
  private bombChallenge(now:number){const mode=this.draw('bomb-modes',['math','scramble','category','trivia']);let challenge:any,answer:string;
    if(mode==='math'){const a=randomInt(2,15),b=randomInt(2,15);challenge={kind:mode,question:`${a} + ${b}`};answer=String(a+b);}
    else if(mode==='scramble'){answer=this.draw('bomb-words',scrambleWords.filter(w=>w.length>=4&&w.length<=7));challenge={kind:mode,question:`Unscramble: ${scramble(answer).toUpperCase()}`};}
    else if(mode==='category'){const category=this.draw('bomb-category',Object.keys(categories)),word=pick(categories[category]);answer=word[0].toLowerCase();challenge={kind:mode,category,letter:answer,question:`Name ${category.toLowerCase()} beginning with ${answer.toUpperCase()}`};}
    else{const q=this.draw('bomb-trivia',trivia);answer=q.answer;challenge={kind:mode,question:q.question,options:shuffle(q.options)};}
    this.data.challenge=challenge;this.secret=answer;this.data.unlocked=false;this.phaseFor('challenge',this.ms('roundSeconds',8),now);
  }
  private passwordAttempt(now:number){const team=(this.round-1+this.data.clueNumber-1)%2;this.data.team=team;this.data.members=this.data.teams[team];this.data.giver=this.data.givers[team];this.clue='';this.phaseFor('clue',this.ms('roundSeconds',30),now);}
  private nextPassword(now:number){if(this.data.clueNumber>=4){this.finishRound(now,{answer:this.secret,clues:this.data.history});return;}this.data.clueNumber++;this.passwordAttempt(now);}
  private numberChoice(value:any,length:number){const v=number(value,0,length-1);assert(Number.isInteger(v));return v;}
  input(id:string,a:any,now:number){
    this.eligible(id);assert(!this.disconnected.has(id)&&this.alive.includes(id),'You are watching this round.');assert(a&&typeof a==='object'&&!Array.isArray(a));assert(a.type===undefined||['submit','type','pass','stroke','undo','clear'].includes(a.type),'That action is not available.');assert(!['reveal','finished'].includes(this.phase));assert(this.id==='bomb-pass'?now<this.fuse:now<this.deadline,'The phase has ended.');this.clock=now;
    if(['stroke','undo','clear'].includes(a.type)){assert(this.phase==='draw'&&((this.id==='draw-guess'&&this.data.drawer===id)||(['guess-drawing','doodle-telephone'].includes(this.id)&&!(id in this.submissions))));this.canvas.input(id,a,now);return;}
    const rate=['word-scramble','emoji-guess','secret-number'].includes(this.id)?500:this.id==='type-race'?25:70;assert(now-(this.inputAt[id]??-Infinity)>=rate,'Slow down a little.');this.inputAt[id]=now;
    if(this.id==='draw-guess'){assert(this.phase==='draw'&&id!==this.data.drawer&&!(id in this.submissions));const answer=clean(a.value,100);assert(answer.length>0);if(exact(answer,this.secret,this.aliases)){this.submitted(id,true,now);this.add(id,Math.max(100,1000-Math.floor((now-this.phaseStart)/100)));this.add(this.data.drawer,250);this.data.chat.push({id,text:'guessed it!',correct:true});if(this.players.filter(p=>p.id!==this.data.drawer&&!this.disconnected.has(p.id)).every(p=>p.id in this.submissions))this.finishRound(now,{answer:this.secret});}else this.data.chat.push({id,text:answer});this.data.chat=this.data.chat.slice(-20);return;}
    if(this.id==='impostor-word'){if(this.phase==='discuss'){const clue=clean(a.value,80);assert(clue&&!exact(clue,this.secret),'Give a clue without saying the secret word.');assert(!this.data.clues.some((c:any)=>c.id===id),'You already shared a clue.');this.data.clues.push({id,text:clue});return;}if(this.phase==='guess'){assert(id===this.role);const value=clean(a.value,80);assert(value);const correct=exact(value,this.secret,this.aliases);if(correct)this.add(id,500);this.finishRound(now,{...this.data.voteResult,answer:this.secret,impostor:this.role,finalGuess:value,stolen:correct});return;}this.vote(id,a.value,now);return;}
    if(this.id==='type-race'){assert(this.phase==='race'&&a.type==='type'&&!(id in this.submissions));if(a.requestId!==undefined){assert(typeof a.requestId==='string'&&/^[a-zA-Z0-9_-]{1,64}$/.test(a.requestId));if((this.data.typeSeen[id]??[]).includes(a.requestId))return;}const prior=this.typed[id]??'';assert(a.index===prior.length,'Waiting for typing confirmation.');assert(typeof a.segment==='string'&&a.segment.length>=1&&a.segment.length<=12,'Type incremental text only.');let value=prior;this.keystrokes[id]=(this.keystrokes[id]??0)+a.segment.length;for(const c of a.segment){if(c!==this.data.phrase[value.length])break;value+=c;this.goodKeys[id]=(this.goodKeys[id]??0)+1;}this.typed[id]=value;if(a.requestId!==undefined){this.data.typeAcks[id]=a.requestId;this.data.typeSeen[id]=[...(this.data.typeSeen[id]??[]),a.requestId].slice(-128);}const elapsed=now-this.phaseStart;if(elapsed>=5000&&value.length/5/(elapsed/60000)>300)this.data.paceFlags[id]=true;if(value===this.data.phrase)this.submitted(id,true,now);if(this.all())this.resolve(now);return;}
    if(this.id==='bomb-pass'){assert(id===this.turn());if(a.type==='pass'){assert(this.data.unlocked,'Solve the challenge before passing.');const target=clean(a.target,80);assert(target!==id&&this.alive.includes(target)&&!this.disconnected.has(target));this.turnIndex=this.alive.indexOf(target);this.data.last=`${this.players.find(p=>p.id===id)?.name} passed the bomb.`;this.holderAwayAt=0;this.bombChallenge(now);return;}assert(this.phase==='challenge'&&now<this.deadline&&!this.data.unlocked);const q=this.data.challenge;const value=q.kind==='trivia'?q.options[this.numberChoice(a.value,q.options.length)]:clean(a.value,80);const correct=q.kind==='category'?String(value).toLowerCase().startsWith(q.letter)&&categories[q.category].some(w=>categoryNorm(w)===categoryNorm(value)):exact(value,this.secret);if(correct){this.data.unlocked=true;this.phase='pass';}else{this.data.last='Wrong answer — a new challenge is coming.';this.phaseFor('retry',1000,now);}return;}
    if(this.id==='guess-drawing'){if(this.phase==='draw'){assert(a.type==='submit');this.submitted(id,true,now);if(this.all())this.beginGallery(now);return;}this.vote(id,a.value,now);return;}
    if(this.id==='the-liar'||this.id==='fake-answer'){if(this.phase==='write'){const value=clean(a.value,this.id==='fake-answer'?80:120);assert(value.length>=2);if(this.id==='fake-answer'){assert(!exact(value,this.secret,this.aliases),'That matches the truth. Invent a fake.');assert(!Object.values(this.submissions).some(v=>norm(v)===norm(value)),'Someone already submitted that fake. Try another.');}this.submitted(id,value,now);if(this.all())this.beginGallery(now);return;}this.vote(id,a.value,now);return;}
    if(this.id==='word-chain'){assert(this.phase==='turn'&&id===this.turn());const word=clean(a.value,40).toLowerCase();assert(/^[a-z]{2,}$/.test(word),'Use letters only, at least two.');assert(dictionary.has(word),'Choose a word in the bundled dictionary.');assert(!this.used.has(word),'That word was already used.');assert(word[0]===this.data.previous.slice(-1),'Start with the previous word’s last letter.');this.used.add(word);this.data.previous=word;this.data.last=`${this.players.find(p=>p.id===id)?.name} played ${word}`;this.validWords[id]++;this.scores[id]=this.validWords[id];this.correctTime[id]+=now-this.phaseStart;this.nextTurn(now);return;}
    if(memoryIds.includes(this.id)){assert(this.phase==='repeat'&&!this.memoryWaiting.has(id)&&!(id in this.submissions));const value=this.numberChoice(a.value,this.data.size),progress=this.progress[id]??=[];if(value!==this.sequence[progress.length]){this.strikes[id]++;this.submitted(id,false,now);}else{progress.push(value);if(progress.length===this.sequence.length){this.submitted(id,true,now);this.add(id,this.round*100);}}if(this.all())this.resolve(now);return;}
    if(this.id==='higher-lower'){assert(a.value==='higher'||a.value==='lower');this.submitted(id,a.value,now);if(this.all())this.resolve(now);return;}
    if(this.id==='auction-wars'){const bid=number(a.value,0,this.budgets[id]);assert(Number.isInteger(bid),'Bid whole dollars.');this.submitted(id,bid,now,true);return;}
    if(this.id==='doodle-telephone'){assert(['phrase','draw','describe'].includes(this.phase));const entry:Entry=this.phase==='draw'?{author:id,kind:'drawing',strokes:this.strokes[id]??[]}:{author:id,kind:'text',text:clean(a.value,100)};assert(entry.kind==='drawing'||entry.text!.length>=2);this.submitted(id,true,now);this.pendingEntries[id]=entry;if(this.all())this.resolve(now);return;}
    if(this.id==='hangman-battle'){assert(!(id in this.submissions));const value=clean(a.value,100).toLowerCase(),guess=norm(value);assert(guess.length>=1);const letters=this.letters[id]??=[];if(guess.length===1){assert(/^[a-z]$/.test(guess));if(letters.includes(guess))return;letters.push(guess);}const correct=guess.length===1?this.secret.includes(guess):exact(guess,this.secret);if(!correct)this.guesses[id]=Math.min(6,(this.guesses[id]??0)+(guess.length===1?1:2));if(exact(guess,this.secret)||this.secret.split('').every(c=>!/[a-z]/.test(c)||letters.includes(c))){const rank=Object.values(this.submissions).filter(v=>v===true).length;this.submitted(id,true,now);this.add(id,rank===0?1000:rank===1?700:500);}else if((this.guesses[id]??0)>=6)this.submitted(id,false,now);if(this.all())this.resolve(now);return;}
    if(this.id==='password'){const word=clean(a.value,60);assert(/^[a-z]+(?:-[a-z]+)*$/i.test(word),'Use exactly one token: letters and internal hyphens.');if(this.phase==='clue'){assert(id===this.data.giver);const stem=(s:string)=>norm(s).replace(/(ing|ed|es|s)$/,'');assert(!norm(word).includes(norm(this.secret))&&!stem(word).includes(stem(this.secret))&&!stem(this.secret).includes(stem(word)),'Your clue cannot contain the password or its stem.');this.clue=word;this.data.history.push({team:this.data.team,giver:id,clue:word,number:this.data.clueNumber});this.phaseFor('guess',this.ms('roundSeconds',30),now);}else{assert(this.phase==='guess'&&this.data.members.includes(id)&&!this.data.givers.includes(id),'Only this team’s guessers can answer.');this.data.history[this.data.history.length-1].guess=word;if(exact(word,this.secret)){const points=5-this.data.clueNumber;for(const member of this.data.members)this.add(member,points);this.finishRound(now,{answer:this.secret,solver:id,team:this.data.team,points,clues:this.data.history});}else this.nextPassword(now);}return;}
    if(this.id==='secret-number'){assert(this.phase==='deduce'&&!(id in this.submissions));const value=number(a.value,1,1000);assert(Number.isInteger(value));const own=this.privateNumbers[id];assert(own.history.length<20);const hint=value<Number(this.secret)?'higher':value>Number(this.secret)?'lower':'correct';own.history.push({value,hint});if(hint==='higher')own.low=Math.max(own.low,value+1);else if(hint==='lower')own.high=Math.min(own.high,value-1);else{const rank=Object.values(this.submissions).filter(v=>v===true).length+1;this.submitted(id,true,now);this.add(id,rankPoints(rank));}if(own.history.length>=20&&!(id in this.submissions))this.submitted(id,false,now);if(this.all())this.resolve(now);return;}
    if(this.id==='trivia-blitz'){assert(!(id in this.submissions));const value=this.numberChoice(a.value,this.options.length),pending=this.pendingAnswers[id];assert(!pending||now<pending.lockAt,'Your answer has confirmed.');this.pendingAnswers[id]={value,at:now,lockAt:pending?.lockAt??now+500};return;}
    if(this.id==='closest-wins')this.submitted(id,number(a.value,this.data.min,this.data.max),now);
    else if(this.id==='categories'){const value=clean(a.value,40);assert(value.length>0);this.submitted(id,value,now);}
    else if(socialIds.includes(this.id)){this.submitted(id,this.numberChoice(a.value,this.options.length),now,true);return;}
    else if(this.id==='speed-math'){assert(typeof a.value==='number'||typeof a.value==='string'&&/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(a.value.trim()),'Enter a numeric answer.');const value=Number(a.value);assert(Number.isFinite(value));this.submitted(id,value,now);}
    else if(this.id==='word-scramble'||this.id==='emoji-guess'){assert(!(id in this.submissions));const value=clean(a.value,100);assert(value);const correct=this.id==='emoji-guess'?[this.secret,...this.aliases].some(answer=>emojiNorm(value)===emojiNorm(answer)):exact(value,this.secret,this.aliases);if(correct){const rank=Object.keys(this.submissions).length+1;this.submitted(id,true,now);this.add(id,rankPoints(rank));}else this.data.feedback[id]='Not quite. Try again.';}
    else assert(false,'That action is not available.');
    if(this.all())this.resolve(now);
  }
  private vote(id:string,value:any,now:number){assert(this.phase==='vote');if(this.id==='impostor-word'){const target=clean(value,80);assert(this.players.some(p=>p.id===target)&&target!==id,'Vote for another player.');this.submitted(id,target,now,true);return;}
    const index=this.numberChoice(value,this.options.length);if(this.id==='fake-answer')assert(!this.optionOwners[index].includes(id),'You cannot choose your own fake.');else assert(this.galleryOrder[index]!==id,'You cannot vote for your own entry.');this.submitted(id,index,now);if(this.all())this.resolve(now);
  }
  private beginGallery(now:number){
    if(this.id==='fake-answer'){const values=shuffle([{text:this.secret,owners:[] as string[]},...Object.entries(this.submissions).map(([id,text])=>({text,owners:[id]}))]);this.options=values.map(v=>v.text);this.optionOwners=values.map(v=>v.owners);this.submissions={};this.submittedAt={};this.phaseFor('vote',this.ms('voteSeconds',20),now);return;}
    this.galleryOrder=shuffle(this.players.map(p=>p.id));this.options=this.galleryOrder.map(id=>this.id==='guess-drawing'?'Drawing':this.submissions[id]??'(No response)');this.submissions={};this.submittedAt={};this.phaseFor('inspect',this.id==='guess-drawing'?20000:this.ms('discussionSeconds',45),now);
  }
  private caught(counts:Record<string,number>){const top=Math.max(0,...Object.values(counts));return top>0&&counts[this.role]===top&&Object.values(counts).filter(n=>n===top).length===1&&(this.config.strictMajority!==true||top>this.players.length/2);}
  private resolve(now:number){
    const id=this.id;let result:any={answers:{...this.submissions}};
    if(id==='impostor-word'){
      if(this.phase==='read'){this.phaseFor('discuss',this.ms('discussionSeconds',90),now);return;}if(this.phase==='discuss'){this.submissions={};this.phaseFor('vote',this.ms('voteSeconds',30),now);return;}
      if(this.phase==='guess'){this.finishRound(now,{...this.data.voteResult,answer:this.secret,impostor:this.role});return;}
      const counts=responseGroups(this.submissions),caught=this.caught(counts);for(const [p,v]of Object.entries(this.submissions))if(p!==this.role&&v===this.role)this.add(p,500);
      this.data.voteResult={votes:{...this.submissions},counts,caught};if(!caught){this.add(this.role,750);this.finishRound(now,{...this.data.voteResult,answer:this.secret,impostor:this.role});}else{this.submissions={};this.phaseFor('guess',15000,now);}return;
    }
    if(id==='guess-drawing'||id==='the-liar'){
      if(this.phase==='draw'||this.phase==='write'){this.beginGallery(now);return;}if(this.phase==='inspect'){this.phaseFor('vote',this.ms('voteSeconds',20),now);return;}
      const votes=Object.fromEntries(Object.entries(this.submissions).map(([p,v])=>[p,this.galleryOrder[v]])),counts=responseGroups(votes),caught=this.caught(counts);
      for(const [p,target]of Object.entries(votes))if(p!==this.role){if(target===this.role)this.add(p,500);else this.add(this.role,id==='guess-drawing'?250:200);}if(!caught)this.add(this.role,750);
      result={votes:{...this.submissions},oddPlayer:this.role,caught,counts,answer:id==='guess-drawing'?this.secret:undefined,oddPrompt:id==='guess-drawing'?this.data.odd:undefined,gallery:this.galleryOrder.map((author,index)=>({author,index,text:this.options[index],strokes:id==='guess-drawing'?this.strokes[author]??[]:undefined}))};
    }else if(id==='fake-answer'){if(this.phase==='write'){this.beginGallery(now);return;}for(const [p,index]of Object.entries(this.submissions))if(exact(this.options[index],this.secret,this.aliases))this.add(p,1000);else for(const owner of this.optionOwners[index])if(owner!==p)this.add(owner,500);result={answer:this.secret,options:this.options.map((text,i)=>({text,owners:this.optionOwners[i],voters:Object.keys(this.submissions).filter(p=>this.submissions[p]===i)}))};}
    else if(id==='draw-guess')result={answer:this.secret};
    else if(id==='type-race'){const finishers=this.players.filter(p=>p.id in this.submissions).sort((a,b)=>this.submittedAt[a.id]-this.submittedAt[b.id]);for(const p of this.players){const index=finishers.findIndex(q=>q.id===p.id),progress=(this.typed[p.id]??'').length,accuracy=(this.goodKeys[p.id]??0)/Math.max(1,this.keystrokes[p.id]??0);if(index>=0){this.add(p.id,2000);this.correctTime[p.id]+=this.submittedAt[p.id]-this.phaseStart;this.tieBreaks[p.id]=[-this.correctTime[p.id]];}else{this.add(p.id,Math.floor(progress/this.data.phrase.length*1000));this.tieBreaks[p.id]=[accuracy];}}result={phrase:this.data.phrase,finishers:Object.fromEntries(finishers.map((p,i)=>[p.id,i+1])),racers:this.typingProgress()};}
    else if(id==='trivia-blitz'||id==='speed-math'){for(const [p,value]of Object.entries(this.submissions)){const correct=id==='trivia-blitz'?this.options[value]===this.secret:Number(value)===Number(this.secret);if(correct)this.rewardSpeed(p,this.submittedAt[p]);}result={answer:this.secret,question:this.data.question,answers:id==='trivia-blitz'?Object.fromEntries(Object.entries(this.submissions).map(([p,i])=>[p,this.options[i]])):{...this.submissions},distribution:id==='trivia-blitz'?this.options.map((text,i)=>({text,count:Object.values(this.submissions).filter(v=>v===i).length,correct:text===this.secret})):undefined};}
    else if(id==='word-scramble'||id==='emoji-guess'||id==='hangman-battle')result={answer:this.secret,answers:{...this.submissions}};
    else if(memoryIds.includes(id)){if(this.phase==='show'){this.phaseFor('repeat',this.sequence.length*1200+3000,now);return;}for(const p of this.active())if(!(p.id in this.submissions)&&!this.memoryWaiting.has(p.id))this.strikes[p.id]++;this.alive=this.alive.filter(p=>this.strikes[p]<2);for(const p of this.players)this.tieBreaks[p.id]=[-this.strikes[p.id]];if(this.alive.length===1)this.placementScores=Object.fromEntries(this.players.map(p=>[p.id,this.scores[p.id]+(this.alive.includes(p.id)?1000000:0)]));result={sequence:[...this.sequence],answers:{...this.submissions},strikes:{...this.strikes}};}
    else if(id==='higher-lower'){const correct=this.data.next>this.data.current?'higher':this.data.next<this.data.current?'lower':'equal';for(const p of this.active())if(correct!=='equal'){if(this.submissions[p.id]===correct)this.add(p.id,100);else this.strikes[p.id]++;}this.alive=this.alive.filter(p=>this.strikes[p]<2);this.placementScores=Object.fromEntries(this.players.map(p=>[p.id,this.alive.includes(p.id)?10000+this.scores[p.id]:this.scores[p.id]]));result={current:this.data.current,next:this.data.next,correct,answers:{...this.submissions}};}
    else if(id==='auction-wars'){const bidders=Object.keys(this.submissions).sort((a,b)=>this.submissions[b]-this.submissions[a]||this.submittedAt[a]-this.submittedAt[b]||this.players.findIndex(p=>p.id===a)-this.players.findIndex(p=>p.id===b)),winner=bidders[0];if(winner){this.budgets[winner]-=this.submissions[winner];this.assets[winner]+=this.data.value;}for(const p of this.players)this.scores[p.id]=this.assets[p.id]+this.budgets[p.id]*0.25;result={item:this.data.item,winner,bid:winner?this.submissions[winner]:0,value:this.data.value,bids:{...this.submissions},budgets:{...this.budgets},assets:{...this.assets}};}
    else if(id==='doodle-telephone'){for(let i=0;i<this.players.length;i++){const p=this.players[i],chain=(i-this.round+1+this.players.length)%this.players.length;this.chains[chain].push(this.pendingEntries[p.id]??(this.phase==='draw'?{author:p.id,kind:'drawing',strokes:[],skipped:true}:{author:p.id,kind:'text',text:'No contribution — continue the story freely.',skipped:true}));}if(this.round<this.maxRounds){this.round++;this.startRound(now);return;}result={chains:this.chains,participationOnly:true};}
    else if(id==='closest-wins'){const guesses=Object.entries(this.submissions).map(([p,value])=>({id:p,value,error:Math.abs(value-Number(this.secret))})).sort((a,b)=>a.error-b.error);for(const guess of guesses){const rank=1+guesses.filter(g=>g.error<guess.error).length;this.add(guess.id,(rank===1?1000:rank===2?500:rank===3?250:0)+(guess.error===0?250:0));}result={answer:this.secret,unit:this.data.unit,answers:Object.fromEntries(guesses.map(g=>[g.id,g.value])),estimates:guesses};}
    else if(id==='categories'){const counts=responseGroups(Object.fromEntries(Object.entries(this.submissions).map(([p,v])=>[p,categoryNorm(v)]))),validity:Record<string,boolean>={};for(const [p,v]of Object.entries(this.submissions)){const normalized=categoryNorm(v),valid=norm(v)[0]===this.data.letter.toLowerCase()&&categories[this.data.category].some(w=>categoryNorm(w)===normalized);validity[p]=valid;if(valid)this.add(p,counts[normalized]>1?250:500);}result={answers:{...this.submissions},validity,examples:categories[this.data.category].filter(w=>w[0].toLowerCase()===this.data.letter.toLowerCase()).slice(0,8)};}
    else if(id==='password'){this.nextPassword(now);return;}
    else if(socialIds.includes(id)){const counts=responseGroups(this.submissions),sizes=Object.values(counts),max=Math.max(0,...sizes),min=Math.min(Infinity,...sizes),topTied=sizes.filter(n=>n===max).length>1,allEqual=min===max;for(const [p,value]of Object.entries(this.submissions)){const n=counts[String(value)];let points=0;if(id==='would-you-rather')points=topTied?250:n===max?500:0;else if(id==='majority-rules')points=n===max?(topTied?300:500):0;else points=allEqual?250:n===min?500:0;this.add(p,points);}result={answers:{...this.submissions},counts,options:this.options};}
    else if(id==='secret-number'){const solved=Object.entries(this.submissions).filter(([,v])=>v===true).map(([p])=>p);if(!solved.length){const entries=this.players.filter(p=>this.privateNumbers[p.id].history.length).map(p=>{const h=this.privateNumbers[p.id].history;return{id:p.id,error:Math.abs(h.at(-1)!.value-Number(this.secret)),attempts:h.length};});for(const p of entries){const rank=1+entries.filter(other=>other.error<p.error||other.error===p.error&&other.attempts<p.attempts).length;this.add(p.id,rankPoints(rank));}}result={answer:this.secret,solvers:solved,noSolvers:!solved.length};}
    this.finishRound(now,result);
  }
  private finishRound(now:number,result:any){this.reveal=result;this.phaseFor('reveal',this.id==='doodle-telephone'?Math.max(30000,this.players.length*this.players.length*5000):6500,now);}
  private nextTurn(now:number){this.turnCount++;if(this.alive.length<=1||this.turnCount>=(Number(this.config.rounds)||100)){this.placementScores=Object.fromEntries(this.players.map(p=>[p.id,this.alive.length===1?(this.alive.includes(p.id)?100:0):-this.strikes[p.id]]));for(const p of this.players)this.tieBreaks[p.id]=[this.validWords[p.id],-this.correctTime[p.id]/Math.max(1,this.validWords[p.id])];this.finishRound(now,{winner:this.alive.length===1?this.alive[0]:undefined,lastWord:this.data.previous});return;}this.turnIndex=(this.turnIndex+1+this.alive.length)%this.alive.length;this.phaseFor('turn',this.ms('turnSeconds',8),now);}
  private bombOut(id:string,now:number,disconnected=false){this.alive=this.alive.filter(p=>p!==id);this.scores[id]=this.players.length-this.alive.length;for(const p of this.alive)this.scores[p]=this.players.length-this.alive.length+1;if(disconnected&&this.alive.length>1){this.turnIndex=randomInt(this.alive.length);this.holderAwayAt=0;this.data.last='Disconnected holder forfeited; the fuse is still burning.';this.bombChallenge(now);return;}this.reveal={exploded:id,survivors:[...this.alive],disconnected};this.phaseFor('reveal',2000,now);}
  tick(now:number,_dt:number){
    if(this.done)return;this.clock=now;
    if(this.id==='bomb-pass'&&!['reveal','finished'].includes(this.phase)){if(now>=this.fuse){this.bombOut(this.turn(),now);return;}if(this.disconnected.has(this.turn())){if(!this.holderAwayAt)this.holderAwayAt=now;if(now-this.holderAwayAt>=2000){this.bombOut(this.turn(),now,true);return;}}else this.holderAwayAt=0;if(now>=this.deadline&&!this.data.unlocked)this.bombChallenge(now);return;}
    if(this.id==='trivia-blitz'&&this.phase==='answer'){for(const [p,answer]of Object.entries(this.pendingAnswers))if(now>=answer.lockAt||now>=this.deadline){this.submitted(p,answer.value,answer.at);delete this.pendingAnswers[p];}if(this.all()){this.resolve(now);return;}}
    if(this.phase==='turn'&&this.id==='word-chain'&&now>=this.deadline){const current=this.turn();this.strikes[current]++;this.data.last=`${this.players.find(p=>p.id===current)?.name} missed a turn.`;if(this.strikes[current]>=2){this.alive=this.alive.filter(p=>p!==current);this.turnIndex--;}this.nextTurn(now);return;}
    if(now<this.deadline)return;
    if(this.phase==='reveal'){if(this.round>=this.maxRounds||(['higher-lower','bomb-pass','word-chain',...memoryIds].includes(this.id)&&this.alive.length<=1)||this.id==='word-chain'){this.done=true;this.phase='finished';return;}this.round++;this.startRound(now);return;}
    this.resolve(now);
  }
  reconnect(id:string,now:number){super.reconnect(id,now);if(memoryIds.includes(this.id)&&this.phase==='show')this.memoryWaiting.add(id);}
  private typingProgress(){return this.players.map(p=>{const text=this.typed[p.id]??'',elapsed=Math.max(1,(this.submittedAt[p.id]??this.clock)-this.phaseStart);return{id:p.id,progress:text.length/this.data.phrase.length,accuracy:Math.round(100*(this.goodKeys[p.id]??0)/Math.max(1,this.keystrokes[p.id]??0)),wpm:Math.round(text.length/5/(elapsed/60000)),finished:p.id in this.submissions};});}
  serialize(playerId:string|null):GameView{
    const pid=playerId&&this.players.some(p=>p.id===playerId)?playerId:'';const view:GameView={...this.base(),maxRounds:this.maxRounds,instructions:partyInstructions[this.id],alive:[...this.alive],strikes:{...this.strikes},submitted:Object.keys(this.submissions),youSubmitted:pid in this.submissions,canPlay:!!pid&&this.alive.includes(pid)&&!this.memoryWaiting.has(pid),phaseStart:this.phaseStart};
    if(this.phase==='reveal'||this.phase==='finished'){view.reveal=this.reveal;return view;}
    const id=this.id;
    if(id==='draw-guess'){view.drawer=this.data.drawer;view.category=this.data.category;view.strokes=this.strokes[this.data.drawer]??[];view.hint=this.secret.replace(/[a-z]/gi,'_');view.chat=this.data.chat;if(pid===this.data.drawer)view.secret=this.secret;}
    else if(id==='impostor-word'){view.category=this.data.category;view.clues=this.data.clues;if(pid){view.role=pid===this.role?'impostor':'civilian';if(pid!==this.role)view.secret=this.secret;}if(this.phase==='vote'){view.canChange=true;view.yourChoice=this.submissions[pid];}if(this.phase==='guess'){view.guesser=this.role;view.voteResult=this.data.voteResult;}}
    else if(id==='type-race'){view.phrase=this.data.phrase;view.yourText=this.typed[pid]??'';view.racers=this.typingProgress();view.paceFlag=!!this.data.paceFlags[pid];view.typingAck=this.data.typeAcks[pid];}
    else if(id==='bomb-pass'){if(this.data.unlocked)delete view.deadline;view.holder=this.turn();view.last=this.data.last;if(pid===this.turn()){view.challenge=this.data.challenge;view.unlocked=this.data.unlocked;}view.challengeStatus=this.phase;}
    else if(id==='guess-drawing'){view.category=this.data.category;if(this.phase==='draw'){if(pid)view.secret=pid===this.role?this.data.odd:this.secret;view.strokes=pid?this.strokes[pid]??[]:[];}else view.gallery=this.galleryOrder.map((author,index)=>({index,strokes:this.strokes[author]??[],yours:author===pid}));}
    else if(id==='trivia-blitz'){view.question=this.data.question;view.options=this.options;if(pid&&this.pendingAnswers[pid])view.pending={value:this.pendingAnswers[pid].value,confirmAt:this.pendingAnswers[pid].lockAt};}
    else if(id==='word-chain'){view.current=this.turn();view.previous=this.data.previous;view.last=this.data.last;view.used=[...this.used].slice(-30);view.turns=this.turnCount;view.turnLimit=Number(this.config.rounds)||100;}
    else if(memoryIds.includes(id)){view.size=this.data.size;view.length=this.sequence.length;view.waitingNextRound=this.memoryWaiting.has(pid);if(this.phase==='show'){const elapsed=this.clock-this.phaseStart-500,step=Math.floor(elapsed/this.data.stepMs);view.currentStep=step;view.currentPad=elapsed>=0&&step<this.sequence.length&&elapsed%this.data.stepMs<this.data.light?this.sequence[step]:null;view.lightUntil=view.currentPad===null?this.clock:this.phaseStart+500+step*this.data.stepMs+this.data.light;}view.progress=(this.progress[pid]??[]).length;view.yourResult=this.submissions[pid];}
    else if(id==='the-liar'){view.question=this.data.question;if(this.phase==='write'&&pid)view.role=pid===this.role?'liar':'truthful';if(this.phase==='inspect'||this.phase==='vote')view.gallery=this.galleryOrder.map((author,index)=>({index,text:this.options[index],yours:author===pid}));}
    else if(id==='higher-lower'){view.current=this.data.current;view.options=['Higher','Lower'];}
    else if(id==='fake-answer'){view.question=this.data.question;if(this.phase==='vote'){view.options=this.options;view.disabledOptions=this.optionOwners.map((owners,i)=>pid&&owners.includes(pid)?i:-1).filter(i=>i>=0);}}
    else if(id==='auction-wars'){view.item=this.data.item;view.description=this.data.description;view.category=this.data.category;view.budgets={...this.budgets};view.canChange=true;if(pid in this.submissions)view.yourBid=this.submissions[pid];}
    else if(id==='doodle-telephone'){if(pid){const index=this.players.findIndex(p=>p.id===pid),chain=(index-this.round+1+this.players.length)%this.players.length,last=this.chains[chain]?.at(-1);if(last)view.assignment=last.kind==='drawing'?{kind:'drawing',strokes:last.strokes,skipped:last.skipped}:{kind:'text',text:last.text,skipped:last.skipped};view.strokes=this.strokes[pid]??[];}}
    else if(id==='speed-math'||id==='closest-wins'||id==='categories'||socialIds.includes(id)){view.question=this.data.question;view.unit=this.data.unit;view.min=this.data.min;view.max=this.data.max;if(id==='categories'){view.category=this.data.category;view.letter=this.data.letter;}view.options=this.options;if(socialIds.includes(id)){view.canChange=true;view.yourChoice=this.submissions[pid];}}
    else if(id==='word-scramble'){view.scramble=this.data.scramble;view.feedback=this.data.feedback[pid];}
    else if(id==='hangman-battle'){view.mask=this.secret.split('').map(c=>!/[a-z]/.test(c)||(this.letters[pid]??[]).includes(c)||this.submissions[pid]===true?c:'_').join(' ');view.letters=this.letters[pid]??[];view.mistakes=this.guesses[pid]??0;view.solved=this.submissions[pid];}
    else if(id==='password'){view.team=this.data.team;view.giver=this.data.giver;view.givers=this.data.givers;view.members=this.data.members;view.teams=this.data.teams;view.clue=this.clue;view.clueNumber=this.data.clueNumber;view.clues=this.data.history;if(this.data.givers.includes(pid))view.secret=this.secret;}
    else if(id==='emoji-guess'){view.emoji=this.data.emoji;view.feedback=this.data.feedback[pid];}
    else if(id==='secret-number'){if(pid){const own=this.privateNumbers[pid];view.low=own.low;view.high=own.high;view.history=own.history.map(h=>({...h}));view.attempts=own.history.length;view.solved=this.submissions[pid]===true;}else{view.low=1;view.high=1000;view.history=[];view.attempts=0;}}
    return view;
  }
}
