export const SUITS = ['♣', '♦', '♥', '♠'] as const;
export const RANKS = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A'] as const;
export const cardRank = (card: number): number => Math.floor(card / 4) + 2;
export const cardSuit = (card: number): number => card % 4;
export const cardLabel = (card: number): string => `${RANKS[Math.floor(card / 4)]}${SUITS[cardSuit(card)]}`;
export const presidentStrength = (card: number): number => (cardRank(card) + 10) % 13;
export const BOARD_RULES: Record<string, string> = {
  'connect-four': 'Choose a column to drop a disc. Connect four horizontally, vertically, or diagonally. A full board is a draw. Each turn lasts {turnSeconds} seconds; a timeout forfeits the game. The starting player alternates on rematches. A win scores 100, a draw 50 each.',
  'ultimate-tic-tac-toe': 'Win three small boards in a row. Your chosen square sends the opponent to the corresponding small board. If it is already won or drawn, they may choose any unfinished board. If every small board finishes without a global line, the player who won more small boards wins; equal totals draw. Idle turns make a legal mark after {turnSeconds} seconds. A win scores 100, a draw 50 each.',
  'dots-boxes': 'Join neighboring dots by selecting an edge. Closing a box earns one point and another turn; one edge can close two boxes. Claim the most of the 25 boxes. A {turnSeconds}-second timeout passes without drawing an edge. Two complete consecutive idle cycles end the game using current box totals; equal totals share placement. Any legal edge resets the idle count.',
  battleship: 'Drag ships from the tray or tap a ship and its starting square. Drag placed ships to move them, use Rotate to change orientation, or Randomize the fleet. Place lengths 5, 4, 3, 3, 2 on the 10 × 10 sea without overlap; touching is allowed. Lock your fleet, then fire one unshot square per turn, even after hits. Sink all 17 enemy cells to win 100 points. Placement lasts 60 seconds; unfinished fleets are completed automatically. A {turnSeconds}-second missed shot passes; two consecutive missed turns forfeit. A legal shot clears your timeout count.',
  checkers: 'American checkers: black moves first. Men move and capture diagonally forward; kings move and capture both ways. Captures are mandatory and the same piece must continue a jump chain. Crowning ends the turn. Win when the opponent has no pieces or legal moves. Each turn lasts {turnSeconds} seconds. The first timeout grants one more turn timer; a second consecutive timeout forfeits. A legal move clears the warning. Threefold repetition or 80 quiet king turns draws. Black ownership swaps on rematches. Win: 100 points; draw: 50 each.',
  'crazy-eights': 'Match the top rank or active suit, or play an eight and choose its suit. You may instead draw ONE card even when your existing hand has a legal play. After drawing, only that new card may be played; keep it and pass if you prefer. An unplayable draw ends your turn. Seven cards each for 2 players, five for 3–8. Discards reshuffle except the top card. First empty hand wins 200 points; others score max(0, 100 − remaining hand value). Eights count 50, face cards 10, aces 1. A fully blocked deck or 30-minute cap awards the lowest hand value. After {turnSeconds} seconds, an idle player draws and passes safely.',
  president: 'President – Quick: no rank-based card exchanges. The starting player may lead any single, pair, triple, or quad of one rank. Follow with the same number of cards at a strictly higher rank: 3 low through 2 high, suits irrelevant. Passing sits you out until the trick clears. After everyone else passes, the last successful player leads any set; if they have finished, the next remaining player leads. First empty hand becomes President, then Vice-President, and play continues until one remains. Finish order awards 100 points per player behind you. Idle turns play a legal set or pass after {turnSeconds} seconds.',
};
export const boardInstructions=(id:string,turnSeconds=id==='checkers'?60:30):string=>BOARD_RULES[id].replaceAll('{turnSeconds}',String(turnSeconds));
