import type {GameMeta} from './types.js';
import {settingsFor} from './game-config.js';
export const catalog:GameMeta[]=[
  {id:"draw-guess",number:1,name:"Draw & Guess",category:"Party",min:2,max:12,icon:"✎",description:"Take the pen. Make a masterpiece. Or a mess.",instructions:"Take the pen. Make a masterpiece. Or a mess.",family:"party"},
  {id:"impostor-word",number:2,name:"Impostor Word",category:"Party",min:3,max:12,icon:"◉",description:"One of you is missing a very important word.",instructions:"One of you is missing a very important word.",family:"party"},
  {id:"territory-wars",number:3,name:"Territory Wars",category:"Strategy",min:2,max:8,icon:"▦",description:"Expand your color. Surround the competition.",instructions:"Expand your color. Surround the competition.",family:"arcade"},
  {id:"quick-draw",number:4,name:"Quick Draw",category:"Reaction",min:2,max:12,icon:"ϟ",description:"Wait for the signal. Make your move.",instructions:"Wait for the signal. Make your move.",family:"arcade"},
  {id:"type-race",number:5,name:"Type Race",category:"Words",min:2,max:10,icon:"⌨",description:"Fast fingers, fewer mistakes, first place.",instructions:"Fast fingers, fewer mistakes, first place.",family:"party"},
  {id:"snake-arena",number:6,name:"Snake Arena",category:"Arcade",min:2,max:12,icon:"〰",description:"Eat, grow, and keep your head.",instructions:"Eat, grow, and keep your head.",family:"arcade"},
  {id:"bomb-pass",number:7,name:"Bomb Pass",category:"Party",min:3,max:12,icon:"💣",description:"Answer the challenge. Get rid of the bomb.",instructions:"Answer the challenge. Get rid of the bomb.",family:"party"},
  {id:"guess-drawing",number:8,name:"Guess the Drawing",category:"Party",min:3,max:12,icon:"▧",description:"Find the artist with a different assignment.",instructions:"Find the artist with a different assignment.",family:"party"},
  {id:"trivia-blitz",number:9,name:"Trivia Blitz",category:"Trivia",min:2,max:20,icon:"?",description:"Ten questions. Many confident wrong answers.",instructions:"Ten questions. Many confident wrong answers.",family:"party"},
  {id:"word-chain",number:10,name:"Word Chain",category:"Words",min:2,max:12,icon:"↪",description:"Your last letter is their next problem.",instructions:"Your last letter is their next problem.",family:"party"},
  {id:"pixel-battle",number:11,name:"Pixel Battle",category:"Arcade",min:2,max:12,icon:"⌖",description:"A tiny arena with very big rivalries.",instructions:"A tiny arena with very big rivalries.",family:"arcade"},
  {id:"memory-mayhem",number:12,name:"Memory Mayhem",category:"Reaction",min:2,max:12,icon:"▩",description:"A growing pattern. A shrinking confidence.",instructions:"A growing pattern. A shrinking confidence.",family:"party"},
  {id:"the-liar",number:13,name:"The Liar",category:"Party",min:3,max:12,icon:"◇",description:"Read the answers. Find the person bluffing.",instructions:"Read the answers. Find the person bluffing.",family:"party"},
  {id:"higher-lower",number:14,name:"Higher or Lower",category:"Cards",min:2,max:12,icon:"↕",description:"Make the call before the next card falls.",instructions:"Make the call before the next card falls.",family:"party"},
  {id:"mini-golf",number:15,name:"Mini Golf",category:"Arcade",min:2,max:8,icon:"⚑",description:"Six holes. Few strokes. Friendly grudges.",instructions:"Six holes. Few strokes. Friendly grudges.",family:"arcade"},
  {id:"last-tile",number:16,name:"Last Tile",category:"Arcade",min:2,max:12,icon:"▣",description:"Keep moving. The floor remembers.",instructions:"Keep moving. The floor remembers.",family:"arcade"},
  {id:"one-button-racing",number:17,name:"One Button Racing",category:"Arcade",min:2,max:10,icon:"➜",description:"One button between you and the finish.",instructions:"One button between you and the finish.",family:"arcade"},
  {id:"fake-answer",number:18,name:"Fake Answer",category:"Party",min:3,max:12,icon:"✦",description:"Invent a fact that your friends will believe.",instructions:"Invent a fact that your friends will believe.",family:"party"},
  {id:"auction-wars",number:19,name:"Auction Wars",category:"Strategy",min:3,max:10,icon:"⚖",description:"Sealed bids. Limited cash. Hidden treasures.",instructions:"Sealed bids. Limited cash. Hidden treasures.",family:"party"},
  {id:"doodle-telephone",number:20,name:"Doodle Telephone",category:"Party",min:4,max:12,icon:"☎",description:"A phrase becomes a drawing becomes chaos.",instructions:"A phrase becomes a drawing becomes chaos.",family:"party"},
  {id:"connect-four",number:21,name:"Connect Four",category:"Strategy",min:2,max:2,icon:"●",description:"Four in a row. One move ahead.",instructions:"Four in a row. One move ahead.",family:"board"},
  {id:"ultimate-tic-tac-toe",number:22,name:"Ultimate Tic-Tac-Toe",category:"Strategy",min:2,max:2,icon:"#",description:"Nine boards. Every move sends a message.",instructions:"Nine boards. Every move sends a message.",family:"board"},
  {id:"dots-boxes",number:23,name:"Dots & Boxes",category:"Strategy",min:2,max:6,icon:"⊡",description:"Draw the line. Claim the square.",instructions:"Draw the line. Claim the square.",family:"board"},
  {id:"battleship",number:24,name:"Battleship",category:"Strategy",min:2,max:2,icon:"⚓",description:"Hide your fleet. Read the ocean.",instructions:"Hide your fleet. Read the ocean.",family:"board"},
  {id:"checkers",number:25,name:"Checkers",category:"Strategy",min:2,max:2,icon:"◈",description:"Jump, crown, and control the board.",instructions:"Jump, crown, and control the board.",family:"board"},
  {id:"crazy-eights",number:26,name:"Crazy Eights",category:"Cards",min:2,max:8,icon:"8",description:"Match the suit. Change the rules with an eight.",instructions:"Match the suit. Change the rules with an eight.",family:"board"},
  {id:"president",number:27,name:"President",category:"Cards",min:3,max:8,icon:"♛",description:"Play higher. Empty your hand. Take the title.",instructions:"Play higher. Empty your hand. Take the title.",family:"board"},
  {id:"speed-math",number:28,name:"Speed Math",category:"Trivia",min:2,max:12,icon:"±",description:"Quick calculations under a little pressure.",instructions:"Quick calculations under a little pressure.",family:"party"},
  {id:"closest-wins",number:29,name:"Closest Wins",category:"Trivia",min:2,max:20,icon:"≈",description:"You don’t need to know. Just get closer.",instructions:"You don’t need to know. Just get closer.",family:"party"},
  {id:"categories",number:30,name:"Categories",category:"Words",min:2,max:12,icon:"Aa",description:"One letter. One category. Think differently.",instructions:"One letter. One category. Think differently.",family:"party"},
  {id:"word-scramble",number:31,name:"Word Scramble",category:"Words",min:2,max:12,icon:"↝",description:"A perfectly good word, all mixed up.",instructions:"A perfectly good word, all mixed up.",family:"party"},
  {id:"hangman-battle",number:32,name:"Hangman Battle",category:"Words",min:2,max:8,icon:"_",description:"Uncover the word before your chances run out.",instructions:"Uncover the word before your chances run out.",family:"party"},
  {id:"password",number:33,name:"Password",category:"Words",min:4,max:12,icon:"⌑",description:"One-word clues. Team-sized brainwaves.",instructions:"One-word clues. Team-sized brainwaves.",family:"party"},
  {id:"emoji-guess",number:34,name:"Emoji Guess",category:"Trivia",min:2,max:12,icon:"☀",description:"Small pictures. Big ideas.",instructions:"Small pictures. Big ideas.",family:"party"},
  {id:"would-you-rather",number:35,name:"Would You Rather",category:"Party",min:3,max:20,icon:"⇄",description:"Pick a side. See where everyone stands.",instructions:"Pick a side. See where everyone stands.",family:"party"},
  {id:"majority-rules",number:36,name:"Majority Rules",category:"Party",min:3,max:20,icon:"≋",description:"Think like the room to take the points.",instructions:"Think like the room to take the points.",family:"party"},
  {id:"minority-rules",number:37,name:"Minority Rules",category:"Party",min:3,max:20,icon:"⋄",description:"The smallest crowd gets the last laugh.",instructions:"The smallest crowd gets the last laugh.",family:"party"},
  {id:"secret-number",number:38,name:"Secret Number",category:"Trivia",min:2,max:12,icon:"№",description:"Higher. Lower. Closer. Yours.",instructions:"Higher. Lower. Closer. Yours.",family:"party"},
  {id:"maze-race",number:39,name:"Maze Race",category:"Arcade",min:2,max:12,icon:"▥",description:"Find your way out before everyone else.",instructions:"Find your way out before everyone else.",family:"arcade"},
  {id:"platform-panic",number:40,name:"Platform Panic",category:"Arcade",min:2,max:12,icon:"▰",description:"The platforms are leaving. Are you?",instructions:"The platforms are leaving. Are you?",family:"arcade"},
  {id:"color-dash",number:41,name:"Color Dash",category:"Arcade",min:2,max:12,icon:"◐",description:"Find the right color before time runs out.",instructions:"Find the right color before time runs out.",family:"arcade"},
  {id:"sumo-circles",number:42,name:"Sumo Circles",category:"Arcade",min:2,max:8,icon:"◎",description:"Make a little space. Push everyone out.",instructions:"Make a little space. Push everyone out.",family:"arcade"},
  {id:"dodge",number:43,name:"Dodge",category:"Arcade",min:2,max:12,icon:"☄",description:"Simple plan: be somewhere else.",instructions:"Simple plan: be somewhere else.",family:"arcade"},
  {id:"coin-rush",number:44,name:"Coin Rush",category:"Arcade",min:2,max:10,icon:"◉",description:"A pocketful of coins and a roomful of rivals.",instructions:"A pocketful of coins and a roomful of rivals.",family:"arcade"},
  {id:"capture-crown",number:45,name:"Capture the Crown",category:"Arcade",min:2,max:10,icon:"♔",description:"Wear the crown. Run like you mean it.",instructions:"Wear the crown. Run like you mean it.",family:"arcade"},
  {id:"red-light",number:46,name:"Red Light",category:"Reaction",min:2,max:20,icon:"▮",description:"Green means go. Red means absolutely don’t.",instructions:"Green means go. Red means absolutely don’t.",family:"arcade"},
  {id:"reaction-tournament",number:47,name:"Reaction Tournament",category:"Reaction",min:2,max:20,icon:"ϟ",description:"A series of tiny tests for lightning reflexes.",instructions:"A series of tiny tests for lightning reflexes.",family:"arcade"},
  {id:"spot-difference",number:48,name:"Spot the Difference",category:"Trivia",min:2,max:12,icon:"◑",description:"Two scenes. Five sneaky changes.",instructions:"Two scenes. Five sneaky changes.",family:"arcade"},
  {id:"sequence",number:49,name:"Sequence",category:"Reaction",min:2,max:12,icon:"▤",description:"Watch the lights. Echo the pattern.",instructions:"Watch the lights. Echo the pattern.",family:"party"},
  {id:"button-bash",number:50,name:"Button Bash",category:"Reaction",min:2,max:12,icon:"✣",description:"Hit the command. Beat the clock.",instructions:"Hit the command. Beat the clock.",family:"arcade"}
];
const controls=[
 'Draw with mouse or touch; pick brush, color, eraser, undo or clear. Type guesses.',
 'Read your private role; discuss, choose a player to vote, and submit a final guess when eligible.',
 'Tap one legal neighboring tile during each planning turn.',
 'Press Space or tap only after GO.',
 'Type the target in the text area; correct mistakes with Backspace. Paste and drop are disabled.',
 'Use arrows, WASD or the mobile direction buttons.',
 'Answer the holder’s challenge, then choose another player to pass to.',
 'Draw your private prompt, inspect the anonymous gallery and vote for the odd drawing.',
 'Choose one of four answers; the confirmation indicator shows when it locks.',
 'Type a new dictionary word on your turn.',
 'WASD/arrows or touch controls move. Aim with pointer/touch and fire; Space fires.',
 'Watch each lit pad, then tap the pads in the same order.',
 'Write a short response; discuss the anonymous answers and vote.',
 'Tap Higher or Lower before the timer ends.',
 'Drag opposite your shot direction, or set angle and power and Shoot.',
 'Use arrows, WASD or touch direction buttons to move between tiles.',
 'Hold Space or the Jump button briefly to jump higher.',
 'Write a believable fake, then choose another answer from the shuffled list.',
 'Enter a whole-number bid; revise it until bidding closes.',
 'Write, draw and describe your private assignment; browse the final slideshow.',
 'Tap a column to drop a piece.',
 'Tap a highlighted cell in a legal small board.',
 'Tap an unclaimed horizontal or vertical edge.',
 'Drag or select/rotate ships, or randomize placement; then tap enemy cells to fire.',
 'Select a piece, then a highlighted legal destination; complete forced captures.',
 'Select a legal card and wild suit, or draw one card and play it or pass.',
 'Select matching-rank cards and Play, or Pass for the rest of the trick.',
 'Enter your numeric result and submit.',
 'Enter a numeric estimate and submit.',
 'Type one accepted word matching the category and starting letter.',
 'Type guesses using all the scrambled letters.',
 'Tap letters or submit a whole solution; your guesses stay private.',
 'Clue-givers enter one token; the designated teammate submits the team’s guess.',
 'Type the phrase or object represented by the emoji.',
 'Choose A or B privately.',
 'Choose the option you expect the most players to select.',
 'Choose the option you expect the fewest players to select.',
 'Submit private integer guesses and follow your own higher/lower hints.',
 'Use arrows, WASD or touch direction buttons through the maze.',
 'Use arrows, WASD or touch buttons to leave warned platforms.',
 'Use arrows, WASD or touch buttons to reach the named color.',
 'Move with arrows/WASD or touch controls; Space or Dash adds an impulse.',
 'Move with arrows/WASD or touch controls to avoid hazards.',
 'Move to collect coins; Space or Dash gives a short burst.',
 'Move, tag the holder and collect the dropped crown; Space or Dash boosts movement.',
 'Hold Space, W or Run during green; release before red.',
 'Follow each prompt using Space, arrow keys or the labeled on-screen choices.',
 'Tap differences in the right scene; incorrect clicks briefly pause input.',
 'Watch the current pad, then reproduce the pattern when prompted.',
 'Use arrows plus Z/X, or the six on-screen command buttons.'
];
for(const meta of catalog){meta.specId=meta.number===8?'odd_drawing':meta.number===22?'ultimate_ttt':meta.id.replaceAll('-','_');meta.minPlayers=meta.min;meta.maxPlayers=meta.max;meta.controls=controls[meta.number-1];meta.settings=settingsFor(meta.id);}
export const canonicalGameId=(id:string)=>catalog.find(g=>g.id===id||g.specId===id)?.id??id;
export const gameMeta=(id:string):GameMeta=>{const m=catalog.find(g=>g.id===canonicalGameId(id));if(!m)throw Error('Unknown game');return m;};
